# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(base_n)
add_subdirectory(html)
add_subdirectory(impl)
add_subdirectory(json)
add_subdirectory(pattern)
add_subdirectory(punycode)
add_subdirectory(render)
add_subdirectory(u16)
add_subdirectory(u32)
add_subdirectory(u8)

target_sources(erbsland-core PRIVATE
        AnyString.cpp
        AnyString.hpp
        AnyString_fwd.hpp
        AnyStringBuilder.cpp
        AnyStringBuilder.hpp
        AnyStringBuilder_fwd.hpp
        AnyStringBuilder_integer.tpp
        AnyStringEditor.hpp
        AnyStringEditor_fwd.hpp
        AsciiCategory.hpp
        BooleanFormat.cpp
        BooleanFormat.hpp
        BooleanFormat_fwd.hpp
        ByteFormat.cpp
        ByteFormat.hpp
        ByteFormat_fwd.hpp
        ByteFormatFlag.hpp
        Capitalization.hpp
        CaseSensitivity.cpp
        CaseSensitivity.hpp
        Char.cpp
        Char.hpp
        Char_fwd.hpp
        Char_unicode.cpp
        CharCompareFn.hpp
        CharRange.hpp
        CharRange_unicode.cpp
        CharSet.cpp
        CharSet.hpp
        CharSet.tpp
        CharSet_fwd.hpp
        CharSet_set_operations.cpp
        CharSet_unicode.cpp
        CharSignal.hpp
        CodeSnippet.hpp
        CodeSnippetMarker.hpp
        CombinedChar.cpp
        CombinedChar.hpp
        EncodingError.hpp
        EncodingMode.hpp
        EscapeAmount.cpp
        EscapeAmount.hpp
        EscapeFormat.cpp
        EscapeFormat.hpp
        FloatFormat.hpp
        FloatFormat_fwd.hpp
        FloatParseFlag.hpp
        FloatParseOptions.hpp
        FormatArgument.cpp
        FormatArgument.hpp
        FormatArgumentKind.hpp
        FormatAs.hpp
        FormatAs_fwd.hpp
        FormatError.hpp
        IntegerBase.cpp
        IntegerBase.hpp
        IntegerFormat.cpp
        IntegerFormat.hpp
        IntegerFormat_fwd.hpp
        IntegerFormatFlag.hpp
        IntegerParseFlag.hpp
        IntegerParseOptions.hpp
        IntegerSignMode.hpp
        LetterCase.hpp
        Literals.hpp
        NormalizationForm.hpp
        ParseNumberError.cpp
        ParseNumberError.hpp
        PlainTextRenderer.cpp
        PlainTextRenderer.hpp
        PlainTextRenderer_fwd.hpp
        ProcessCharacterFn.hpp
        ReadIntegerResult.hpp
        ReadNumberStatus.hpp
        SafeStringFlag.hpp
        StdFormat.hpp
        String.hpp
        String_fwd.hpp
        StringBomMode.hpp
        StringCharReader.cpp
        StringCharReader.hpp
        StringCharReader_fwd.hpp
        StringCharReader_integer.tpp
        StringCharReaderState.hpp
        StringCIHashMap.hpp
        StringCIHashMap_fwd.hpp
        StringCIHashSet.hpp
        StringCIHashSet_fwd.hpp
        StringCIMap.hpp
        StringCIMap_fwd.hpp
        StringCISet.hpp
        StringCISet_fwd.hpp
        StringConverter.cpp
        StringConverter.hpp
        StringConverter_fwd.hpp
        StringDecodeBuffer.cpp
        StringDecodeBuffer.hpp
        StringDecodeBuffer.tpp
        StringDecodeBuffer_scan.tpp
        StringDecoder.cpp
        StringDecoder.hpp
        StringDecoder_fwd.hpp
        StringEditor.hpp
        StringEditor_fwd.hpp
        StringEditorList.hpp
        StringEditorList_fwd.hpp
        StringEncoder.cpp
        StringEncoder.hpp
        StringEncoder_fwd.hpp
        StringEncoding.cpp
        StringEncoding.hpp
        StringFormat.hpp
        StringHashMap.hpp
        StringHashMap_fwd.hpp
        StringHashSet.hpp
        StringHashSet_fwd.hpp
        StringKind.cpp
        StringKind.hpp
        StringList.hpp
        StringList_fwd.hpp
        StringLiteral.hpp
        StringLiteral_fwd.hpp
        StringMap.hpp
        StringMap_fwd.hpp
        StringPattern.cpp
        StringPattern.hpp
        StringPattern.tpp
        StringPattern_fwd.hpp
        StringSet.hpp
        StringSet_fwd.hpp
        StringSide.hpp
        StringSplitMode.hpp
        StringSplitter.hpp
        StringSplitter_fwd.hpp
        StringTree.cpp
        StringTree.hpp
        StringTree.tpp
        StringTree_fwd.hpp
        TextDocument.cpp
        TextDocument.hpp
        TextDocument_fwd.hpp
        TextNode.cpp
        TextNode.hpp
        TextNode.tpp
        TextNode_fwd.hpp
        TextNodeData.cpp
        TextNodeData.hpp
        TextNodeData_fwd.hpp
        TextNodeType.cpp
        TextNodeType.hpp
        TextWalkResult.hpp
        TextWalkStatus.hpp
        ToString.cpp
        ToString.hpp
        TransformCharacterFn.hpp
        TruncateMode.hpp
        U16EncodingError.hpp
        U32EncodingError.hpp
        U8EncodingError.hpp
        UnicodeCategory.hpp
        UnicodeCategoryGroup.hpp
        UnicodeVersion.cpp
        UnicodeVersion.hpp
)
