// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "ConsoleLogWriterOptions.hpp"
#include "FileLogWriterOptions.hpp"
#include "LogConfiguration.hpp"
#include "LogConfigurationParser.hpp"
#include "LogEntry.hpp"
#include "LogFileMode.hpp"
#include "LogFileRotation.hpp"
#include "LogLevel.hpp"
#include "LogLevelFormat.hpp"
#include "LogLineFormat.hpp"
#include "LogManager.hpp"
#include "LogManagerOptions.hpp"
#include "LogManagerStatistics.hpp"
#include "LogMessageTruncation.hpp"
#include "LogNameFormat.hpp"
#include "LogPath.hpp"
#include "LogStream.hpp"
#include "LogTimestampZone.hpp"
#include "LogTraceSection.hpp"
#include "LogWriter.hpp"
#include "LogWriterFilter.hpp"
#include "SyslogLogWriterOptions.hpp"
#include "SyslogTransport.hpp"


