// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "Connection.hpp"
#include "ConnectionCloseContext.hpp"
#include "ConnectionCloseFn.hpp"
#include "ConnectionCloseOrigin.hpp"
#include "ConnectionEventEditor.hpp"
#include "ConnectionQuota.hpp"
#include "ConnectionQuotaLease.hpp"
#include "ConnectionState.hpp"
#include "NetworkDataFn.hpp"
#include "NetworkError.hpp"
#include "NetworkErrorContext.hpp"
#include "NetworkErrorFn.hpp"
#include "NetworkErrorPhase.hpp"
#include "NetworkErrorReason.hpp"
#include "NetworkEventFn.hpp"
#include "NetworkSendStatus.hpp"
#include "NetworkSourceState.hpp"
#include "SocketBufferLimits.hpp"


