// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "CaptureGroup.hpp"
#include "CaptureGroupIndex.hpp"
#include "CaptureRange.hpp"
#include "CharAndPosition.hpp"
#include "ErrorCategory.hpp"
#include "Feature.hpp"
#include "Features.hpp"
#include "Flag.hpp"
#include "Flags.hpp"
#include "Input.hpp"
#include "Input16.hpp"
#include "Input32.hpp"
#include "InputBase.hpp"
#include "InputPosition.hpp"
#include "Match.hpp"
#include "Match16.hpp"
#include "Match32.hpp"
#include "MatchBase.hpp"
#include "RegEx.hpp"
#include "RegExError.hpp"
#include "RegExErrorContext.hpp"
#include "Settings.hpp"


