// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "CalendarDelta.hpp"
#include "CalendarParts.hpp"
#include "Date.hpp"
#include "DateTime.hpp"
#include "DateTimePrecision.hpp"
#include "Day.hpp"
#include "DayOfWeek.hpp"
#include "DayOfWeekFormat.hpp"
#include "DayOfYear.hpp"
#include "Duration.hpp"
#include "DurationPart.hpp"
#include "ElapsedTimer.hpp"
#include "Hour.hpp"
#include "IsoTimeFormat.hpp"
#include "Literals.hpp"
#include "Minute.hpp"
#include "Month.hpp"
#include "Second.hpp"
#include "Time.hpp"
#include "TimeAmounts.hpp"
#include "TimeDelta.hpp"
#include "TimeDeltaFormat.hpp"
#include "TimeDeltaUnit.hpp"
#include "TimeOccurrenceInFold.hpp"
#include "TimePoint.hpp"
#include "TimeUnitTags.hpp"
#include "TimeWithZone.hpp"
#include "TimeZone.hpp"
#include "TimeZoneId.hpp"
#include "Year.hpp"


