# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(impl)
add_subdirectory(tz)

target_sources(erbsland-core PRIVATE
        all.hpp
        CalendarDelta.cpp
        CalendarDelta.hpp
        CalendarDeltaParts.hpp
        CalendarParts.hpp
        CalendarPartsTypes.hpp
        Date.cpp
        Date.hpp
        Date_fwd.hpp
        DateParts_fwd.hpp
        DateTime.cpp
        DateTime.hpp
        DateTime.tpp
        DateTime_calendar.cpp
        DateTime_fwd.hpp
        DateTimeParts.hpp
        DateTimePrecision.hpp
        Day.cpp
        Day.hpp
        Day_fwd.hpp
        DayOfWeek.cpp
        DayOfWeek.hpp
        DayOfWeek_fwd.hpp
        DayOfWeekFormat.hpp
        DayOfYear.cpp
        DayOfYear.hpp
        DayOfYear_fwd.hpp
        Duration.cpp
        Duration.hpp
        Duration_fwd.hpp
        DurationPart.hpp
        ElapsedTimer.hpp
        Hour.hpp
        Hour_fwd.hpp
        IsoTimeFormat.hpp
        Literals.hpp
        Minute.hpp
        Minute_fwd.hpp
        Month.cpp
        Month.hpp
        Month_fwd.hpp
        MonthDayParts_fwd.hpp
        Second.hpp
        Second_fwd.hpp
        StdFormat.hpp
        Time.cpp
        Time.hpp
        Time_fwd.hpp
        TimeAmounts.hpp
        TimeDelta.cpp
        TimeDelta.hpp
        TimeDelta_fwd.hpp
        TimeDeltaFormat.cpp
        TimeDeltaFormat.hpp
        TimeDeltaUnit.hpp
        TimeEpoch.hpp
        TimeOccurrenceInFold.hpp
        TimeParts.hpp
        TimePoint.hpp
        TimeUnitTags.hpp
        TimeUnitTypes.hpp
        TimeWithZone.cpp
        TimeWithZone.hpp
        TimeWrapResult.hpp
        TimeWrapResult_fwd.hpp
        TimeZone.cpp
        TimeZone.hpp
        TimeZoneId.hpp
        Year.cpp
        Year.hpp
        Year_fwd.hpp
        YearDayOfYearParts_fwd.hpp
        YearMonthParts_fwd.hpp
)
