// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "AlignedSource.hpp"
#include "Coordinate.hpp"
#include "CoordinateSpan.hpp"
#include "Direction.hpp"
#include "MarginPair.hpp"
#include "Margins.hpp"
#include "Position.hpp"
#include "PositionList.hpp"
#include "Rectangle.hpp"
#include "RectangleList.hpp"
#include "Size.hpp"


