// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "AccessCheck.hpp"
#include "AccessCheckResult.hpp"
#include "AccessSources.hpp"
#include "ConfError.hpp"
#include "ConfErrorCategory.hpp"
#include "ConfErrorContext.hpp"
#include "Document.hpp"
#include "DocumentBuilder.hpp"
#include "FileAccessCheck.hpp"
#include "FileSourceResolver.hpp"
#include "Float.hpp"
#include "Integer.hpp"
#include "Location.hpp"
#include "Matrix.hpp"
#include "Name.hpp"
#include "NamePath.hpp"
#include "NameType.hpp"
#include "Parser.hpp"
#include "SignatureSigner.hpp"
#include "SignatureSignerData.hpp"
#include "SignatureValidator.hpp"
#include "SignatureValidatorData.hpp"
#include "SignatureValidatorResult.hpp"
#include "Signer.hpp"
#include "Source.hpp"
#include "SourceIdentifier.hpp"
#include "SourceResolver.hpp"
#include "SourceResolverContext.hpp"
#include "TestFormat.hpp"
#include "Value.hpp"
#include "ValueIterator.hpp"
#include "ValueList.hpp"
#include "ValueMatrix.hpp"
#include "ValueType.hpp"


