// Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0

use std::env;
use std::ffi::OsString;
use std::fs;
use std::io::{Cursor, Read, Write};
use std::path::{Path, PathBuf};

use bzip2::read::{BzDecoder, BzEncoder};
use flate2::read::DeflateDecoder;
use lz4::block::CompressionMode;
use miniz_oxide::deflate::core::{
    compress as miniz_compress, CompressionStrategy, CompressorOxide, TDEFLFlush, TDEFLStatus,
};
use miniz_oxide::DataFormat;
use xz2::stream::{Action, LzmaOptions, Status, Stream};

const LEVEL_NAMES: [&str; 5] = ["fastest", "fast", "default", "high", "highest"];

#[derive(Clone, Copy)]
enum Algorithm {
    Lz4Block,
    Deflate,
    Bzip2,
    Lzma,
    Zstandard,
}

impl Algorithm {
    fn parse(value: &OsString) -> Result<Self, String> {
        match value.to_str() {
            Some("lz4-block") => Ok(Self::Lz4Block),
            Some("deflate") => Ok(Self::Deflate),
            Some("bzip2") => Ok(Self::Bzip2),
            Some("lzma") => Ok(Self::Lzma),
            Some("zstandard") => Ok(Self::Zstandard),
            Some(value) => Err(format!("unsupported algorithm: {value}")),
            None => Err("algorithm name is not valid UTF-8".to_owned()),
        }
    }

    fn name(self) -> &'static str {
        match self {
            Self::Lz4Block => "lz4-block",
            Self::Deflate => "deflate",
            Self::Bzip2 => "bzip2",
            Self::Lzma => "lzma",
            Self::Zstandard => "zstandard",
        }
    }
}

fn main() {
    if let Err(error) = run() {
        eprintln!("compression interop counterpart failed: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let arguments = env::args_os().skip(1).collect::<Vec<_>>();
    if arguments.len() == 1 && arguments[0] == "print-vectors" {
        print_vectors()?;
        return Ok(());
    }
    if arguments.len() != 4 || arguments[0] != "verify-batch" {
        return Err(
            "usage: counterpart verify-batch <algorithm> <workspace> <case-count>\n       counterpart print-vectors"
                .to_owned(),
        );
    }
    let algorithm = Algorithm::parse(&arguments[1])?;
    let workspace = PathBuf::from(&arguments[2]);
    let case_count = arguments[3]
        .to_str()
        .ok_or_else(|| "case count is not valid UTF-8".to_owned())?
        .parse::<usize>()
        .map_err(|error| format!("invalid case count: {error}"))?;
    for case_index in 0..case_count {
        verify_case(algorithm, &workspace, case_index)?;
    }
    Ok(())
}

fn print_vectors() -> Result<(), String> {
    println!("# Compression conformance vectors generated by the pinned Rust counterpart.");
    println!("# algorithm\tencoder\tversion\tvariant\toptions\tcase\tsource-hex\tcompressed-hex");
    for algorithm in [
        Algorithm::Lz4Block,
        Algorithm::Deflate,
        Algorithm::Bzip2,
        Algorithm::Lzma,
        Algorithm::Zstandard,
    ] {
        for (case_name, source) in [("empty", &[][..]), ("abc", &b"abc"[..])] {
            for (variant, compressed) in compress_variants(algorithm, source)? {
                let (encoder, version, options) = vector_metadata(algorithm, variant);
                println!(
                    "{}\t{encoder}\t{version}\t{variant}\t{options}\t{case_name}\t{}\t{}",
                    algorithm.name(),
                    to_hex(source),
                    to_hex(&compressed)
                );
            }
        }
    }
    Ok(())
}

fn vector_metadata(
    algorithm: Algorithm,
    variant: &str,
) -> (&'static str, &'static str, &'static str) {
    match (algorithm, variant) {
        (Algorithm::Lz4Block, "default") => ("LZ4", "1.10.0", "default;store-size=false"),
        (Algorithm::Lz4Block, "fast") => ("LZ4", "1.10.0", "acceleration=4;store-size=false"),
        (Algorithm::Lz4Block, "high") => ("LZ4", "1.10.0", "high-compression=12;store-size=false"),
        (Algorithm::Deflate, "stored") => (
            "miniz_oxide",
            "0.9.1",
            "level=0;strategy=default;window-bits=15;raw",
        ),
        (Algorithm::Deflate, "fixed") => (
            "miniz_oxide",
            "0.9.1",
            "level=6;strategy=fixed;window-bits=15;raw",
        ),
        (Algorithm::Deflate, "dynamic") => (
            "miniz_oxide",
            "0.9.1",
            "level=9;strategy=default;window-bits=15;raw",
        ),
        (Algorithm::Bzip2, "level-1") => ("bzip2", "1.0.8", "block-size=1"),
        (Algorithm::Bzip2, "level-5") => ("bzip2", "1.0.8", "block-size=5"),
        (Algorithm::Bzip2, "level-9") => ("bzip2", "1.0.8", "block-size=9"),
        (Algorithm::Lzma, "known-size") => ("lzma-rs", "0.3.0", "lzma-alone;unpacked-size=header"),
        (Algorithm::Lzma, "liblzma-eos-default") => (
            "liblzma",
            "5.2.5",
            "lzma-alone;preset=6;dict=8388608;lc=3;lp=0;pb=2;eos",
        ),
        (Algorithm::Lzma, "liblzma-eos-small-dictionary") => (
            "liblzma",
            "5.2.5",
            "lzma-alone;preset=1;dict=65536;lc=3;lp=0;pb=2;eos",
        ),
        (Algorithm::Lzma, "liblzma-eos-alt-properties") => (
            "liblzma",
            "5.2.5",
            "lzma-alone;preset=6;dict=262144;lc=2;lp=1;pb=1;eos",
        ),
        (Algorithm::Zstandard, "level-1-no-size") => (
            "zstd",
            "1.5.7",
            "level=1;content-size=false;checksum=false;window-log=17",
        ),
        (Algorithm::Zstandard, "level-3-size") => (
            "zstd",
            "1.5.7",
            "level=3;content-size=true;checksum=false;window-log=19",
        ),
        (Algorithm::Zstandard, "level-15-checksum") => (
            "zstd",
            "1.5.7",
            "level=15;content-size=true;checksum=true;window-log=23",
        ),
        _ => unreachable!("metadata is required for every compression variant"),
    }
}

fn to_hex(bytes: &[u8]) -> String {
    use std::fmt::Write as _;

    let mut result = String::with_capacity(bytes.len() * 2);
    for byte in bytes {
        write!(result, "{byte:02x}").expect("writing to a String cannot fail");
    }
    result
}

fn verify_case(algorithm: Algorithm, workspace: &Path, case_index: usize) -> Result<(), String> {
    let source_path = case_path(workspace, case_index, "source");
    let source = read_file(&source_path)?;
    for level in LEVEL_NAMES {
        let input_path = case_path(workspace, case_index, &format!("core-{level}"));
        let compressed = read_file(&input_path)?;
        let restored = decompress(algorithm, &compressed, source.len()).map_err(|error| {
            format!(
                "case {case_index}, Core -> Rust {} {level}: {error}",
                algorithm.name()
            )
        })?;
        if restored != source {
            return Err(format!(
                "case {case_index}, Core -> Rust {} {level}: restored data differs ({} bytes instead of {})",
                algorithm.name(),
                restored.len(),
                source.len()
            ));
        }
    }
    for (variant, compressed) in compress_variants(algorithm, &source).map_err(|error| {
        format!(
            "case {case_index}, Rust -> Core {}: {error}",
            algorithm.name()
        )
    })? {
        let output_path = case_path(workspace, case_index, &format!("reference-{variant}"));
        fs::write(&output_path, compressed)
            .map_err(|error| format!("failed to write {}: {error}", output_path.display()))?;
    }
    Ok(())
}

fn case_path(workspace: &Path, case_index: usize, kind: &str) -> PathBuf {
    workspace.join(format!("case-{case_index:03}-{kind}.bin"))
}

fn read_file(path: &Path) -> Result<Vec<u8>, String> {
    fs::read(path).map_err(|error| format!("failed to read {}: {error}", path.display()))
}

fn compress_variants(
    algorithm: Algorithm,
    source: &[u8],
) -> Result<Vec<(&'static str, Vec<u8>)>, String> {
    match algorithm {
        Algorithm::Lz4Block => Ok(vec![
            (
                "default",
                lz4::block::compress(source, Some(CompressionMode::DEFAULT), false)
                    .map_err(|error| error.to_string())?,
            ),
            (
                "fast",
                lz4::block::compress(source, Some(CompressionMode::FAST(4)), false)
                    .map_err(|error| error.to_string())?,
            ),
            (
                "high",
                lz4::block::compress(source, Some(CompressionMode::HIGHCOMPRESSION(12)), false)
                    .map_err(|error| error.to_string())?,
            ),
        ]),
        Algorithm::Deflate => Ok(vec![
            (
                "stored",
                compress_deflate(source, 0, CompressionStrategy::Default)?,
            ),
            (
                "fixed",
                compress_deflate(source, 6, CompressionStrategy::Fixed)?,
            ),
            (
                "dynamic",
                compress_deflate(source, 9, CompressionStrategy::Default)?,
            ),
        ]),
        Algorithm::Bzip2 => Ok(vec![
            ("level-1", compress_bzip2(source, 1)?),
            ("level-5", compress_bzip2(source, 5)?),
            ("level-9", compress_bzip2(source, 9)?),
        ]),
        Algorithm::Lzma => Ok(vec![
            ("known-size", compress_lzma_known_size(source)?),
            (
                "liblzma-eos-default",
                compress_lzma_liblzma(source, 6, 8 * 1024 * 1024, 3, 0, 2)?,
            ),
            (
                "liblzma-eos-small-dictionary",
                compress_lzma_liblzma(source, 1, 64 * 1024, 3, 0, 2)?,
            ),
            (
                "liblzma-eos-alt-properties",
                compress_lzma_liblzma(source, 6, 256 * 1024, 2, 1, 1)?,
            ),
        ]),
        Algorithm::Zstandard => Ok(vec![
            (
                "level-1-no-size",
                compress_zstandard(source, 1, false, false, 17)?,
            ),
            (
                "level-3-size",
                compress_zstandard(source, 3, true, false, 19)?,
            ),
            (
                "level-15-checksum",
                compress_zstandard(source, 15, true, true, 23)?,
            ),
        ]),
    }
}

fn compress_deflate(
    source: &[u8],
    level: u8,
    strategy: CompressionStrategy,
) -> Result<Vec<u8>, String> {
    let mut compressor = CompressorOxide::with_params(DataFormat::Raw, level, strategy, 15);
    let mut remaining = source;
    let mut output = vec![0; source.len().saturating_div(2).max(64)];
    let mut output_position = 0;
    loop {
        let (status, consumed, written) = miniz_compress(
            &mut compressor,
            remaining,
            &mut output[output_position..],
            TDEFLFlush::Finish,
        );
        remaining = &remaining[consumed..];
        output_position += written;
        match status {
            TDEFLStatus::Done => {
                output.truncate(output_position);
                return Ok(output);
            }
            TDEFLStatus::Okay => {
                if output.len().saturating_sub(output_position) < 64 {
                    output.resize(output.len().saturating_mul(2).max(output_position + 64), 0);
                }
            }
            status => return Err(format!("miniz deflate failed with status {status:?}")),
        }
    }
}

fn compress_bzip2(source: &[u8], level: u32) -> Result<Vec<u8>, String> {
    read_all(BzEncoder::new(source, bzip2::Compression::new(level)))
}

fn compress_lzma_known_size(source: &[u8]) -> Result<Vec<u8>, String> {
    let options = lzma_rs::compress::Options {
        unpacked_size: lzma_rs::compress::UnpackedSize::WriteToHeader(Some(source.len() as u64)),
    };
    let mut input = Cursor::new(source);
    let mut output = Vec::new();
    lzma_rs::lzma_compress_with_options(&mut input, &mut output, &options)
        .map_err(|error| error.to_string())?;
    Ok(output)
}

fn compress_lzma_liblzma(
    source: &[u8],
    preset: u32,
    dictionary_size: u32,
    lc: u32,
    lp: u32,
    pb: u32,
) -> Result<Vec<u8>, String> {
    let mut options = LzmaOptions::new_preset(preset).map_err(|error| error.to_string())?;
    options
        .dict_size(dictionary_size)
        .literal_context_bits(lc)
        .literal_position_bits(lp)
        .position_bits(pb);
    let stream = Stream::new_lzma_encoder(&options).map_err(|error| error.to_string())?;
    process_lzma(stream, source)
}

fn compress_zstandard(
    source: &[u8],
    level: i32,
    content_size: bool,
    checksum: bool,
    window_log: u32,
) -> Result<Vec<u8>, String> {
    let mut encoder =
        zstd::stream::write::Encoder::new(Vec::new(), level).map_err(|error| error.to_string())?;
    encoder
        .include_checksum(checksum)
        .map_err(|error| error.to_string())?;
    encoder
        .include_contentsize(content_size)
        .map_err(|error| error.to_string())?;
    encoder
        .window_log(window_log)
        .map_err(|error| error.to_string())?;
    if content_size {
        encoder
            .set_pledged_src_size(Some(source.len() as u64))
            .map_err(|error| error.to_string())?;
    }
    encoder
        .write_all(source)
        .map_err(|error| error.to_string())?;
    encoder.finish().map_err(|error| error.to_string())
}

fn decompress(
    algorithm: Algorithm,
    source: &[u8],
    expected_length: usize,
) -> Result<Vec<u8>, String> {
    match algorithm {
        Algorithm::Lz4Block => lz4::block::decompress(
            source,
            Some(
                i32::try_from(expected_length)
                    .map_err(|_| "LZ4 output length exceeds i32".to_owned())?,
            ),
        )
        .map_err(|error| error.to_string()),
        Algorithm::Deflate => read_all(DeflateDecoder::new(source)),
        Algorithm::Bzip2 => read_all(BzDecoder::new(source)),
        Algorithm::Lzma => process_lzma(
            Stream::new_lzma_decoder(u64::MAX).map_err(|error| error.to_string())?,
            source,
        ),
        Algorithm::Zstandard => zstd::stream::decode_all(source).map_err(|error| error.to_string()),
    }
}

fn read_all(mut reader: impl Read) -> Result<Vec<u8>, String> {
    let mut output = Vec::new();
    reader
        .read_to_end(&mut output)
        .map_err(|error| error.to_string())?;
    Ok(output)
}

fn process_lzma(mut stream: Stream, source: &[u8]) -> Result<Vec<u8>, String> {
    let mut output = Vec::with_capacity(source.len().saturating_add(4096));
    loop {
        output.reserve(64 * 1024);
        let input_position =
            usize::try_from(stream.total_in()).map_err(|_| "LZMA input position overflow")?;
        let output_position = output.len();
        let status = stream
            .process_vec(&source[input_position..], &mut output, Action::Finish)
            .map_err(|error| error.to_string())?;
        if status == Status::StreamEnd {
            return Ok(output);
        }
        if status != Status::Ok {
            return Err(format!(
                "LZMA stream ended with unexpected status: {status:?}"
            ));
        }
        if usize::try_from(stream.total_in()).map_err(|_| "LZMA input position overflow")?
            == input_position
            && output.len() == output_position
        {
            return Err("LZMA stream made no progress".to_owned());
        }
    }
}
