// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "CurrentEvents.hpp"
#include "Event.hpp"
#include "EventBackend.hpp"
#include "EventBackendId.hpp"
#include "EventBackendIdInfo.hpp"
#include "EventBackendTarget.hpp"
#include "EventCallback.hpp"
#include "EventData.hpp"
#include "EventEditor.hpp"
#include "EventId.hpp"
#include "EventIdInfo.hpp"
#include "EventLoop.hpp"
#include "EventLoopDriver.hpp"
#include "EventLoopErrorAction.hpp"
#include "EventLoopErrorHandler.hpp"
#include "EventRegistry.hpp"
#include "EventScheduler.hpp"
#include "EventSource.hpp"
#include "EventSubscription.hpp"
#include "EventThread.hpp"
#include "EventTimer.hpp"
#include "EventTimerMode.hpp"
#include "Events.hpp"
#include "ManagedEventThread.hpp"
#include "UnmanagedEventThread.hpp"


