// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "EventBackend.hpp"
#include "EventId.hpp"
#include "EventIdInfo.hpp"
#include "EventIdRegistry.hpp"
#include "EventLoop.hpp"
#include "EventPipe.hpp"
#include "EventPipeReceiver.hpp"
#include "EventPipeSender.hpp"
#include "EventSource.hpp"
#include "EventTarget.hpp"
#include "EventThread.hpp"


