// Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

#include "Event.hpp"
#include "EventBackend_fwd.hpp"
#include "EventBackendId.hpp"
#include "EventBackendTarget_fwd.hpp"
#include "EventLoopDriver_fwd.hpp"

#include "../time/TimePoint.hpp"

#include <optional>

namespace erbsland::event {

/// A backend for event loops.
/// Backends provide external event sources such as timers, files or network IO.
/// @tested{EventBackendTest}
class EventBackend {
public:
    // defaults
    virtual ~EventBackend() = default;

public: // interface
    /// Get the unique backend identifier.
    [[nodiscard]] virtual auto backendId() const noexcept -> EventBackendId = 0;
    /// Attach this backend to a backend target.
    /// @param target The target for events generated by this backend.
    /// @param driver The native wait and wake driver for attached event sources.
    virtual void attach(EventBackendTargetWeakPtr target, EventLoopDriverWeakPtr driver) = 0;
    /// Poll the backend for due events.
    /// @param now The current time point used by the loop for this poll cycle.
    virtual void poll(time::TimePoint now) = 0;
    /// Handle an event owned by this backend.
    /// @param event The event to handle.
    /// @return `true` if this backend handled the event.
    [[nodiscard]] virtual auto handleEvent(const Event &event) -> bool = 0;
    /// Get the next time point at which this backend wants to be polled.
    [[nodiscard]] virtual auto nextWakeTime() const -> std::optional<time::TimePoint> = 0;
};

}
