// Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

#include "Event.hpp"
#include "EventBackendTarget_fwd.hpp"

namespace erbsland::event {

/// A target interface for event backends.
/// @tested{EventBackendTest}
class EventBackendTarget {
public:
    // defaults
    virtual ~EventBackendTarget() = default;

public: // interface
    /// Post an event generated by a backend.
    /// @param event The event to post.
    virtual void postFromBackend(Event event) = 0;
    /// Wake this target after a backend state change.
    virtual void wakeFromBackend() noexcept = 0;
};

}
