# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0
cmake_minimum_required(VERSION 3.28)
include(BundleUtilities)
set(BU_COPY_FULL_FRAMEWORK_CONTENTS TRUE)
set(BU_CHMOD_BUNDLE_ITEMS TRUE)
if(IS_DIRECTORY "${PACKAGE_BUNDLE}")
    get_bundle_main_executable("${PACKAGE_BUNDLE}" package_executable)
    set(package_frameworks "${PACKAGE_BUNDLE}/Contents/Frameworks")
    set(package_reference_prefix "@executable_path/../Frameworks/")
else()
    set(package_executable "${PACKAGE_BUNDLE}")
    get_filename_component(package_frameworks "${PACKAGE_BUNDLE}" DIRECTORY)
    set(package_reference_prefix "@executable_path/")
endif()
if(NOT EXISTS "${package_executable}")
    message(FATAL_ERROR "Invalid macOS application bundle: ${PACKAGE_BUNDLE}")
endif()
file(CHMOD "${package_executable}" PERMISSIONS
        OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
file(GET_RUNTIME_DEPENDENCIES
        EXECUTABLES "${package_executable}"
        DIRECTORIES ${PACKAGE_LIBRARY_DIRECTORIES}
        RESOLVED_DEPENDENCIES_VAR package_resolved
        UNRESOLVED_DEPENDENCIES_VAR package_unresolved
        CONFLICTING_DEPENDENCIES_PREFIX package_conflict)
if(package_unresolved)
    message(FATAL_ERROR "Unresolved macOS runtime dependencies: ${package_unresolved}")
endif()
if(package_conflict_FILENAMES)
    message(FATAL_ERROR "Conflicting macOS runtime dependencies: ${package_conflict_FILENAMES}")
endif()
file(MAKE_DIRECTORY "${package_frameworks}")
set(package_embedded "")
foreach(package_dependency IN LISTS package_resolved)
    if(package_dependency MATCHES "^(/usr/lib/|/System/Library/)")
        continue()
    endif()
    if(package_dependency MATCHES "^(.*\\.framework)/(.+)$")
        set(package_framework_root "${CMAKE_MATCH_1}")
        set(package_framework_path "${CMAKE_MATCH_2}")
        get_filename_component(package_framework_name "${package_framework_root}" NAME)
        if(NOT EXISTS "${package_frameworks}/${package_framework_name}")
            file(COPY "${package_framework_root}" DESTINATION "${package_frameworks}")
        endif()
        list(APPEND package_embedded "${package_frameworks}/${package_framework_name}/${package_framework_path}")
    else()
        get_filename_component(package_dependency_name "${package_dependency}" NAME)
        if(NOT EXISTS "${package_frameworks}/${package_dependency_name}")
            file(COPY "${package_dependency}" DESTINATION "${package_frameworks}" FOLLOW_SYMLINK_CHAIN)
        endif()
        list(APPEND package_embedded "${package_frameworks}/${package_dependency_name}")
    endif()
endforeach()

# BundleUtilities handles absolute references and framework layout. Its current prerequisite
# scanner does not enumerate every @rpath reference, so repair those explicitly below.
fixup_bundle("${PACKAGE_BUNDLE}" "${package_embedded}" "${PACKAGE_LIBRARY_DIRECTORIES}")
if(IS_DIRECTORY "${PACKAGE_BUNDLE}")
    file(GLOB_RECURSE package_binaries LIST_DIRECTORIES FALSE
            "${PACKAGE_BUNDLE}/Contents/MacOS/*"
            "${PACKAGE_BUNDLE}/Contents/Frameworks/*")
else()
    file(GLOB_RECURSE package_binaries LIST_DIRECTORIES FALSE "${package_frameworks}/*")
endif()
foreach(package_binary IN LISTS package_binaries)
    if(IS_SYMLINK "${package_binary}")
        continue()
    endif()
    execute_process(COMMAND /usr/bin/otool -L "${package_binary}"
            OUTPUT_VARIABLE package_references ERROR_QUIET RESULT_VARIABLE package_result)
    if(NOT package_result EQUAL 0)
        continue()
    endif()
    file(CHMOD "${package_binary}" PERMISSIONS
            OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
    foreach(package_dependency IN LISTS package_resolved)
        if(package_dependency MATCHES "^(/usr/lib/|/System/Library/)")
            continue()
        endif()
        if(package_dependency MATCHES "^(.*\\.framework)/(.+)$")
            get_filename_component(package_framework_name "${CMAKE_MATCH_1}" NAME)
            set(package_relative "${package_framework_name}/${CMAKE_MATCH_2}")
        else()
            get_filename_component(package_relative "${package_dependency}" NAME)
        endif()
        string(REGEX MATCHALL "[^\n]*${package_relative}[^\n]*" package_lines "${package_references}")
        foreach(package_line IN LISTS package_lines)
            string(STRIP "${package_line}" package_line)
            string(REGEX REPLACE "[ \t]+\\(.*$" "" package_old_reference "${package_line}")
            if(package_old_reference STREQUAL "${package_binary}")
                continue()
            endif()
            if(package_old_reference MATCHES "^(/usr/lib/|/System/Library/)")
                continue()
            endif()
            set(package_new_reference "${package_reference_prefix}${package_relative}")
            execute_process(COMMAND /usr/bin/install_name_tool -change
                    "${package_old_reference}" "${package_new_reference}" "${package_binary}"
                    COMMAND_ERROR_IS_FATAL ANY)
        endforeach()
    endforeach()
endforeach()
verify_app("${PACKAGE_BUNDLE}")
