// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "X509AlgorithmIdentifier.hpp"
#include "X509BasicConstraints.hpp"
#include "X509Certificate.hpp"
#include "X509CertificateBuilder.hpp"
#include "X509CertificateBundle.hpp"
#include "X509CertificateProfile.hpp"
#include "X509CertificateProfileIssue.hpp"
#include "X509CertificateProfileIssueCategory.hpp"
#include "X509CertificateProfileMode.hpp"
#include "X509CertificateSigningRequest.hpp"
#include "X509CertificateValidation.hpp"
#include "X509CertificateValidationFailure.hpp"
#include "X509CertificateValidationFailureCategory.hpp"
#include "X509Extension.hpp"
#include "X509GeneralName.hpp"
#include "X509KeyUsage.hpp"
#include "X509Name.hpp"
#include "X509NameAttribute.hpp"
#include "X509RelativeDistinguishedName.hpp"
#include "X509ServerCertificatePolicy.hpp"
#include "X509Version.hpp"


