# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(HostLookupFailure)
add_subdirectory(HostLookupCancel)
add_subdirectory(HostLookupDomain)
add_subdirectory(HostLookupEventThread)
add_subdirectory(HostLookupLifetime)
add_subdirectory(HostLookupNumeric)
add_subdirectory(HttpsServer)
add_subdirectory(NetworkValues)
add_subdirectory(TcpMapClient)
add_subdirectory(TcpMapServer)
add_subdirectory(TimeClient)
add_subdirectory(TimeServer)
add_subdirectory(UdpSockets)
