// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "Url.hpp"
#include "UrlFormatOptions.hpp"
#include "UrlParseOptions.hpp"
#include "UrlScheme.hpp"


