// Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

#include "ZstandardHuffmanTable.hpp"
#include "ZstandardSequenceCode.hpp"
#include "ZstandardSequenceTable.hpp"

#include "../../../mem/ByteBlockEditor_fwd.hpp"
#include "../../../mem/ByteBuffer.hpp"
#include "../../../mem/ByteSpan.hpp"

#include <array>
#include <cstddef>
#include <cstdint>

namespace erbsland::compression::impl {

/// Stateful decoder for dictionaryless Zstandard compressed blocks.
/// @tested{ZstandardInternalTest}
class ZstandardDecoder final {
public:
    /// Create a decoder for one frame.
    ZstandardDecoder(mem::ByteBlockEditor &output, std::size_t windowSize, std::size_t maximumOutputLength) noexcept;

public: // decode
    /// Decode one compressed block and append its regenerated bytes.
    void decodeBlock(mem::ConstByteSpan data);

private:
    /// Decode a block's literals section and return the following byte position.
    [[nodiscard]] auto decodeLiterals(mem::ConstByteSpan data) -> std::size_t;
    /// Decode a raw or RLE literals section.
    [[nodiscard]] auto decodeRawLiterals(mem::ConstByteSpan data, uint8_t header, std::size_t position) -> std::size_t;
    /// Decode a compressed or treeless literals section.
    [[nodiscard]] auto decodeHuffmanLiterals(mem::ConstByteSpan data, uint8_t header, std::size_t position)
        -> std::size_t;
    /// Decode a four-stream Huffman payload.
    void decodeFourHuffmanStreams(
        mem::ConstByteSpan data, std::size_t position, std::size_t size, std::size_t regeneratedSize);
    /// Parse the sequence count and table modes.
    [[nodiscard]] auto initializeSequences(mem::ConstByteSpan data, std::size_t &position) -> std::size_t;
    /// Apply one sequence table mode.
    void initializeSequenceTable(
        mem::ConstByteSpan data,
        std::size_t &position,
        ZstandardSequenceCode kind,
        uint8_t mode,
        ZstandardSequenceTable &table);
    /// Decode and execute all sequences in a block.
    void executeSequences(mem::ConstByteSpan data, std::size_t position, std::size_t sequenceCount);
    /// Resolve and update one decoded repeat offset.
    [[nodiscard]] auto resolveOffset(uint32_t encodedOffset, uint8_t offsetBits, uint32_t literalLength) -> uint32_t;
    /// Append literal bytes from the current literals buffer.
    void appendLiterals(std::size_t count, std::size_t &literalPosition);
    /// Append a possibly overlapping match from the frame history.
    void appendMatch(uint32_t offset, uint32_t length);
    /// Verify that regenerated output can grow by `count` bytes.
    void requireOutputSpace(std::size_t count) const;

private:
    mem::ByteBlockEditor &_output;                       ///< Complete frame output and match history.
    std::size_t _windowSize;                             ///< Maximum permitted match offset.
    std::size_t _maximumOutputLength;                    ///< Configured output limit.
    std::size_t _blockBegin{};                           ///< Output length before the current block.
    std::size_t _maximumBlockSize{};                     ///< Effective block regeneration limit.
    mem::ByteBuffer _literals;                           ///< Current regenerated literals.
    ZstandardHuffmanTable _huffmanTable;                 ///< Reusable literal table.
    ZstandardSequenceTable _literalLengthTable;          ///< Reusable literal-length table.
    ZstandardSequenceTable _offsetTable;                 ///< Reusable offset table.
    ZstandardSequenceTable _matchLengthTable;            ///< Reusable match-length table.
    std::array<uint32_t, 3U> _repeatOffsets{1U, 4U, 8U}; ///< Most recent offsets.
};

}
