// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "CpuArchitecture.hpp"
#include "EnvironmentVariables.hpp"
#include "FileIdentity.hpp"
#include "GroupId.hpp"
#include "GroupName.hpp"
#include "OperatingSystem.hpp"
#include "PlatformError.hpp"
#include "PlatformErrorCategory.hpp"
#include "PlatformErrorContext.hpp"
#include "ProcessId.hpp"
#include "ProcessInfo.hpp"
#include "Subprocess.hpp"
#include "SubprocessExitStatus.hpp"
#include "SubprocessOptions.hpp"
#include "SubprocessOutputMode.hpp"
#include "SystemInfo.hpp"
#include "UserId.hpp"
#include "UserLookup.hpp"
#include "UserName.hpp"


