#pragma once
// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.
#include "../../src/erbsland/text/StdFormat.hpp"
#include "../../src/erbsland/time/StdFormat.hpp"
#include "../../src/erbsland/unit/StdFormat.hpp"
