// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "U16Format.hpp"
#include "U16String.hpp"
#include "U16StringCIHashMap.hpp"
#include "U16StringCIHashSet.hpp"
#include "U16StringCIMap.hpp"
#include "U16StringCISet.hpp"
#include "U16StringCharView.hpp"
#include "U16StringConstIterator.hpp"
#include "U16StringHashMap.hpp"
#include "U16StringHashSet.hpp"
#include "U16StringList.hpp"
#include "U16StringLiteral.hpp"
#include "U16StringMap.hpp"
#include "U16StringSet.hpp"
#include "U16StringView.hpp"
#include "U16StringViewList.hpp"


