// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.
#include "Database.hpp"

namespace erbsland::time::tz::impl {

auto Database::version() noexcept -> unit::Version {
    return unit::Version{1, 2026, 2};
}

}
