// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.
#include "RegionEtcetera.hpp"

#include "Rules.hpp"

namespace erbsland::time::tz::impl {

auto infoEtc_GMT() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{0, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0135U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMTPlus1() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-3600, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0028U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMTPlus10() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-36000, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0038U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMTPlus11() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-39600, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x003bU},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMTPlus12() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-43200, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x003eU},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMTPlus2() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-7200, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x002aU},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMTPlus3() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-10800, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x002cU},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMTPlus4() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-14400, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x002fU},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMTPlus5() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-18000, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0031U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMTPlus6() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-21600, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0032U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMTPlus7() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-25200, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0033U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMTPlus8() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-28800, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0034U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMTPlus9() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-32400, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0036U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMT_1() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{3600, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0003U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMT_10() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{36000, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x001aU},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMT_11() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{39600, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x001cU},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMT_12() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{43200, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x001fU},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMT_13() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{46800, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0024U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMT_14() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{50400, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0026U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMT_2() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{7200, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0005U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMT_3() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{10800, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0008U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMT_4() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{14400, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x000aU},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMT_5() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{18000, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x000cU},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMT_6() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{21600, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x000fU},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMT_7() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{25200, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0011U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMT_8() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{28800, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0014U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_GMT_9() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{32400, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0017U},
        std::vector<AbbreviationOffset>{});
}

auto infoEtc_UTC() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{0, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x02d1U},
        std::vector<AbbreviationOffset>{});
}

}
