// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.

#include "Info.hpp"

#include <memory>

namespace erbsland::time::tz::impl {

[[nodiscard]] auto infoAntarctica_Macquarie() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAustralia_Adelaide() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAustralia_Brisbane() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAustralia_BrokenHill() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAustralia_Darwin() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAustralia_Eucla() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAustralia_Hobart() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAustralia_Lindeman() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAustralia_LordHowe() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAustralia_Melbourne() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAustralia_Perth() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAustralia_Sydney() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Apia() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Auckland() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Bougainville() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Chatham() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Efate() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Fakaofo() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Fiji() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Gambier() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Guadalcanal() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Guam() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Kanton() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Kiritimati() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Kosrae() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Kwajalein() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Marquesas() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Nauru() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Niue() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Norfolk() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Noumea() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_PagoPago() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Palau() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Pitcairn() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_PortMoresby() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Rarotonga() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Tahiti() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Tarawa() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Tongatapu() noexcept -> std::unique_ptr<Info>;

}
