// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.
#include "RegionAntarctica.hpp"

#include "Rules.hpp"

namespace erbsland::time::tz::impl {

auto infoAntarctica_Casey() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{0, 0x0e77934880ULL, 0, 0, 0x00U},
            ContinuationLine{28800, 0x0ec44e8220ULL, 28800, 0, 0x01U},
            ContinuationLine{39600, 0x0ec50446f0ULL, 39600, 0, 0x02U},
            ContinuationLine{28800, 0x0ec81e1820ULL, 28800, 0, 0x01U},
            ContinuationLine{39600, 0x0ec8b84990ULL, 39600, 0, 0x02U},
            ContinuationLine{28800, 0x0ed17eb780ULL, 28800, 0, 0x01U},
            ContinuationLine{39600, 0x0ed4188b10ULL, 39600, 0, 0x02U},
            ContinuationLine{28800, 0x0ed52d9040ULL, 28800, 0, 0x01U},
            ContinuationLine{39600, 0x0ed6019980ULL, 39600, 0, 0x02U},
            ContinuationLine{28800, 0x0ed70ac130ULL, 28800, 0, 0x01U},
            ContinuationLine{39600, 0x0ed7d84100ULL, 39600, 0, 0x02U},
            ContinuationLine{28800, 0x0ed8ed1c3cULL, 28800, 0, 0x01U},
            ContinuationLine{39600, 0x0ed9c13350ULL, 39600, 0, 0x02U},
            ContinuationLine{28800, 0x0edaccfe3cULL, 28800, 0, 0x01U},
            ContinuationLine{39600, 0x0edba11550ULL, 39600, 0, 0x02U},
            ContinuationLine{28800, 0x0edcace03cULL, 28800, 0, 0x01U},
            ContinuationLine{39600, 0x0edd7d2d00ULL, 39600, 0, 0x02U},
            ContinuationLine{28800, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0014U, 0x001cU},
        std::vector<AbbreviationOffset>{});
}

auto infoAntarctica_Davis() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{0, 0x0e6110bc00ULL, 0, 0, 0x00U},
            ContinuationLine{25200, 0x0e6fbc5b10ULL, 25200, 0, 0x02U},
            ContinuationLine{0, 0x0e77bc2700ULL, 0, 0, 0x00U},
            ContinuationLine{25200, 0x0ec44e9030ULL, 25200, 0, 0x02U},
            ContinuationLine{18000, 0x0ec50c7640ULL, 18000, 0, 0x01U},
            ContinuationLine{25200, 0x0ec81e2630ULL, 25200, 0, 0x02U},
            ContinuationLine{18000, 0x0ec8b873c0ULL, 18000, 0, 0x01U},
            ContinuationLine{25200, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x000cU, 0x0011U},
        std::vector<AbbreviationOffset>{});
}

auto infoAntarctica_Mawson() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{0, 0x0e5b94ae80ULL, 0, 0, 0x00U},
            ContinuationLine{21600, 0x0ec44e9e40ULL, 21600, 0, 0x02U},
            ContinuationLine{18000, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x000cU, 0x000fU},
        std::vector<AbbreviationOffset>{});
}

auto infoAntarctica_Rothera() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{0, 0x0e8676a900ULL, 0, 0, 0x00U},
            ContinuationLine{-10800, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x002cU},
        std::vector<AbbreviationOffset>{});
}

auto infoAntarctica_Troll() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(121U) /* Troll */},
        std::vector<ContinuationLine>{
            ContinuationLine{0, 0x0ebb81c300ULL, 0, 0, 0x00U},
            ContinuationLine{0, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{},
        std::vector<AbbreviationOffset>{0x00U, 0x00U});
}

auto infoAntarctica_Vostok() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{0, 0x0e62cd0580ULL, 0, 0, 0x00U},
            ContinuationLine{25200, 0x0ea6c1b510ULL, 25200, 0, 0x02U},
            ContinuationLine{0, 0x0ea82a0100ULL, 0, 0, 0x00U},
            ContinuationLine{25200, 0x0edef3c130ULL, 25200, 0, 0x02U},
            ContinuationLine{18000, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x000cU, 0x0011U},
        std::vector<AbbreviationOffset>{});
}

}
