// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.

#include "Info.hpp"

#include <memory>

namespace erbsland::time::tz::impl {

[[nodiscard]] auto infoAfrica_Abidjan() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_Algiers() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_Bissau() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_Cairo() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_Casablanca() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_ElAaiun() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_Johannesburg() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_Juba() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_Khartoum() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_Lagos() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_Maputo() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_Monrovia() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_Nairobi() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_Ndjamena() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_SaoTome() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_Tripoli() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_Tunis() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAfrica_Windhoek() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAtlantic_CapeVerde() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoIndian_Mauritius() noexcept -> std::unique_ptr<Info>;

}
