// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.

#include "Info.hpp"

#include <memory>

namespace erbsland::time::tz::impl {

[[nodiscard]] auto infoEtc_GMT() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMTPlus1() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMTPlus10() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMTPlus11() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMTPlus12() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMTPlus2() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMTPlus3() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMTPlus4() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMTPlus5() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMTPlus6() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMTPlus7() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMTPlus8() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMTPlus9() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMT_1() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMT_10() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMT_11() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMT_12() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMT_13() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMT_14() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMT_2() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMT_3() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMT_4() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMT_5() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMT_6() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMT_7() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMT_8() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_GMT_9() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoEtc_UTC() noexcept -> std::unique_ptr<Info>;

}
