// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.

#include "Info.hpp"

#include <memory>

namespace erbsland::time::tz::impl {

[[nodiscard]] auto infoAmerica_Adak() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Anchorage() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_BahiaBanderas() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Barbados() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Belize() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Boise() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_CambridgeBay() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Cancun() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Chicago() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Chihuahua() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_CiudadJuarez() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_CostaRica() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Dawson() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_DawsonCreek() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Denver() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Detroit() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Edmonton() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_ElSalvador() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_FortNelson() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_GlaceBay() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_GooseBay() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_GrandTurk() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Guatemala() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Halifax() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Havana() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Hermosillo() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Indiana_Indianapolis() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Indiana_Knox() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Indiana_Marengo() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Indiana_Petersburg() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Indiana_TellCity() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Indiana_Vevay() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Indiana_Vincennes() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Indiana_Winamac() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Inuvik() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Iqaluit() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Jamaica() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Juneau() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Kentucky_Louisville() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Kentucky_Monticello() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_LosAngeles() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Managua() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Martinique() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Matamoros() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Mazatlan() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Menominee() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Merida() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Metlakatla() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_MexicoCity() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Miquelon() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Moncton() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Monterrey() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_NewYork() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Nome() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_NorthDakota_Beulah() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_NorthDakota_Center() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_NorthDakota_NewSalem() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Ojinaga() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Panama() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Phoenix() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Port_au_Prince() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_PuertoRico() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_RankinInlet() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Regina() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Resolute() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_SantoDomingo() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Sitka() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_StJohns() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_SwiftCurrent() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Tegucigalpa() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Tijuana() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Toronto() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Vancouver() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Whitehorse() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Winnipeg() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Yakutat() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAtlantic_Bermuda() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Honolulu() noexcept -> std::unique_ptr<Info>;

}
