// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.
#include "RegionAustralasia.hpp"

#include "Rules.hpp"

namespace erbsland::time::tz::impl {

auto infoAntarctica_Macquarie() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(3U) /* AT */, ruleSet(10U) /* Aus */},
        std::vector<ContinuationLine>{
            ContinuationLine{0, 0x0df5799200ULL, 0, 0, 0x00U},
            ContinuationLine{36000, 0x0e1549f480ULL, 36000, 0, 0x02U},
            ContinuationLine{36000, 0x0e15ebf2d0ULL, 39600, 3600, 0x01U},
            ContinuationLine{36000, 0x0e19fc3060ULL, 39600, 65553, 0x00U},
            ContinuationLine{0, 0x0e5080e400ULL, 0, 0, 0x00U},
            ContinuationLine{36000, 0x0e73cef550ULL, 39600, 65553, 0x00U},
            ContinuationLine{36000, 0x0ec4b12a60ULL, 36000, 65552, 0x00U},
            ContinuationLine{36000, 0x0ec6924fd0ULL, 39600, 3600, 0x01U},
            ContinuationLine{36000, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0044U, 0x0045U},
        std::vector<AbbreviationOffset>{
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x02U});
}

auto infoAustralia_Adelaide() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(2U) /* AS */, ruleSet(10U) /* Aus */},
        std::vector<ContinuationLine>{
            ContinuationLine{33260, 0x0dec8b0714ULL, 33260, 0, 0x03U},
            ContinuationLine{32400, 0x0df4867f70ULL, 32400, 0, 0x02U},
            ContinuationLine{34200, 0x0e7b551bd8ULL, 37800, 65553, 0x00U},
            ContinuationLine{34200, 0x0000000000ULL, 0, 65648, 0x00U},
        },
        std::vector<TextId>{0x003fU, 0x0040U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x01U});
}

auto infoAustralia_Brisbane() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(1U) /* AQ */, ruleSet(10U) /* Aus */},
        std::vector<ContinuationLine>{
            ContinuationLine{36728, 0x0dec621b08ULL, 36728, 0, 0x03U},
            ContinuationLine{36000, 0x0e7b5514d0ULL, 39600, 65553, 0x00U},
            ContinuationLine{36000, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0044U, 0x0045U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U});
}

auto infoAustralia_BrokenHill() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(0U) /* AN */, ruleSet(2U) /* AS */, ruleSet(10U) /* Aus */},
        std::vector<ContinuationLine>{
            ContinuationLine{33948, 0x0dec8b0464ULL, 33948, 0, 0x04U},
            ContinuationLine{36000, 0x0def7921e0ULL, 36000, 0, 0x03U},
            ContinuationLine{32400, 0x0df4867f70ULL, 32400, 0, 0x02U},
            ContinuationLine{34200, 0x0e7b551bd8ULL, 37800, 65554, 0x00U},
            ContinuationLine{34200, 0x0eb1e139e8ULL, 34200, 65648, 0x00U},
            ContinuationLine{34200, 0x0000000000ULL, 0, 65889, 0x00U},
        },
        std::vector<TextId>{0x003fU, 0x0040U, 0x0045U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x01U});
}

auto infoAustralia_Darwin() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(10U) /* Aus */},
        std::vector<ContinuationLine>{
            ContinuationLine{31400, 0x0dec8b0e58ULL, 31400, 0, 0x03U},
            ContinuationLine{32400, 0x0df4867f70ULL, 32400, 0, 0x02U},
            ContinuationLine{34200, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x003fU, 0x0040U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U});
}

auto infoAustralia_Eucla() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(5U) /* AW */, ruleSet(10U) /* Aus */},
        std::vector<ContinuationLine>{
            ContinuationLine{30928, 0x0dee1a86b0ULL, 30928, 0, 0x03U},
            ContinuationLine{31500, 0x0e4798e964ULL, 35100, 65553, 0x00U},
            ContinuationLine{31500, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0016U, 0x0019U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U});
}

auto infoAustralia_Hobart() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(3U) /* AT */, ruleSet(10U) /* Aus */},
        std::vector<ContinuationLine>{
            ContinuationLine{35356, 0x0deda27ce4ULL, 35356, 0, 0x03U},
            ContinuationLine{36000, 0x0e1b0bc560ULL, 36000, 65552, 0x00U},
            ContinuationLine{36000, 0x0e73cef550ULL, 39600, 65553, 0x00U},
            ContinuationLine{36000, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0044U, 0x0045U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x02U});
}

auto infoAustralia_Lindeman() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(1U) /* AQ */, ruleSet(10U) /* Aus */, ruleSet(56U) /* Holiday */},
        std::vector<ContinuationLine>{
            ContinuationLine{35756, 0x0dec621ed4ULL, 35756, 0, 0x03U},
            ContinuationLine{36000, 0x0e7b5514d0ULL, 39600, 65553, 0x00U},
            ContinuationLine{36000, 0x0ea3c4e4e0ULL, 36000, 65552, 0x00U},
            ContinuationLine{36000, 0x0000000000ULL, 0, 65554, 0x00U},
        },
        std::vector<TextId>{0x0044U, 0x0045U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U});
}

auto infoAustralia_LordHowe() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(66U) /* LH */},
        std::vector<ContinuationLine>{
            ContinuationLine{38180, 0x0dec8af3dcULL, 38180, 0, 0x05U},
            ContinuationLine{36000, 0x0e8e72e2e0ULL, 36000, 0, 0x04U},
            ContinuationLine{37800, 0x0e9699d258ULL, 37800, 65552, 0x00U},
            ContinuationLine{37800, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x001bU, 0x001cU, 0x001eU, 0x0045U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x03U, 0x01U, 0x02U, 0x01U, 0x02U, 0x02U, 0x01U, 0x01U, 0x02U, 0x02U, 0x01U, 0x01U, 0x01U, 0x02U});
}

auto infoAustralia_Melbourne() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(4U) /* AV */, ruleSet(10U) /* Aus */},
        std::vector<ContinuationLine>{
            ContinuationLine{34792, 0x0dec8b0118ULL, 34792, 0, 0x03U},
            ContinuationLine{36000, 0x0e7b5514d0ULL, 39600, 65553, 0x00U},
            ContinuationLine{36000, 0x0000000000ULL, 0, 65648, 0x00U},
        },
        std::vector<TextId>{0x0044U, 0x0045U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x01U});
}

auto infoAustralia_Perth() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(5U) /* AW */, ruleSet(10U) /* Aus */},
        std::vector<ContinuationLine>{
            ContinuationLine{27804, 0x0dee1a92e4ULL, 27804, 0, 0x03U},
            ContinuationLine{28800, 0x0e4798f3f0ULL, 32400, 65553, 0x00U},
            ContinuationLine{28800, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0053U, 0x0054U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U});
}

auto infoAustralia_Sydney() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(0U) /* AN */, ruleSet(10U) /* Aus */},
        std::vector<ContinuationLine>{
            ContinuationLine{36292, 0x0dec8afb3cULL, 36292, 0, 0x03U},
            ContinuationLine{36000, 0x0e7b5514d0ULL, 39600, 65553, 0x00U},
            ContinuationLine{36000, 0x0000000000ULL, 0, 65648, 0x00U},
        },
        std::vector<TextId>{0x0044U, 0x0045U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x01U});
}

auto infoPacific_Apia() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(130U) /* WS */},
        std::vector<ContinuationLine>{
            ContinuationLine{45184, 0x0de7b24500ULL, 45184, 0, 0x06U},
            ContinuationLine{-41216, 0x0e0a7a7800ULL, -41216, 0, 0x06U},
            ContinuationLine{-41400, 0x0e53d68038ULL, -41400, 0, 0x05U},
            ContinuationLine{-39600, 0x0ec87207a0ULL, -36000, 65552, 0x00U},
            ContinuationLine{46800, 0x0000000000ULL, 0, 65632, 0x00U},
        },
        std::vector<TextId>{0x0024U, 0x0026U, 0x0038U, 0x003bU, 0x003dU, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x04U, 0x03U, 0x04U, 0x03U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U});
}

auto infoPacific_Auckland() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(85U) /* NZ */},
        std::vector<ContinuationLine>{
            ContinuationLine{41944, 0x0dbb2bc8a8ULL, 41944, 0, 0x01U},
            ContinuationLine{41400, 0x0e4c4f1d48ULL, 41400, 65552, 0x00U},
            ContinuationLine{43200, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x01c0U, 0x021eU, 0x021fU, 0x0220U},
        std::vector<AbbreviationOffset>{
            0x04U,
            0x03U,
            0x04U,
            0x03U,
            0x03U,
            0x04U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x02U,
            0x04U,
            0x02U,
            0x04U});
}

auto infoPacific_Bougainville() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{37336, 0x0dd02ace28ULL, 37336, 0, 0x04U},
            ContinuationLine{35312, 0x0dec622090ULL, 35312, 0, 0x05U},
            ContinuationLine{36000, 0x0e45b7b260ULL, 36000, 0, 0x02U},
            ContinuationLine{32400, 0x0e4b9fe8f0ULL, 32400, 0, 0x01U},
            ContinuationLine{36000, 0x0ece135380ULL, 36000, 0, 0x02U},
            ContinuationLine{39600, 0x0000000000ULL, 0, 0, 0x03U},
        },
        std::vector<TextId>{0x0017U, 0x001aU, 0x001cU, 0x01c0U, 0x0240U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Chatham() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(24U) /* Chatham */},
        std::vector<ContinuationLine>{
            ContinuationLine{44028, 0x0dbb2bc084ULL, 44028, 0, 0x04U},
            ContinuationLine{44100, 0x0e4c4f12bcULL, 44100, 0, 0x01U},
            ContinuationLine{45900, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0020U, 0x0023U, 0x0025U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x03U, 0x02U, 0x03U, 0x03U, 0x02U, 0x03U, 0x02U});
}

auto infoPacific_Efate() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(127U) /* Vanuatu */},
        std::vector<ContinuationLine>{
            ContinuationLine{40396, 0x0e0c6a3eb4ULL, 40396, 0, 0x03U},
            ContinuationLine{39600, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x001cU, 0x001fU, 0x01c0U},
        std::vector<AbbreviationOffset>{0x02U, 0x01U, 0x02U, 0x01U, 0x01U, 0x02U});
}

auto infoPacific_Fakaofo() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-41096, 0x0df7abd188ULL, -41096, 0, 0x03U},
            ContinuationLine{-39600, 0x0ec87215b0ULL, -39600, 0, 0x02U},
            ContinuationLine{46800, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0024U, 0x003bU, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Fiji() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(45U) /* Fiji */},
        std::vector<ContinuationLine>{
            ContinuationLine{42944, 0x0e13882dc0ULL, 42944, 0, 0x03U},
            ContinuationLine{43200, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x001fU, 0x0024U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x01U, 0x01U, 0x02U, 0x01U, 0x02U, 0x02U});
}

auto infoPacific_Gambier() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-32388, 0x0e0dc4c404ULL, -32388, 0, 0x02U},
            ContinuationLine{-32400, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0036U, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Guadalcanal() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{38388, 0x0e0dc3af8cULL, 38388, 0, 0x02U},
            ContinuationLine{39600, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x001cU, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Guam() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(51U) /* Guam */},
        std::vector<ContinuationLine>{
            ContinuationLine{-51660, 0x0d8e5641ccULL, -51660, 0, 0x05U},
            ContinuationLine{34740, 0x0df7aaa94cULL, 34740, 0, 0x05U},
            ContinuationLine{36000, 0x0e44ac11e0ULL, 36000, 0, 0x04U},
            ContinuationLine{32400, 0x0e49a305f0ULL, 32400, 0, 0x01U},
            ContinuationLine{36000, 0x0eb3b7cc50ULL, 39600, 65552, 0x00U},
            ContinuationLine{36000, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x0017U, 0x00d1U, 0x0134U, 0x0155U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x03U, 0x04U, 0x03U, 0x04U, 0x03U, 0x04U, 0x03U, 0x04U, 0x03U, 0x04U, 0x03U, 0x04U, 0x03U, 0x04U});
}

auto infoPacific_Kanton() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{0, 0x0e3ca15780ULL, 0, 0, 0x00U},
            ContinuationLine{-43200, 0x0e8bca80c0ULL, -43200, 0, 0x03U},
            ContinuationLine{-39600, 0x0ea879b5b0ULL, -39600, 0, 0x02U},
            ContinuationLine{46800, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0024U, 0x003bU, 0x003eU},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Kiritimati() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-37760, 0x0df7abc480ULL, -37760, 0, 0x04U},
            ContinuationLine{-38400, 0x0e8bca6e00ULL, -38400, 0, 0x03U},
            ContinuationLine{-36000, 0x0ea879a7a0ULL, -36000, 0, 0x02U},
            ContinuationLine{50400, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0026U, 0x0038U, 0x003aU, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Kosrae() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-47284, 0x0d8e5630b4ULL, -47284, 0, 0x05U},
            ContinuationLine{39116, 0x0df7aa9834ULL, 39116, 0, 0x05U},
            ContinuationLine{39600, 0x0e118611d0ULL, 39600, 0, 0x03U},
            ContinuationLine{32400, 0x0e19ae75f0ULL, 32400, 0, 0x01U},
            ContinuationLine{39600, 0x0e3b61b1d0ULL, 39600, 0, 0x03U},
            ContinuationLine{36000, 0x0e435e8660ULL, 36000, 0, 0x02U},
            ContinuationLine{32400, 0x0e4b858af0ULL, 32400, 0, 0x01U},
            ContinuationLine{39600, 0x0e78fa9750ULL, 39600, 0, 0x03U},
            ContinuationLine{43200, 0x0eafffe340ULL, 43200, 0, 0x04U},
            ContinuationLine{39600, 0x0000000000ULL, 0, 0, 0x03U},
        },
        std::vector<TextId>{0x0017U, 0x001aU, 0x001cU, 0x001fU, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Kwajalein() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{40160, 0x0df7aa9420ULL, 40160, 0, 0x06U},
            ContinuationLine{39600, 0x0e3b61b1d0ULL, 39600, 0, 0x03U},
            ContinuationLine{36000, 0x0e435e8660ULL, 36000, 0, 0x02U},
            ContinuationLine{32400, 0x0e48bafdf0ULL, 32400, 0, 0x01U},
            ContinuationLine{39600, 0x0e78fa9750ULL, 39600, 0, 0x03U},
            ContinuationLine{-43200, 0x0ea5ea8a40ULL, -43200, 0, 0x05U},
            ContinuationLine{43200, 0x0000000000ULL, 0, 0, 0x04U},
        },
        std::vector<TextId>{0x0017U, 0x001aU, 0x001cU, 0x001fU, 0x003eU, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Marquesas() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-33480, 0x0e0dc4c848ULL, -33480, 0, 0x02U},
            ContinuationLine{-34200, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0037U, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Nauru() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{40060, 0x0e1d5ba704ULL, 40060, 0, 0x04U},
            ContinuationLine{41400, 0x0e460565c8ULL, 41400, 0, 0x02U},
            ContinuationLine{32400, 0x0e4bb7a3f0ULL, 32400, 0, 0x01U},
            ContinuationLine{41400, 0x0e8a9624e8ULL, 41400, 0, 0x02U},
            ContinuationLine{43200, 0x0000000000ULL, 0, 0, 0x03U},
        },
        std::vector<TextId>{0x0017U, 0x001eU, 0x001fU, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Niue() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-40780, 0x0e5915e64cULL, -40780, 0, 0x03U},
            ContinuationLine{-40800, 0x0e6f1b3460ULL, -40800, 0, 0x02U},
            ContinuationLine{-39600, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x003bU, 0x003cU, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Norfolk() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(0U) /* AN */},
        std::vector<ContinuationLine>{
            ContinuationLine{40312, 0x0df7aa9388ULL, 40312, 0, 0x06U},
            ContinuationLine{40320, 0x0e55b67480ULL, 40320, 0, 0x02U},
            ContinuationLine{41400, 0x0e82844668ULL, 41400, 0, 0x03U},
            ContinuationLine{41400, 0x0e832a6368ULL, 45000, 3600, 0x05U},
            ContinuationLine{41400, 0x0ecf846268ULL, 41400, 0, 0x03U},
            ContinuationLine{39600, 0x0ed68d2e50ULL, 39600, 0, 0x01U},
            ContinuationLine{39600, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x001cU, 0x001dU, 0x001eU, 0x001fU, 0x0022U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x04U,
            0x01U,
            0x01U,
            0x01U,
            0x01U,
            0x01U,
            0x04U,
            0x04U,
            0x01U,
            0x01U,
            0x04U,
            0x04U,
            0x01U,
            0x01U,
            0x01U,
            0x04U});
}

auto infoPacific_Noumea() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(82U) /* NC */},
        std::vector<ContinuationLine>{
            ContinuationLine{39948, 0x0e0c6a4074ULL, 39948, 0, 0x03U},
            ContinuationLine{39600, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x001cU, 0x001fU, 0x01c0U},
        std::vector<AbbreviationOffset>{0x02U, 0x01U, 0x02U, 0x01U});
}

auto infoPacific_PagoPago() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{45432, 0x0de7b24408ULL, 45432, 0, 0x01U},
            ContinuationLine{-40968, 0x0e0a7a7708ULL, -40968, 0, 0x01U},
            ContinuationLine{-39600, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x01c0U, 0x0282U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Palau() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-54124, 0x0d8e564b6cULL, -54124, 0, 0x02U},
            ContinuationLine{32276, 0x0df7aab2ecULL, 32276, 0, 0x02U},
            ContinuationLine{32400, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0017U, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Pitcairn() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-31220, 0x0df7abaaf4ULL, -31220, 0, 0x03U},
            ContinuationLine{-30600, 0x0eaeb8be08ULL, -30600, 0, 0x02U},
            ContinuationLine{-28800, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0034U, 0x0035U, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_PortMoresby() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{35320, 0x0dd02ad608ULL, 35320, 0, 0x02U},
            ContinuationLine{35312, 0x0dec622090ULL, 35312, 0, 0x03U},
            ContinuationLine{36000, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x001aU, 0x01c0U, 0x0240U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Rarotonga() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(27U) /* Cook */},
        std::vector<ContinuationLine>{
            ContinuationLine{48056, 0x0df5c158c8ULL, 48056, 0, 0x04U},
            ContinuationLine{-38344, 0x0e5915dcc8ULL, -38344, 0, 0x04U},
            ContinuationLine{-37800, 0x0e8a209728ULL, -37800, 0, 0x03U},
            ContinuationLine{-36000, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0037U, 0x0038U, 0x0039U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x01U, 0x02U, 0x01U});
}

auto infoPacific_Tahiti() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{-35896, 0x0e0dc4d1b8ULL, -35896, 0, 0x02U},
            ContinuationLine{-36000, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0038U, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Tarawa() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{41524, 0x0df7aa8eccULL, 41524, 0, 0x02U},
            ContinuationLine{43200, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x001fU, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoPacific_Tongatapu() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(119U) /* Tonga */},
        std::vector<ContinuationLine>{
            ContinuationLine{44352, 0x0e4bba1840ULL, 44352, 0, 0x04U},
            ContinuationLine{44400, 0x0e68865c10ULL, 44400, 0, 0x01U},
            ContinuationLine{46800, 0x0eafffd530ULL, 46800, 0, 0x02U},
            ContinuationLine{46800, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0021U, 0x0024U, 0x0026U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x03U, 0x02U, 0x03U, 0x02U});
}

}
