// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.

#include "Info.hpp"

#include <memory>

namespace erbsland::time::tz::impl {

[[nodiscard]] auto infoAmerica_Araguaina() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Argentina_BuenosAires() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Argentina_Catamarca() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Argentina_Cordoba() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Argentina_Jujuy() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Argentina_LaRioja() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Argentina_Mendoza() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Argentina_RioGallegos() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Argentina_Salta() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Argentina_SanJuan() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Argentina_SanLuis() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Argentina_Tucuman() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Argentina_Ushuaia() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Asuncion() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Bahia() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Belem() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_BoaVista() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Bogota() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_CampoGrande() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Caracas() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Cayenne() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Coyhaique() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Cuiaba() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Eirunepe() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Fortaleza() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Guayaquil() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Guyana() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_LaPaz() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Lima() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Maceio() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Manaus() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Montevideo() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Noronha() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Paramaribo() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_PortoVelho() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_PuntaArenas() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Recife() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_RioBranco() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Santarem() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_Santiago() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAmerica_SaoPaulo() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAntarctica_Palmer() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAtlantic_SouthGeorgia() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAtlantic_Stanley() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Easter() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoPacific_Galapagos() noexcept -> std::unique_ptr<Info>;

}
