// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.
#include "RegionAsia.hpp"

#include "Rules.hpp"

namespace erbsland::time::tz::impl {

auto infoAsia_Almaty() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(103U) /* RussiaAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{18468, 0x0e238df7dcULL, 18468, 0, 0x04U},
            ContinuationLine{18000, 0x0e2f186b30ULL, 18000, 0, 0x01U},
            ContinuationLine{21600, 0x0ea1696a40ULL, 25200, 65552, 0x00U},
            ContinuationLine{18000, 0x0ea2ed1150ULL, 21600, 65616, 0x00U},
            ContinuationLine{21600, 0x0ebaf86ec0ULL, 25200, 65552, 0x00U},
            ContinuationLine{21600, 0x0edf554220ULL, 21600, 0, 0x02U},
            ContinuationLine{18000, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x000cU, 0x000fU, 0x0011U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x02U, 0x03U, 0x02U, 0x01U, 0x01U, 0x02U, 0x01U});
}

auto infoAsia_Amman() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(64U) /* Jordan */},
        std::vector<ContinuationLine>{
            ContinuationLine{8624, 0x0e301852d0ULL, 8624, 0, 0x04U},
            ContinuationLine{7200, 0x0edccf7b60ULL, 10800, 65552, 0x00U},
            ContinuationLine{10800, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0008U, 0x010dU, 0x010eU, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x02U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x02U,
            0x03U,
            0x03U,
            0x03U,
            0x03U,
            0x03U,
            0x02U,
            0x03U,
            0x02U});
}

auto infoAsia_Aqtau() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(103U) /* RussiaAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{12064, 0x0e238e10e0ULL, 12064, 0, 0x04U},
            ContinuationLine{14400, 0x0e2f187940ULL, 14400, 0, 0x01U},
            ContinuationLine{18000, 0x0e8f8d4a30ULL, 18000, 0, 0x02U},
            ContinuationLine{21600, 0x0e907d2d20ULL, 21600, 0, 0x03U},
            ContinuationLine{18000, 0x0ea1697850ULL, 21600, 65552, 0x00U},
            ContinuationLine{14400, 0x0ea2ed1f60ULL, 18000, 65616, 0x00U},
            ContinuationLine{18000, 0x0ea7f90f50ULL, 21600, 65552, 0x00U},
            ContinuationLine{14400, 0x0ebaf88ae0ULL, 18000, 65616, 0x00U},
            ContinuationLine{18000, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x000aU, 0x000cU, 0x000fU, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x02U, 0x03U, 0x02U, 0x01U, 0x01U, 0x02U, 0x01U});
}

auto infoAsia_Aqtobe() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(103U) /* RussiaAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{13720, 0x0e238e0a68ULL, 13720, 0, 0x04U},
            ContinuationLine{14400, 0x0e2f187940ULL, 14400, 0, 0x01U},
            ContinuationLine{18000, 0x0e8e9c07b0ULL, 18000, 0, 0x02U},
            ContinuationLine{18000, 0x0e8f8d3c20ULL, 21600, 3600, 0x03U},
            ContinuationLine{21600, 0x0e907d2d20ULL, 21600, 0, 0x03U},
            ContinuationLine{18000, 0x0ea1697850ULL, 21600, 65552, 0x00U},
            ContinuationLine{14400, 0x0ea2ed1f60ULL, 18000, 65616, 0x00U},
            ContinuationLine{18000, 0x0ebaf87cd0ULL, 21600, 65552, 0x00U},
            ContinuationLine{18000, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x000aU, 0x000cU, 0x000fU, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x02U, 0x03U, 0x02U, 0x01U, 0x01U, 0x02U, 0x01U});
}

auto infoAsia_Ashgabat() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(103U) /* RussiaAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{14012, 0x0e238e0944ULL, 14012, 0, 0x04U},
            ContinuationLine{14400, 0x0e2f187940ULL, 14400, 0, 0x01U},
            ContinuationLine{18000, 0x0ea1696a40ULL, 21600, 65552, 0x00U},
            ContinuationLine{14400, 0x0ea2ed1150ULL, 18000, 65616, 0x00U},
            ContinuationLine{18000, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x000aU, 0x000cU, 0x000fU, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x02U, 0x03U, 0x02U, 0x01U, 0x01U, 0x02U, 0x01U});
}

auto infoAsia_Atyrau() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(103U) /* RussiaAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{12464, 0x0e238e0f50ULL, 12464, 0, 0x05U},
            ContinuationLine{10800, 0x0e2f188750ULL, 10800, 0, 0x01U},
            ContinuationLine{18000, 0x0e8f8d4a30ULL, 18000, 0, 0x03U},
            ContinuationLine{21600, 0x0e907d2d20ULL, 21600, 0, 0x04U},
            ContinuationLine{18000, 0x0ea1697850ULL, 21600, 65552, 0x00U},
            ContinuationLine{14400, 0x0ea2ed1f60ULL, 18000, 65616, 0x00U},
            ContinuationLine{18000, 0x0eb071c2d0ULL, 21600, 65552, 0x00U},
            ContinuationLine{14400, 0x0ebaf88ae0ULL, 18000, 65616, 0x00U},
            ContinuationLine{18000, 0x0000000000ULL, 0, 0, 0x03U},
        },
        std::vector<TextId>{0x0008U, 0x000aU, 0x000cU, 0x000fU, 0x01c0U},
        std::vector<AbbreviationOffset>{0x04U, 0x03U, 0x03U, 0x04U, 0x03U, 0x02U, 0x02U, 0x03U, 0x02U});
}

auto infoAsia_Baghdad() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(61U) /* Iraq */},
        std::vector<ContinuationLine>{
            ContinuationLine{10660, 0x0de2fb2ddcULL, 10660, 0, 0x04U},
            ContinuationLine{10656, 0x0e17a4b8e0ULL, 10656, 0, 0x03U},
            ContinuationLine{10800, 0x0e90a4e450ULL, 10800, 0, 0x01U},
            ContinuationLine{10800, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0008U, 0x000aU, 0x0085U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x02U, 0x01U, 0x02U, 0x02U, 0x01U, 0x02U, 0x02U, 0x01U});
}

auto infoAsia_Baku() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(12U) /* Azer */, ruleSet(38U) /* EUAsia */, ruleSet(103U) /* RussiaAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{11964, 0x0e238e1144ULL, 11964, 0, 0x04U},
            ContinuationLine{10800, 0x0e614e8850ULL, 10800, 0, 0x01U},
            ContinuationLine{14400, 0x0ea1698660ULL, 18000, 65554, 0x00U},
            ContinuationLine{10800, 0x0ea4396770ULL, 14400, 65618, 0x00U},
            ContinuationLine{14400, 0x0eaa5b67c0ULL, 14400, 0, 0x02U},
            ContinuationLine{14400, 0x0eac3ddeb0ULL, 18000, 65553, 0x00U},
            ContinuationLine{14400, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0008U, 0x000aU, 0x000cU, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x02U, 0x03U, 0x02U, 0x01U, 0x01U, 0x02U, 0x01U});
}

auto infoAsia_Bangkok() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{24124, 0x0dd02b01c4ULL, 24124, 0, 0x03U},
            ContinuationLine{24124, 0x0e1bdee3c4ULL, 24124, 0, 0x02U},
            ContinuationLine{25200, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0011U, 0x0085U, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Beirut() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(68U) /* Lebanon */},
        std::vector<ContinuationLine>{
            ContinuationLine{8520, 0x0dd02b3eb8ULL, 8520, 0, 0x03U},
            ContinuationLine{7200, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x010dU, 0x010eU, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U});
}

auto infoAsia_Bishkek() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(65U) /* Kyrgyz */, ruleSet(103U) /* RussiaAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{17904, 0x0e238dfa10ULL, 17904, 0, 0x04U},
            ContinuationLine{18000, 0x0e2f186b30ULL, 18000, 0, 0x01U},
            ContinuationLine{21600, 0x0ea1696a40ULL, 25200, 65553, 0x00U},
            ContinuationLine{18000, 0x0ea2331fc0ULL, 21600, 65617, 0x00U},
            ContinuationLine{18000, 0x0ebc700e20ULL, 21600, 65664, 0x00U},
            ContinuationLine{21600, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x000cU, 0x000fU, 0x0011U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x02U, 0x03U, 0x02U, 0x01U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U});
}

auto infoAsia_Colombo() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{19164, 0x0dd02b1524ULL, 19164, 0, 0x04U},
            ContinuationLine{19172, 0x0e0112391cULL, 19172, 0, 0x05U},
            ContinuationLine{19800, 0x0e44ce9828ULL, 19800, 0, 0x01U},
            ContinuationLine{19800, 0x0e4609a7a0ULL, 21600, 1800, 0x02U},
            ContinuationLine{19800, 0x0e4be9fc38ULL, 23400, 3600, 0x03U},
            ContinuationLine{19800, 0x0eab1a7c28ULL, 19800, 0, 0x01U},
            ContinuationLine{23400, 0x0eabe57c20ULL, 23400, 0, 0x03U},
            ContinuationLine{21600, 0x0ebdb46628ULL, 21600, 0, 0x02U},
            ContinuationLine{19800, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x000dU, 0x000fU, 0x0010U, 0x01c0U, 0x01d9U},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Damascus() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(116U) /* Syria */},
        std::vector<ContinuationLine>{
            ContinuationLine{8712, 0x0e1b672778ULL, 8712, 0, 0x04U},
            ContinuationLine{7200, 0x0edccf6d50ULL, 10800, 65552, 0x00U},
            ContinuationLine{10800, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0008U, 0x010dU, 0x010eU, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x03U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x02U,
            0x02U,
            0x03U});
}

auto infoAsia_Dhaka() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(34U) /* Dhaka */},
        std::vector<ContinuationLine>{
            ContinuationLine{21700, 0x0de2fb02bcULL, 21700, 0, 0x06U},
            ContinuationLine{21200, 0x0e445002b0ULL, 21200, 0, 0x05U},
            ContinuationLine{23400, 0x0e4579ed18ULL, 23400, 0, 0x03U},
            ContinuationLine{19800, 0x0e4609aea8ULL, 19800, 0, 0x01U},
            ContinuationLine{23400, 0x0e571d4e98ULL, 23400, 0, 0x03U},
            ContinuationLine{21600, 0x0ec2d02f20ULL, 21600, 0, 0x02U},
            ContinuationLine{21600, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x000dU, 0x000fU, 0x0010U, 0x0011U, 0x016dU, 0x01c0U},
        std::vector<AbbreviationOffset>{0x04U, 0x02U});
}

auto infoAsia_Dili() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{30140, 0x0e0c5a9a00ULL, 30140, 0, 0x03U},
            ContinuationLine{28800, 0x0e450daef0ULL, 28800, 0, 0x01U},
            ContinuationLine{32400, 0x0e855eac70ULL, 32400, 0, 0x02U},
            ContinuationLine{28800, 0x0eb3381500ULL, 28800, 0, 0x01U},
            ContinuationLine{32400, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x0014U, 0x0017U, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Dubai() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{13272, 0x0e1b6715a8ULL, 13272, 0, 0x02U},
            ContinuationLine{14400, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x000aU, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Dushanbe() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(103U) /* RussiaAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{16512, 0x0e238dff80ULL, 16512, 0, 0x04U},
            ContinuationLine{18000, 0x0e2f186b30ULL, 18000, 0, 0x01U},
            ContinuationLine{21600, 0x0ea1696a40ULL, 25200, 65552, 0x00U},
            ContinuationLine{18000, 0x0ea23f0b50ULL, 21600, 3600, 0x02U},
            ContinuationLine{18000, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x000cU, 0x000fU, 0x0011U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x02U, 0x03U, 0x02U});
}

auto infoAsia_Famagusta() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(29U) /* Cyprus */, ruleSet(38U) /* EUAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{8148, 0x0e1eeb9a2cULL, 8148, 0, 0x04U},
            ContinuationLine{7200, 0x0eaf5f8ad0ULL, 10800, 65552, 0x00U},
            ContinuationLine{7200, 0x0ed144fbd0ULL, 10800, 65617, 0x00U},
            ContinuationLine{10800, 0x0ed369a410ULL, 10800, 0, 0x01U},
            ContinuationLine{7200, 0x0000000000ULL, 0, 65617, 0x00U},
        },
        std::vector<TextId>{0x0008U, 0x010dU, 0x010eU, 0x01c0U},
        std::vector<AbbreviationOffset>{0x02U, 0x03U, 0x02U, 0x03U, 0x02U, 0x03U, 0x03U, 0x03U, 0x02U});
}

auto infoAsia_Gaza() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{
            ruleSet(42U) /* EgyptAsia */,
            ruleSet(64U) /* Jordan */,
            ruleSet(90U) /* Palestine */,
            ruleSet(133U) /* Zion */},
        std::vector<ContinuationLine>{
            ContinuationLine{8272, 0x0df731c6b0ULL, 8272, 0, 0x07U},
            ContinuationLine{7200, 0x0e50c3f650ULL, 10800, 65539, 0x03U},
            ContinuationLine{7200, 0x0e749bbe50ULL, 10800, 65552, 0x00U},
            ContinuationLine{7200, 0x0eaa5b75d0ULL, 10800, 65651, 0x00U},
            ContinuationLine{7200, 0x0eb00061d0ULL, 10800, 67009, 0x00U},
            ContinuationLine{7200, 0x0ec22b8dd0ULL, 10800, 67506, 0x00U},
            ContinuationLine{7200, 0x0ec22f9060ULL, 7200, 0, 0x02U},
            ContinuationLine{7200, 0x0ec4b18cd0ULL, 10800, 67506, 0x00U},
            ContinuationLine{7200, 0x0ec521aa9cULL, 7200, 0, 0x02U},
            ContinuationLine{7200, 0x0ec7aa3e50ULL, 10800, 67506, 0x00U},
            ContinuationLine{7200, 0x0ec87401e0ULL, 7200, 0, 0x02U},
            ContinuationLine{7200, 0x0000000000ULL, 0, 67506, 0x00U},
        },
        std::vector<TextId>{0x010dU, 0x010eU, 0x010fU, 0x017fU, 0x0180U, 0x0182U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x05U,
            0x04U,
            0x05U,
            0x06U,
            0x05U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x06U,
            0x06U,
            0x06U,
            0x06U,
            0x06U,
            0x06U,
            0x06U,
            0x05U,
            0x06U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x01U,
            0x01U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U});
}

auto infoAsia_Hebron() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{
            ruleSet(42U) /* EgyptAsia */,
            ruleSet(64U) /* Jordan */,
            ruleSet(90U) /* Palestine */,
            ruleSet(133U) /* Zion */},
        std::vector<ContinuationLine>{
            ContinuationLine{8423, 0x0df731c619ULL, 8423, 0, 0x07U},
            ContinuationLine{7200, 0x0e50c3f650ULL, 10800, 65539, 0x03U},
            ContinuationLine{7200, 0x0e749bbe50ULL, 10800, 65552, 0x00U},
            ContinuationLine{7200, 0x0eaa5b75d0ULL, 10800, 65651, 0x00U},
            ContinuationLine{7200, 0x0eb00061d0ULL, 10800, 67009, 0x00U},
            ContinuationLine{7200, 0x0000000000ULL, 0, 67506, 0x00U},
        },
        std::vector<TextId>{0x010dU, 0x010eU, 0x010fU, 0x017fU, 0x0180U, 0x0182U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x05U,
            0x04U,
            0x05U,
            0x06U,
            0x05U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x05U,
            0x06U,
            0x06U,
            0x06U,
            0x06U,
            0x06U,
            0x06U,
            0x06U,
            0x06U,
            0x05U,
            0x06U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x01U,
            0x01U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U});
}

auto infoAsia_HoChiMinh() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{25590, 0x0e0200bf8aULL, 25590, 0, 0x04U},
            ContinuationLine{25590, 0x0e0b17a70aULL, 25590, 0, 0x05U},
            ContinuationLine{25200, 0x0e46aa6280ULL, 25200, 0, 0x01U},
            ContinuationLine{28800, 0x0e4ace4a70ULL, 28800, 0, 0x02U},
            ContinuationLine{32400, 0x0e4bafbaf0ULL, 32400, 0, 0x03U},
            ContinuationLine{25200, 0x0e4ea73710ULL, 25200, 0, 0x01U},
            ContinuationLine{28800, 0x0e5e2b6e90ULL, 28800, 0, 0x02U},
            ContinuationLine{25200, 0x0e66a41400ULL, 25200, 0, 0x01U},
            ContinuationLine{28800, 0x0e83b24300ULL, 28800, 0, 0x02U},
            ContinuationLine{25200, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0011U, 0x0014U, 0x0017U, 0x01c0U, 0x023fU},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_HongKong() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(53U) /* HK */},
        std::vector<ContinuationLine>{
            ContinuationLine{27402, 0x0dfedddf90ULL, 27402, 0, 0x05U},
            ContinuationLine{28800, 0x0e43c1ad30ULL, 28800, 0, 0x02U},
            ContinuationLine{28800, 0x0e44500f30ULL, 32400, 3600, 0x01U},
            ContinuationLine{28800, 0x0e44bfed78ULL, 30600, 1800, 0x03U},
            ContinuationLine{32400, 0x0e4c155a90ULL, 32400, 0, 0x04U},
            ContinuationLine{28800, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x016aU, 0x016bU, 0x016cU, 0x0192U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x01U, 0x02U, 0x01U, 0x01U, 0x02U});
}

auto infoAsia_Hovd() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(79U) /* Mongol */},
        std::vector<ContinuationLine>{
            ContinuationLine{21996, 0x0e00487894ULL, 21996, 0, 0x04U},
            ContinuationLine{21600, 0x0e888066a0ULL, 21600, 0, 0x01U},
            ContinuationLine{25200, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x000fU, 0x0011U, 0x0014U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x03U, 0x02U, 0x03U, 0x02U, 0x03U, 0x03U, 0x02U});
}

auto infoAsia_Jakarta() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{25632, 0x0db8dac560ULL, 25632, 0, 0x06U},
            ContinuationLine{25632, 0x0e22ed01e0ULL, 25632, 0, 0x05U},
            ContinuationLine{26400, 0x0e338b5a60ULL, 26400, 0, 0x01U},
            ContinuationLine{27000, 0x0e4533ff88ULL, 27000, 0, 0x02U},
            ContinuationLine{32400, 0x0e4bcb6a70ULL, 32400, 0, 0x04U},
            ContinuationLine{27000, 0x0e50b14208ULL, 27000, 0, 0x02U},
            ContinuationLine{28800, 0x0e5473a200ULL, 28800, 0, 0x03U},
            ContinuationLine{27000, 0x0e6e2a3a88ULL, 27000, 0, 0x02U},
            ContinuationLine{25200, 0x0000000000ULL, 0, 0, 0x07U},
        },
        std::vector<TextId>{0x0012U, 0x0013U, 0x0014U, 0x0017U, 0x0085U, 0x01c0U, 0x02eeU},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Jayapura() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{33768, 0x0e338b3d98ULL, 33768, 0, 0x03U},
            ContinuationLine{32400, 0x0e49cd35f0ULL, 32400, 0, 0x01U},
            ContinuationLine{34200, 0x0e6e2a1e68ULL, 34200, 0, 0x02U},
            ContinuationLine{32400, 0x0000000000ULL, 0, 0, 0x04U},
        },
        std::vector<TextId>{0x0017U, 0x0018U, 0x01c0U, 0x02efU},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Jerusalem() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(133U) /* Zion */},
        std::vector<ContinuationLine>{
            ContinuationLine{8454, 0x0dd02b3efaULL, 8454, 0, 0x05U},
            ContinuationLine{8440, 0x0e17a4c188ULL, 8440, 0, 0x04U},
            ContinuationLine{7200, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x017fU, 0x0180U, 0x0182U, 0x0191U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x02U,
            0x01U,
            0x02U,
            0x03U,
            0x02U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x02U,
            0x03U,
            0x03U,
            0x03U,
            0x03U,
            0x03U,
            0x03U,
            0x03U,
            0x03U,
            0x02U,
            0x03U});
}

auto infoAsia_Kabul() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{16608, 0x0de2fb16a0ULL, 16608, 0, 0x03U},
            ContinuationLine{14400, 0x0e4a6e5340ULL, 14400, 0, 0x01U},
            ContinuationLine{16200, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x000aU, 0x000bU, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Karachi() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(89U) /* Pakistan */},
        std::vector<ContinuationLine>{
            ContinuationLine{16092, 0x0e02f378a4ULL, 16092, 0, 0x04U},
            ContinuationLine{19800, 0x0e4609aea8ULL, 19800, 0, 0x02U},
            ContinuationLine{19800, 0x0e4be88e98ULL, 23400, 3600, 0x03U},
            ContinuationLine{19800, 0x0e571d5ca8ULL, 19800, 0, 0x02U},
            ContinuationLine{18000, 0x0e7bc42730ULL, 18000, 0, 0x01U},
            ContinuationLine{18000, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x000cU, 0x000dU, 0x0010U, 0x01c0U, 0x023dU, 0x023eU},
        std::vector<AbbreviationOffset>{0x05U, 0x06U, 0x05U, 0x06U, 0x05U});
}

auto infoAsia_Kathmandu() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{20476, 0x0e1b66f984ULL, 20476, 0, 0x03U},
            ContinuationLine{19800, 0x0e978caca8ULL, 19800, 0, 0x01U},
            ContinuationLine{20700, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x000dU, 0x000eU, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Kolkata() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{21208, 0x0da02e9428ULL, 21208, 0, 0x04U},
            ContinuationLine{21200, 0x0dbd5c6730ULL, 21200, 0, 0x02U},
            ContinuationLine{19270, 0x0e011238baULL, 19270, 0, 0x05U},
            ContinuationLine{19800, 0x0e44500828ULL, 19800, 0, 0x03U},
            ContinuationLine{19800, 0x0e4579ed18ULL, 23400, 3600, 0x01U},
            ContinuationLine{19800, 0x0e4609aea8ULL, 19800, 0, 0x03U},
            ContinuationLine{19800, 0x0e4be88e98ULL, 23400, 3600, 0x01U},
            ContinuationLine{19800, 0x0000000000ULL, 0, 0, 0x03U},
        },
        std::vector<TextId>{0x0010U, 0x016dU, 0x0182U, 0x01c0U, 0x01d9U},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Kuching() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(81U) /* NBorneo */},
        std::vector<ContinuationLine>{
            ContinuationLine{26480, 0x0e26fe8290ULL, 26480, 0, 0x05U},
            ContinuationLine{27000, 0x0e33dbc388ULL, 27000, 0, 0x01U},
            ContinuationLine{28800, 0x0e4505cf50ULL, 30000, 65552, 0x00U},
            ContinuationLine{32400, 0x0e4bbce9f0ULL, 32400, 0, 0x04U},
            ContinuationLine{28800, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x0013U, 0x0014U, 0x0015U, 0x0017U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U});
}

auto infoAsia_Macau() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(71U) /* Macau */},
        std::vector<ContinuationLine>{
            ContinuationLine{27250, 0x0dfeddd78eULL, 27250, 0, 0x06U},
            ContinuationLine{28800, 0x0e44bbf1f0ULL, 28800, 0, 0x04U},
            ContinuationLine{32400, 0x0e4bd5e860ULL, 36000, 65552, 0x00U},
            ContinuationLine{28800, 0x0000000000ULL, 0, 65984, 0x00U},
        },
        std::vector<TextId>{0x0017U, 0x001aU, 0x00b5U, 0x00bbU, 0x00bdU, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x01U,
            0x01U,
            0x02U,
            0x02U,
            0x02U,
            0x01U,
            0x05U,
            0x05U,
            0x04U,
            0x03U,
            0x04U,
            0x03U,
            0x04U,
            0x03U,
            0x04U,
            0x03U,
            0x04U,
            0x03U,
            0x04U,
            0x03U,
            0x04U,
            0x04U,
            0x03U,
            0x04U,
            0x04U,
            0x03U,
            0x03U,
            0x04U,
            0x04U,
            0x03U,
            0x03U,
            0x03U,
            0x04U});
}

auto infoAsia_Makassar() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{28656, 0x0e1b66d990ULL, 28656, 0, 0x03U},
            ContinuationLine{28656, 0x0e338b5190ULL, 28656, 0, 0x04U},
            ContinuationLine{28800, 0x0e44fc9980ULL, 28800, 0, 0x01U},
            ContinuationLine{32400, 0x0e4bcb6a70ULL, 32400, 0, 0x02U},
            ContinuationLine{28800, 0x0000000000ULL, 0, 0, 0x05U},
        },
        std::vector<TextId>{0x0014U, 0x0017U, 0x01c0U, 0x01d9U, 0x02f0U},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Manila() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(94U) /* Phil */},
        std::vector<ContinuationLine>{
            ContinuationLine{-57368, 0x0d8e565818ULL, -57368, 0, 0x02U},
            ContinuationLine{29032, 0x0df52ff640ULL, 29032, 0, 0x02U},
            ContinuationLine{28800, 0x0e45007ff0ULL, 32400, 65552, 0x00U},
            ContinuationLine{32400, 0x0e4abfc9f0ULL, 32400, 0, 0x01U},
            ContinuationLine{28800, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0192U, 0x01c0U, 0x023cU, 0x0245U},
        std::vector<AbbreviationOffset>{0x03U, 0x04U, 0x03U, 0x04U, 0x03U, 0x04U, 0x03U, 0x04U, 0x03U, 0x04U});
}

auto infoAsia_Nicosia() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(29U) /* Cyprus */, ruleSet(38U) /* EUAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{8008, 0x0e1eeb9ab8ULL, 8008, 0, 0x03U},
            ContinuationLine{7200, 0x0eaf5f8ad0ULL, 10800, 65552, 0x00U},
            ContinuationLine{7200, 0x0000000000ULL, 0, 65617, 0x00U},
        },
        std::vector<TextId>{0x010dU, 0x010eU, 0x01c0U},
        std::vector<AbbreviationOffset>{0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x02U, 0x02U, 0x01U});
}

auto infoAsia_Oral() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(103U) /* RussiaAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{12324, 0x0e238e0fdcULL, 12324, 0, 0x05U},
            ContinuationLine{10800, 0x0e2f188750ULL, 10800, 0, 0x01U},
            ContinuationLine{18000, 0x0e8e9c07b0ULL, 18000, 0, 0x03U},
            ContinuationLine{18000, 0x0e8f8d3c20ULL, 21600, 3600, 0x04U},
            ContinuationLine{21600, 0x0e907d2d20ULL, 21600, 0, 0x04U},
            ContinuationLine{18000, 0x0e9da079d0ULL, 21600, 65552, 0x00U},
            ContinuationLine{14400, 0x0ea2ed1f60ULL, 18000, 65616, 0x00U},
            ContinuationLine{18000, 0x0ea3495a50ULL, 21600, 65552, 0x00U},
            ContinuationLine{14400, 0x0ebaf88ae0ULL, 18000, 65616, 0x00U},
            ContinuationLine{18000, 0x0000000000ULL, 0, 0, 0x03U},
        },
        std::vector<TextId>{0x0008U, 0x000aU, 0x000cU, 0x000fU, 0x01c0U},
        std::vector<AbbreviationOffset>{0x04U, 0x03U, 0x03U, 0x04U, 0x03U, 0x02U, 0x02U, 0x03U, 0x02U});
}

auto infoAsia_Pontianak() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{26240, 0x0e05740a00ULL, 26240, 0, 0x04U},
            ContinuationLine{26240, 0x0e338b5b00ULL, 26240, 0, 0x05U},
            ContinuationLine{27000, 0x0e44ee2008ULL, 27000, 0, 0x01U},
            ContinuationLine{32400, 0x0e4bcb6a70ULL, 32400, 0, 0x03U},
            ContinuationLine{27000, 0x0e50b14208ULL, 27000, 0, 0x01U},
            ContinuationLine{28800, 0x0e5473a200ULL, 28800, 0, 0x02U},
            ContinuationLine{27000, 0x0e6e2a3a88ULL, 27000, 0, 0x01U},
            ContinuationLine{28800, 0x0e9b4ef080ULL, 28800, 0, 0x07U},
            ContinuationLine{25200, 0x0000000000ULL, 0, 0, 0x06U},
        },
        std::vector<TextId>{0x0013U, 0x0014U, 0x0017U, 0x01c0U, 0x0241U, 0x02eeU, 0x02f0U},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Pyongyang() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{30180, 0x0e054c6d9cULL, 30180, 0, 0x03U},
            ContinuationLine{30600, 0x0e0c5a92f8ULL, 30600, 0, 0x02U},
            ContinuationLine{32400, 0x0e4ba3dd70ULL, 32400, 0, 0x01U},
            ContinuationLine{32400, 0x0ecf427e70ULL, 32400, 0, 0x02U},
            ContinuationLine{30600, 0x0ed460f170ULL, 30600, 0, 0x02U},
            ContinuationLine{32400, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x0192U, 0x01a1U, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Qatar() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{12368, 0x0e1b671930ULL, 12368, 0, 0x03U},
            ContinuationLine{14400, 0x0e7dff0ec0ULL, 14400, 0, 0x02U},
            ContinuationLine{10800, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0008U, 0x000aU, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Qostanay() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(103U) /* RussiaAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{15268, 0x0e238e045cULL, 15268, 0, 0x04U},
            ContinuationLine{14400, 0x0e2f187940ULL, 14400, 0, 0x01U},
            ContinuationLine{18000, 0x0e8e9c07b0ULL, 18000, 0, 0x02U},
            ContinuationLine{18000, 0x0e8f8d3c20ULL, 21600, 3600, 0x03U},
            ContinuationLine{21600, 0x0e907d2d20ULL, 21600, 0, 0x03U},
            ContinuationLine{18000, 0x0ea1697850ULL, 21600, 65552, 0x00U},
            ContinuationLine{14400, 0x0ea2ed1f60ULL, 18000, 65616, 0x00U},
            ContinuationLine{18000, 0x0ebaf87cd0ULL, 21600, 65552, 0x00U},
            ContinuationLine{21600, 0x0edf554220ULL, 21600, 0, 0x03U},
            ContinuationLine{18000, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x000aU, 0x000cU, 0x000fU, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x02U, 0x03U, 0x02U, 0x01U, 0x01U, 0x02U, 0x01U});
}

auto infoAsia_Qyzylorda() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(103U) /* RussiaAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{15712, 0x0e238e02a0ULL, 15712, 0, 0x05U},
            ContinuationLine{14400, 0x0e2f187940ULL, 14400, 0, 0x01U},
            ContinuationLine{18000, 0x0e8e9c07b0ULL, 18000, 0, 0x02U},
            ContinuationLine{18000, 0x0e8f8d3c20ULL, 21600, 3600, 0x03U},
            ContinuationLine{21600, 0x0e907d2d20ULL, 21600, 0, 0x03U},
            ContinuationLine{18000, 0x0ea1697850ULL, 21600, 65552, 0x00U},
            ContinuationLine{14400, 0x0ea2597760ULL, 18000, 65616, 0x00U},
            ContinuationLine{18000, 0x0ea2ed1150ULL, 21600, 65552, 0x00U},
            ContinuationLine{21600, 0x0ea3494c40ULL, 25200, 65696, 0x00U},
            ContinuationLine{18000, 0x0ebaf87cd0ULL, 21600, 65552, 0x00U},
            ContinuationLine{21600, 0x0ed59054a0ULL, 21600, 0, 0x03U},
            ContinuationLine{18000, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x000aU, 0x000cU, 0x000fU, 0x0011U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x03U, 0x02U, 0x02U, 0x03U, 0x02U, 0x01U, 0x01U, 0x02U, 0x01U, 0x04U, 0x03U, 0x03U, 0x04U, 0x03U});
}

auto infoAsia_Riyadh() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{11212, 0x0e4e8fb2b4ULL, 11212, 0, 0x02U},
            ContinuationLine{10800, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0008U, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Samarkand() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(103U) /* RussiaAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{16073, 0x0e238e0137ULL, 16073, 0, 0x04U},
            ContinuationLine{14400, 0x0e2f187940ULL, 14400, 0, 0x01U},
            ContinuationLine{18000, 0x0e8e9c07b0ULL, 18000, 0, 0x02U},
            ContinuationLine{18000, 0x0e8f8d3c20ULL, 21600, 3600, 0x03U},
            ContinuationLine{21600, 0x0e907d2d20ULL, 21600, 0, 0x03U},
            ContinuationLine{18000, 0x0ea2d52c20ULL, 21600, 65552, 0x00U},
            ContinuationLine{18000, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x000aU, 0x000cU, 0x000fU, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x02U, 0x03U, 0x02U});
}

auto infoAsia_Seoul() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(99U) /* ROK */},
        std::vector<ContinuationLine>{
            ContinuationLine{30472, 0x0e054c6c78ULL, 30472, 0, 0x04U},
            ContinuationLine{30600, 0x0e0c5a92f8ULL, 30600, 0, 0x03U},
            ContinuationLine{32400, 0x0e4bb7a3f0ULL, 32400, 0, 0x01U},
            ContinuationLine{32400, 0x0e5bc397e0ULL, 36000, 65552, 0x00U},
            ContinuationLine{30600, 0x0e69a9df68ULL, 34200, 65552, 0x00U},
            ContinuationLine{32400, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0192U, 0x019fU, 0x01a1U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x02U, 0x03U, 0x02U, 0x03U, 0x02U, 0x02U, 0x02U, 0x03U, 0x02U, 0x03U, 0x02U, 0x03U, 0x02U, 0x03U});
}

auto infoAsia_Shanghai() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(88U) /* PRC */, ruleSet(107U) /* Shang */},
        std::vector<ContinuationLine>{
            ContinuationLine{29143, 0x0df7aabf29ULL, 29143, 0, 0x03U},
            ContinuationLine{28800, 0x0e52b5f8f0ULL, 32400, 65553, 0x00U},
            ContinuationLine{28800, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x00b5U, 0x00bbU, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U});
}

auto infoAsia_Singapore() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{24925, 0x0df7aacfa3ULL, 24925, 0, 0x06U},
            ContinuationLine{24925, 0x0dfff801a3ULL, 24925, 0, 0x07U},
            ContinuationLine{25200, 0x0e33dbca90ULL, 25200, 0, 0x01U},
            ContinuationLine{25200, 0x0e397f6060ULL, 26400, 1200, 0x02U},
            ContinuationLine{26400, 0x0e44286160ULL, 26400, 0, 0x02U},
            ContinuationLine{27000, 0x0e4505db08ULL, 27000, 0, 0x03U},
            ContinuationLine{32400, 0x0e4bbce9f0ULL, 32400, 0, 0x05U},
            ContinuationLine{27000, 0x0e90066a00ULL, 27000, 0, 0x03U},
            ContinuationLine{28800, 0x0000000000ULL, 0, 0, 0x04U},
        },
        std::vector<TextId>{0x0011U, 0x0012U, 0x0013U, 0x0014U, 0x0017U, 0x01c0U, 0x0281U},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Taipei() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(117U) /* Taiwan */},
        std::vector<ContinuationLine>{
            ContinuationLine{29160, 0x0dee436c18ULL, 29160, 0, 0x04U},
            ContinuationLine{28800, 0x0e3cc9c580ULL, 28800, 0, 0x02U},
            ContinuationLine{32400, 0x0e4bc8d580ULL, 32400, 0, 0x03U},
            ContinuationLine{28800, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x00b5U, 0x00bbU, 0x0192U, 0x01c0U},
        std::vector<AbbreviationOffset>{
            0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x02U, 0x01U, 0x01U, 0x02U, 0x01U, 0x02U});
}

auto infoAsia_Tashkent() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(103U) /* RussiaAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{16631, 0x0e238dff09ULL, 16631, 0, 0x04U},
            ContinuationLine{18000, 0x0e2f186b30ULL, 18000, 0, 0x01U},
            ContinuationLine{21600, 0x0ea1695c30ULL, 25200, 65552, 0x00U},
            ContinuationLine{18000, 0x0ea2d52c20ULL, 21600, 65616, 0x00U},
            ContinuationLine{18000, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x000cU, 0x000fU, 0x0011U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x02U, 0x03U, 0x02U, 0x01U, 0x01U, 0x02U, 0x01U});
}

auto infoAsia_Tbilisi() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(36U) /* E-EurAsia */, ruleSet(103U) /* RussiaAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{10751, 0x0dd02b3601ULL, 10751, 0, 0x04U},
            ContinuationLine{10751, 0x0e238e1601ULL, 10751, 0, 0x05U},
            ContinuationLine{10800, 0x0e614e8850ULL, 10800, 0, 0x01U},
            ContinuationLine{14400, 0x0ea1698660ULL, 18000, 65553, 0x00U},
            ContinuationLine{10800, 0x0ea2d54840ULL, 14400, 65617, 0x00U},
            ContinuationLine{10800, 0x0ea7f90140ULL, 14400, 65616, 0x00U},
            ContinuationLine{14400, 0x0eabe6dbb0ULL, 18000, 65552, 0x00U},
            ContinuationLine{14400, 0x0eacb1e2b0ULL, 18000, 3600, 0x03U},
            ContinuationLine{14400, 0x0eba5243b0ULL, 18000, 65552, 0x00U},
            ContinuationLine{10800, 0x0ebbba5760ULL, 14400, 65617, 0x00U},
            ContinuationLine{14400, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x0008U, 0x000aU, 0x000cU, 0x01c0U, 0x02afU},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x02U, 0x03U, 0x02U, 0x01U, 0x01U, 0x02U, 0x01U});
}

auto infoAsia_Tehran() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(60U) /* Iran */},
        std::vector<ContinuationLine>{
            ContinuationLine{12344, 0x0e13e0f9c8ULL, 12344, 0, 0x05U},
            ContinuationLine{12344, 0x0e38754848ULL, 12344, 0, 0x06U},
            ContinuationLine{12600, 0x0e88219dc8ULL, 12600, 65552, 0x00U},
            ContinuationLine{14400, 0x0e8a1e6bb0ULL, 18000, 66192, 0x00U},
            ContinuationLine{12600, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0009U, 0x000aU, 0x000bU, 0x000cU, 0x01c0U, 0x02b0U},
        std::vector<AbbreviationOffset>{
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x03U,
            0x01U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U,
            0x04U,
            0x02U});
}

auto infoAsia_Thimphu() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{21516, 0x0e4f5a9174ULL, 21516, 0, 0x03U},
            ContinuationLine{19800, 0x0e9ad5c9a8ULL, 19800, 0, 0x01U},
            ContinuationLine{21600, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x000dU, 0x000fU, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Tokyo() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(63U) /* Japan */},
        std::vector<ContinuationLine>{
            ContinuationLine{33539, 0x0ddf372070ULL, 33539, 0, 0x03U},
            ContinuationLine{32400, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0190U, 0x0192U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x01U, 0x02U, 0x01U, 0x01U});
}

auto infoAsia_Ulaanbaatar() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(79U) /* Mongol */},
        std::vector<ContinuationLine>{
            ContinuationLine{25652, 0x0e00486a4cULL, 25652, 0, 0x04U},
            ContinuationLine{25200, 0x0e88805890ULL, 25200, 0, 0x01U},
            ContinuationLine{28800, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0011U, 0x0014U, 0x0017U, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x03U, 0x02U, 0x03U, 0x02U, 0x03U, 0x03U, 0x02U});
}

auto infoAsia_Urumqi() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{21020, 0x0e2a733664ULL, 21020, 0, 0x02U},
            ContinuationLine{21600, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x000fU, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Yangon() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{23087, 0x0dd02b05d1ULL, 23087, 0, 0x03U},
            ContinuationLine{23087, 0x0e1b66ef51ULL, 23087, 0, 0x04U},
            ContinuationLine{23400, 0x0e45677818ULL, 23400, 0, 0x01U},
            ContinuationLine{32400, 0x0e4b0ee3f0ULL, 32400, 0, 0x02U},
            ContinuationLine{23400, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x0010U, 0x0017U, 0x01c0U, 0x026aU},
        std::vector<AbbreviationOffset>{});
}

auto infoAsia_Yerevan() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{ruleSet(9U) /* Armenia */, ruleSet(103U) /* RussiaAsia */},
        std::vector<ContinuationLine>{
            ContinuationLine{10680, 0x0e238e1648ULL, 10680, 0, 0x04U},
            ContinuationLine{10800, 0x0e614e8850ULL, 10800, 0, 0x01U},
            ContinuationLine{14400, 0x0ea1698660ULL, 18000, 65553, 0x00U},
            ContinuationLine{10800, 0x0ea9d90d70ULL, 14400, 65617, 0x00U},
            ContinuationLine{14400, 0x0eac3decc0ULL, 14400, 0, 0x02U},
            ContinuationLine{14400, 0x0ec692a430ULL, 18000, 65553, 0x00U},
            ContinuationLine{14400, 0x0000000000ULL, 0, 65552, 0x00U},
        },
        std::vector<TextId>{0x0008U, 0x000aU, 0x000cU, 0x01c0U},
        std::vector<AbbreviationOffset>{0x03U, 0x02U, 0x02U, 0x03U, 0x02U, 0x01U, 0x01U, 0x02U, 0x01U});
}

auto infoIndian_Chagos() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{17380, 0x0e02f3739cULL, 17380, 0, 0x03U},
            ContinuationLine{18000, 0x0eaa5b59b0ULL, 18000, 0, 0x01U},
            ContinuationLine{21600, 0x0000000000ULL, 0, 0, 0x02U},
        },
        std::vector<TextId>{0x000cU, 0x000fU, 0x01c0U},
        std::vector<AbbreviationOffset>{});
}

auto infoIndian_Maldives() noexcept -> std::unique_ptr<Info> {
    return std::make_unique<Info>(
        std::vector<RuleSet>{},
        std::vector<ContinuationLine>{
            ContinuationLine{17640, 0x0dd02b1b18ULL, 17640, 0, 0x02U},
            ContinuationLine{17640, 0x0e66a43f98ULL, 17640, 0, 0x03U},
            ContinuationLine{18000, 0x0000000000ULL, 0, 0, 0x01U},
        },
        std::vector<TextId>{0x000cU, 0x01c0U, 0x01d9U},
        std::vector<AbbreviationOffset>{});
}

}
