// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.

#include "Info.hpp"

#include <memory>

namespace erbsland::time::tz::impl {

[[nodiscard]] auto infoAntarctica_Casey() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAntarctica_Davis() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAntarctica_Mawson() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAntarctica_Rothera() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAntarctica_Troll() noexcept -> std::unique_ptr<Info>;
[[nodiscard]] auto infoAntarctica_Vostok() noexcept -> std::unique_ptr<Info>;

}
