// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.

#include "RuleSet.hpp"

#include <cstdint>

namespace erbsland::time::tz::impl {

[[nodiscard]] auto ruleSet(uint16_t index) noexcept -> RuleSet;

}
