// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.

#include "Text.hpp"
#include "ZoneName.hpp"

#include <array>
#include <string_view>

namespace erbsland::time::tz::impl {

[[nodiscard]] auto textEntries() noexcept -> const std::array<Text, 780> &;
[[nodiscard]] auto textBlock() noexcept -> std::string_view;
[[nodiscard]] auto zoneNames() noexcept -> const std::array<ZoneName, 597> &;
[[nodiscard]] auto primaryZoneNames() noexcept -> const std::array<ZoneName, 340> &;

}
