// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.

#include "../../TimeZoneId.hpp"

#include <optional>
#include <string_view>

namespace erbsland::time::tz::impl {

/// Map a Windows time-zone key to the canonical CLDR world-territory IANA zone identifier.
/// @param windowsName The Windows time-zone key.
/// @return The time-zone identifier, or no value for an unknown key.
[[nodiscard]] auto timeZoneIdFromWindowsName(std::wstring_view windowsName) noexcept -> std::optional<TimeZoneId>;

}
