// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.
#include "WindowsTimeZoneMap.hpp"

#include <array>

namespace erbsland::time::tz::impl {

namespace {
struct Mapping {
    std::wstring_view windowsName;
    TimeZoneId timeZoneId;
};

// Generated from Unicode CLDR windowsZones.xml entries for territory "001".
constexpr auto cMappings = std::to_array<Mapping>({
    Mapping{L"AUS Central Standard Time", TimeZoneId{0x00eaU}},       // Australia/Darwin
    Mapping{L"AUS Eastern Standard Time", TimeZoneId{0x00f1U}},       // Australia/Sydney
    Mapping{L"Afghanistan Standard Time", TimeZoneId{0x00b3U}},       // Asia/Kabul
    Mapping{L"Alaskan Standard Time", TimeZoneId{0x0015U}},           // America/Anchorage
    Mapping{L"Aleutian Standard Time", TimeZoneId{0x0014U}},          // America/Adak
    Mapping{L"Altai Standard Time", TimeZoneId{0x009fU}},             // Asia/Barnaul
    Mapping{L"Arab Standard Time", TimeZoneId{0x00c9U}},              // Asia/Riyadh
    Mapping{L"Arabian Standard Time", TimeZoneId{0x00a7U}},           // Asia/Dubai
    Mapping{L"Arabic Standard Time", TimeZoneId{0x009cU}},            // Asia/Baghdad
    Mapping{L"Argentina Standard Time", TimeZoneId{0x0017U}},         // America/Buenos_Aires
    Mapping{L"Astrakhan Standard Time", TimeZoneId{0x010fU}},         // Europe/Astrakhan
    Mapping{L"Atlantic Standard Time", TimeZoneId{0x0047U}},          // America/Halifax
    Mapping{L"Aus Central W. Standard Time", TimeZoneId{0x00ebU}},    // Australia/Eucla
    Mapping{L"Azerbaijan Standard Time", TimeZoneId{0x009dU}},        // Asia/Baku
    Mapping{L"Azores Standard Time", TimeZoneId{0x00dfU}},            // Atlantic/Azores
    Mapping{L"Bahia Standard Time", TimeZoneId{0x0024U}},             // America/Bahia
    Mapping{L"Bangladesh Standard Time", TimeZoneId{0x00a5U}},        // Asia/Dhaka
    Mapping{L"Belarus Standard Time", TimeZoneId{0x0122U}},           // Europe/Minsk
    Mapping{L"Bougainville Standard Time", TimeZoneId{0x0139U}},      // Pacific/Bougainville
    Mapping{L"Canada Central Standard Time", TimeZoneId{0x007aU}},    // America/Regina
    Mapping{L"Cape Verde Standard Time", TimeZoneId{0x00e2U}},        // Atlantic/Cape_Verde
    Mapping{L"Caucasus Standard Time", TimeZoneId{0x00deU}},          // Asia/Yerevan
    Mapping{L"Cen. Australia Standard Time", TimeZoneId{0x00e7U}},    // Australia/Adelaide
    Mapping{L"Central America Standard Time", TimeZoneId{0x0044U}},   // America/Guatemala
    Mapping{L"Central Asia Standard Time", TimeZoneId{0x00a1U}},      // Asia/Bishkek
    Mapping{L"Central Brazilian Standard Time", TimeZoneId{0x0036U}}, // America/Cuiaba
    Mapping{L"Central Europe Standard Time", TimeZoneId{0x0115U}},    // Europe/Budapest
    Mapping{L"Central European Standard Time", TimeZoneId{0x0132U}},  // Europe/Warsaw
    Mapping{L"Central Pacific Standard Time", TimeZoneId{0x0141U}},   // Pacific/Guadalcanal
    Mapping{L"Central Standard Time", TimeZoneId{0x0031U}},           // America/Chicago
    Mapping{L"Central Standard Time (Mexico)", TimeZoneId{0x0064U}},  // America/Mexico_City
    Mapping{L"Chatham Islands Standard Time", TimeZoneId{0x013aU}},   // Pacific/Chatham
    Mapping{L"China Standard Time", TimeZoneId{0x00cdU}},             // Asia/Shanghai
    Mapping{L"Cuba Standard Time", TimeZoneId{0x0048U}},              // America/Havana
    Mapping{L"Dateline Standard Time", TimeZoneId{0x00f6U}},          // Etc/GMT+12
    Mapping{L"E. Africa Standard Time", TimeZoneId{0x000eU}},         // Africa/Nairobi
    Mapping{L"E. Australia Standard Time", TimeZoneId{0x00e8U}},      // Australia/Brisbane
    Mapping{L"E. Europe Standard Time", TimeZoneId{0x0116U}},         // Europe/Chisinau
    Mapping{L"E. South America Standard Time", TimeZoneId{0x0080U}},  // America/Sao_Paulo
    Mapping{L"Easter Island Standard Time", TimeZoneId{0x013bU}},     // Pacific/Easter
    Mapping{L"Eastern Standard Time", TimeZoneId{0x0069U}},           // America/New_York
    Mapping{L"Eastern Standard Time (Mexico)", TimeZoneId{0x002eU}},  // America/Cancun
    Mapping{L"Egypt Standard Time", TimeZoneId{0x0004U}},             // Africa/Cairo
    Mapping{L"Ekaterinburg Standard Time", TimeZoneId{0x00ddU}},      // Asia/Yekaterinburg
    Mapping{L"FLE Standard Time", TimeZoneId{0x011dU}},               // Europe/Kiev
    Mapping{L"Fiji Standard Time", TimeZoneId{0x013eU}},              // Pacific/Fiji
    Mapping{L"GMT Standard Time", TimeZoneId{0x011fU}},               // Europe/London
    Mapping{L"GTB Standard Time", TimeZoneId{0x0114U}},               // Europe/Bucharest
    Mapping{L"Georgian Standard Time", TimeZoneId{0x00d2U}},          // Asia/Tbilisi
    Mapping{L"Greenland Standard Time", TimeZoneId{0x006fU}},         // America/Godthab
    Mapping{L"Greenwich Standard Time", TimeZoneId{0x0001U}},         // Atlantic/Reykjavik
    Mapping{L"Haiti Standard Time", TimeZoneId{0x0074U}},             // America/Port-au-Prince
    Mapping{L"Hawaiian Standard Time", TimeZoneId{0x0143U}},          // Pacific/Honolulu
    Mapping{L"India Standard Time", TimeZoneId{0x00b8U}},             // Asia/Calcutta
    Mapping{L"Iran Standard Time", TimeZoneId{0x00d3U}},              // Asia/Tehran
    Mapping{L"Israel Standard Time", TimeZoneId{0x00b2U}},            // Asia/Jerusalem
    Mapping{L"Jordan Standard Time", TimeZoneId{0x0096U}},            // Asia/Amman
    Mapping{L"Kaliningrad Standard Time", TimeZoneId{0x011bU}},       // Europe/Kaliningrad
    Mapping{L"Korea Standard Time", TimeZoneId{0x00ccU}},             // Asia/Seoul
    Mapping{L"Libya Standard Time", TimeZoneId{0x0011U}},             // Africa/Tripoli
    Mapping{L"Line Islands Standard Time", TimeZoneId{0x0145U}},      // Pacific/Kiritimati
    Mapping{L"Lord Howe Standard Time", TimeZoneId{0x00eeU}},         // Australia/Lord_Howe
    Mapping{L"Magadan Standard Time", TimeZoneId{0x00bcU}},           // Asia/Magadan
    Mapping{L"Magallanes Standard Time", TimeZoneId{0x0077U}},        // America/Punta_Arenas
    Mapping{L"Marquesas Standard Time", TimeZoneId{0x0148U}},         // Pacific/Marquesas
    Mapping{L"Mauritius Standard Time", TimeZoneId{0x0136U}},         // Indian/Mauritius
    Mapping{L"Middle East Standard Time", TimeZoneId{0x00a0U}},       // Asia/Beirut
    Mapping{L"Montevideo Standard Time", TimeZoneId{0x0068U}},        // America/Montevideo
    Mapping{L"Morocco Standard Time", TimeZoneId{0x0005U}},           // Africa/Casablanca
    Mapping{L"Mountain Standard Time", TimeZoneId{0x003aU}},          // America/Denver
    Mapping{L"Mountain Standard Time (Mexico)", TimeZoneId{0x0060U}}, // America/Mazatlan
    Mapping{L"Myanmar Standard Time", TimeZoneId{0x00dcU}},           // Asia/Rangoon
    Mapping{L"N. Central Asia Standard Time", TimeZoneId{0x00c1U}},   // Asia/Novosibirsk
    Mapping{L"Namibia Standard Time", TimeZoneId{0x0013U}},           // Africa/Windhoek
    Mapping{L"Nepal Standard Time", TimeZoneId{0x00b6U}},             // Asia/Katmandu
    Mapping{L"New Zealand Standard Time", TimeZoneId{0x0138U}},       // Pacific/Auckland
    Mapping{L"Newfoundland Standard Time", TimeZoneId{0x0083U}},      // America/St_Johns
    Mapping{L"Norfolk Standard Time", TimeZoneId{0x014bU}},           // Pacific/Norfolk
    Mapping{L"North Asia East Standard Time", TimeZoneId{0x00afU}},   // Asia/Irkutsk
    Mapping{L"North Asia Standard Time", TimeZoneId{0x00b9U}},        // Asia/Krasnoyarsk
    Mapping{L"North Korea Standard Time", TimeZoneId{0x00c5U}},       // Asia/Pyongyang
    Mapping{L"Omsk Standard Time", TimeZoneId{0x00c2U}},              // Asia/Omsk
    Mapping{L"Pacific SA Standard Time", TimeZoneId{0x007eU}},        // America/Santiago
    Mapping{L"Pacific Standard Time", TimeZoneId{0x005aU}},           // America/Los_Angeles
    Mapping{L"Pacific Standard Time (Mexico)", TimeZoneId{0x0087U}},  // America/Tijuana
    Mapping{L"Pakistan Standard Time", TimeZoneId{0x00b5U}},          // Asia/Karachi
    Mapping{L"Paraguay Standard Time", TimeZoneId{0x0023U}},          // America/Asuncion
    Mapping{L"Qyzylorda Standard Time", TimeZoneId{0x00c8U}},         // Asia/Qyzylorda
    Mapping{L"Romance Standard Time", TimeZoneId{0x0124U}},           // Europe/Paris
    Mapping{L"Russia Time Zone 10", TimeZoneId{0x00cfU}},             // Asia/Srednekolymsk
    Mapping{L"Russia Time Zone 11", TimeZoneId{0x00b4U}},             // Asia/Kamchatka
    Mapping{L"Russia Time Zone 3", TimeZoneId{0x0128U}},              // Europe/Samara
    Mapping{L"Russian Standard Time", TimeZoneId{0x0123U}},           // Europe/Moscow
    Mapping{L"SA Eastern Standard Time", TimeZoneId{0x0030U}},        // America/Cayenne
    Mapping{L"SA Pacific Standard Time", TimeZoneId{0x002aU}},        // America/Bogota
    Mapping{L"SA Western Standard Time", TimeZoneId{0x0058U}},        // America/La_Paz
    Mapping{L"SE Asia Standard Time", TimeZoneId{0x009eU}},           // Asia/Bangkok
    Mapping{L"Saint Pierre Standard Time", TimeZoneId{0x0065U}},      // America/Miquelon
    Mapping{L"Sakhalin Standard Time", TimeZoneId{0x00caU}},          // Asia/Sakhalin
    Mapping{L"Samoa Standard Time", TimeZoneId{0x0137U}},             // Pacific/Apia
    Mapping{L"Sao Tome Standard Time", TimeZoneId{0x0010U}},          // Africa/Sao_Tome
    Mapping{L"Saratov Standard Time", TimeZoneId{0x0129U}},           // Europe/Saratov
    Mapping{L"Singapore Standard Time", TimeZoneId{0x00ceU}},         // Asia/Singapore
    Mapping{L"South Africa Standard Time", TimeZoneId{0x0008U}},      // Africa/Johannesburg
    Mapping{L"South Sudan Standard Time", TimeZoneId{0x0009U}},       // Africa/Juba
    Mapping{L"Sri Lanka Standard Time", TimeZoneId{0x00a3U}},         // Asia/Colombo
    Mapping{L"Sudan Standard Time", TimeZoneId{0x000aU}},             // Africa/Khartoum
    Mapping{L"Syria Standard Time", TimeZoneId{0x00a4U}},             // Asia/Damascus
    Mapping{L"Taipei Standard Time", TimeZoneId{0x00d0U}},            // Asia/Taipei
    Mapping{L"Tasmania Standard Time", TimeZoneId{0x00ecU}},          // Australia/Hobart
    Mapping{L"Tocantins Standard Time", TimeZoneId{0x0016U}},         // America/Araguaina
    Mapping{L"Tokyo Standard Time", TimeZoneId{0x00d5U}},             // Asia/Tokyo
    Mapping{L"Tomsk Standard Time", TimeZoneId{0x00d6U}},             // Asia/Tomsk
    Mapping{L"Tonga Standard Time", TimeZoneId{0x0154U}},             // Pacific/Tongatapu
    Mapping{L"Transbaikal Standard Time", TimeZoneId{0x00a2U}},       // Asia/Chita
    Mapping{L"Turkey Standard Time", TimeZoneId{0x011aU}},            // Europe/Istanbul
    Mapping{L"Turks And Caicos Standard Time", TimeZoneId{0x0043U}},  // America/Grand_Turk
    Mapping{L"US Eastern Standard Time", TimeZoneId{0x004aU}},        // America/Indianapolis
    Mapping{L"US Mountain Standard Time", TimeZoneId{0x0073U}},       // America/Phoenix
    Mapping{L"UTC", TimeZoneId{0x010dU}},                             // Etc/UTC
    Mapping{L"UTC+12", TimeZoneId{0x0102U}},                          // Etc/GMT-12
    Mapping{L"UTC+13", TimeZoneId{0x0103U}},                          // Etc/GMT-13
    Mapping{L"UTC-02", TimeZoneId{0x00f7U}},                          // Etc/GMT+2
    Mapping{L"UTC-08", TimeZoneId{0x00fdU}},                          // Etc/GMT+8
    Mapping{L"UTC-09", TimeZoneId{0x00feU}},                          // Etc/GMT+9
    Mapping{L"UTC-11", TimeZoneId{0x00f5U}},                          // Etc/GMT+11
    Mapping{L"Ulaanbaatar Standard Time", TimeZoneId{0x00d7U}},       // Asia/Ulaanbaatar
    Mapping{L"Venezuela Standard Time", TimeZoneId{0x002fU}},         // America/Caracas
    Mapping{L"Vladivostok Standard Time", TimeZoneId{0x00daU}},       // Asia/Vladivostok
    Mapping{L"Volgograd Standard Time", TimeZoneId{0x0131U}},         // Europe/Volgograd
    Mapping{L"W. Australia Standard Time", TimeZoneId{0x00f0U}},      // Australia/Perth
    Mapping{L"W. Central Africa Standard Time", TimeZoneId{0x000bU}}, // Africa/Lagos
    Mapping{L"W. Europe Standard Time", TimeZoneId{0x0112U}},         // Europe/Berlin
    Mapping{L"W. Mongolia Standard Time", TimeZoneId{0x00aeU}},       // Asia/Hovd
    Mapping{L"West Asia Standard Time", TimeZoneId{0x00d1U}},         // Asia/Tashkent
    Mapping{L"West Bank Standard Time", TimeZoneId{0x00abU}},         // Asia/Hebron
    Mapping{L"West Pacific Standard Time", TimeZoneId{0x0150U}},      // Pacific/Port_Moresby
    Mapping{L"Yakutsk Standard Time", TimeZoneId{0x00dbU}},           // Asia/Yakutsk
    Mapping{L"Yukon Standard Time", TimeZoneId{0x008aU}},             // America/Whitehorse
});
}

auto timeZoneIdFromWindowsName(const std::wstring_view windowsName) noexcept -> std::optional<TimeZoneId> {
    for (const auto &mapping : cMappings) {
        if (mapping.windowsName == windowsName) {
            return mapping.timeZoneId;
        }
    }
    return {};
}

}
