// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_time_zone_data.py" script.

#include "Info.hpp"
#include "ZoneId.hpp"

#include <memory>

namespace erbsland::time::tz::impl {

[[nodiscard]] auto info(ZoneId id) noexcept -> std::unique_ptr<Info>;

}
