// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "generate_unicode_light_data.py" script.

#include "UnicodeData.hpp"

namespace erbsland::text::impl {

auto unicodeDataVersion() noexcept -> unit::Version {
    return unit::Version{17, 0, 0};
}

}
