// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "ByteCompressor.hpp"
#include "ByteDecompressor.hpp"
#include "CompressionAlgorithm.hpp"
#include "CompressionError.hpp"
#include "CompressionErrorContext.hpp"
#include "CompressionErrorReason.hpp"
#include "CompressionFallbackPolicy.hpp"
#include "CompressionFormat.hpp"
#include "CompressionLevel.hpp"
#include "CompressionOptions.hpp"
#include "CompressionPhase.hpp"
#include "CompressionProgress.hpp"
#include "CompressionProgressAction.hpp"
#include "CompressionTransferOptions.hpp"
#include "CompressionTransferResult.hpp"
#include "DecompressionOptions.hpp"


