// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "U32Format.hpp"
#include "U32String.hpp"
#include "U32StringCIHashMap.hpp"
#include "U32StringCIHashSet.hpp"
#include "U32StringCIMap.hpp"
#include "U32StringCISet.hpp"
#include "U32StringConstIterator.hpp"
#include "U32StringHashMap.hpp"
#include "U32StringHashSet.hpp"
#include "U32StringList.hpp"
#include "U32StringLiteral.hpp"
#include "U32StringMap.hpp"
#include "U32StringSet.hpp"
#include "U32StringView.hpp"
#include "U32StringViewList.hpp"


