# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(ApplicationParts)
add_subdirectory(CommandApplication)
add_subdirectory(EventApplication)
add_subdirectory(FunctionApplication)
add_subdirectory(ProceduralApplication)
add_subdirectory(ServiceLifecycle)
