# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(ApplicationRegistration)
add_subdirectory(ManualParsing)
add_subdirectory(DefiningOptions)
add_subdirectory(OptionSets)
add_subdirectory(OptionModules)
add_subdirectory(OptionValues)
add_subdirectory(HelpDocuments)
add_subdirectory(HelpGlobalArguments)
add_subdirectory(HelpOptionSets)
add_subdirectory(HelpModuleShowcase)
add_subdirectory(OptionHelpDetails)
add_subdirectory(OptionSetCallbacks)
add_subdirectory(OptionModuleCallbacks)
add_subdirectory(OptionValueAccess)
add_subdirectory(HelpCustomization)
