# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(BitReader)
add_subdirectory(Byte)
add_subdirectory(ByteArray)
add_subdirectory(ByteBlock)
add_subdirectory(ByteBuffer)
add_subdirectory(ByteIntegerFormat)
add_subdirectory(ByteSpan)
add_subdirectory(ByteStreams)
add_subdirectory(ByteTextOptions)
add_subdirectory(RingBuffer)
add_subdirectory(SecureErase)
add_subdirectory(SharedData)
add_subdirectory(UnsafePointers)
