# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(AccessChecks)
add_subdirectory(ConfigurationDocuments)
add_subdirectory(ConfigurationSignatures)
add_subdirectory(IndividualValues)
add_subdirectory(Placeholders)
add_subdirectory(SourceResolving)
add_subdirectory(ValidatedDocuments)
add_subdirectory(ValidationRules)
add_subdirectory(ValueTrees)
