# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(CalendarDelta)
add_subdirectory(CalendarParts)
add_subdirectory(Date)
add_subdirectory(DateTime)
add_subdirectory(Duration)
add_subdirectory(ElapsedTimer)
add_subdirectory(IsoTimeOutput)
add_subdirectory(Time)
add_subdirectory(TimeAmounts)
add_subdirectory(TimeDelta)
add_subdirectory(TimeDeltaOutput)
add_subdirectory(TimeLiterals)
add_subdirectory(TimePoint)
add_subdirectory(Timestamp)
add_subdirectory(TimeWithZone)
add_subdirectory(TimeZone)
