// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "AuthenticationTokenPair.hpp"
#include "ClientAuthenticationToken.hpp"
#include "PendingAuthenticationChallenge.hpp"
#include "ServerAuthenticationToken.hpp"


