# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(aes)
add_subdirectory(authentication)
add_subdirectory(comparison)
add_subdirectory(control)
add_subdirectory(ecdsa)
add_subdirectory(ed25519)
add_subdirectory(ghash)
add_subdirectory(hash)
add_subdirectory(password)
add_subdirectory(rsa)
add_subdirectory(stream)
add_subdirectory(tls)
add_subdirectory(validation)
add_subdirectory(x25519)
