// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "AnyIntegerTypes.hpp"
#include "BoundedInteger.hpp"
#include "ConstexprSaturatingMath.hpp"
#include "IntegerConversion.hpp"
#include "IntegerMath.hpp"
#include "IntegerRange.hpp"
#include "IntegerTraits.hpp"
#include "IntegerTypes.hpp"
#include "SaturatingInteger.hpp"
#include "SaturatingIntegerTypes.hpp"
#include "SaturatingMath.hpp"
#include "SignedMagnitude.hpp"


