// Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

#include <erbsland/core/Application.hpp>
#include <erbsland/mem/ByteBlock.hpp>
#include <erbsland/path/Path.hpp>
#include <erbsland/text/AnyStringBuilder_fwd.hpp>
#include <erbsland/text/String.hpp>

namespace erbsland::resource::compiler {

/// Generates one data source and one descriptor source for a compiled resource.
/// @notest{Covered by the compiled-resource CMake integration tests.}
class ResourceCompiler final : public core::Application {
public:
    /// The supported generator protocol version.
    static constexpr int cProtocolVersion = 2;

public:
    /// Create a resource compiler from command-line arguments.
    ResourceCompiler(int argc, char *argv[]) : Application{argc, argv} {}
    /// Create a resource compiler from wide command-line arguments.
    ResourceCompiler(int argc, wchar_t *argv[]) : Application{argc, argv} {}

    // defaults/deletions
    ~ResourceCompiler() override = default;
    ResourceCompiler(const ResourceCompiler &) = delete;
    auto operator=(const ResourceCompiler &) -> ResourceCompiler & = delete;

protected: // implement core::Application
    void initialize() override;
    void registerCommandLineOptions(const options::OptionsPtr &options) override;
    [[nodiscard]] auto main() -> unit::ExitCode override;

private:
    /// Generate both resource source files.
    void compileResource();
    /// Read the input file.
    [[nodiscard]] auto readInput() const -> mem::ByteBlock;
    /// Create the data translation unit.
    [[nodiscard]] auto createDataSource(const mem::ByteBlock &storedData) const -> text::String;
    /// Create the descriptor translation unit.
    [[nodiscard]] auto createDescriptorSource(const mem::ByteBlock &infoBlock) const -> text::String;
    /// Create the versioned metadata block kept separate from the resource data.
    [[nodiscard]] auto createInfoBlock(
        unit::ByteLength originalSize, unit::ByteLength storedSize, bool compressed, const mem::ByteBlock &hash) const
        -> mem::ByteBlock;
    /// Append a sequence of C++ byte initializers.
    static void appendByteInitializers(text::AnyStringBuilder &output, const mem::ByteBlock &bytes, bool addSentinel);
    /// Rewrite a generated file only when its content changed.
    static void writeIfChanged(const path::Path &path, const text::String &content);
    /// Read parsed command-line values into the compiler state.
    void readCommandLine();

private:
    path::Path _inputPath;            ///< Input resource path.
    path::Path _dataOutputPath;       ///< Generated byte-array source path.
    path::Path _descriptorOutputPath; ///< Generated descriptor source path.
    text::String _identifier;         ///< Portable resource identifier.
    text::String _resourcePath;       ///< Normalized relative resource path.
    text::String _symbol;             ///< Stable strong-link symbol suffix.
    bool _hashEnabled{true};          ///< Generate a SHA3-256 digest.
    bool _compressionEnabled{true};   ///< Test raw LZ4 compression.
};

}
