// Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#include "ResourceCompiler.hpp"

#include <erbsland/core/ApplicationError.hpp>
#include <erbsland/cryptology/Hasher.hpp>
#include <erbsland/mem/ByteBlockEditor.hpp>
#include <erbsland/mem/ByteCompressor.hpp>
#include <erbsland/mem/ByteWriter.hpp>
#include <erbsland/options/OptionEditor.hpp>
#include <erbsland/options/OptionParserFlag.hpp>
#include <erbsland/options/Options.hpp>
#include <erbsland/options/OptionType.hpp>
#include <erbsland/options/OptionValues.hpp>
#include <erbsland/path/PathContent.hpp>
#include <erbsland/path/PathCreateMode.hpp>
#include <erbsland/path/PathReadDataOptions.hpp>
#include <erbsland/path/PathReadTextOptions.hpp>
#include <erbsland/path/PathWriteTextOptions.hpp>
#include <erbsland/text/AnyStringBuilder.hpp>
#include <erbsland/text/ByteFormat.hpp>
#include <erbsland/text/ByteFormatFlag.hpp>
#include <erbsland/text/Literals.hpp>
#include <erbsland/text/StringBomMode.hpp>
#include <erbsland/text/StringEncoder.hpp>
#include <erbsland/text/StringEncoding.hpp>
#include <erbsland/unit/Version.hpp>

#include <cstdint>
#include <limits>

namespace erbsland::resource::compiler {

using namespace text::literals;

void ResourceCompiler::initialize() {
    info().setApplicationName("Erbsland Core Resource Compiler"_el);
    info().setApplicationVersion(unit::Version{1, 0, 0});
}

void ResourceCompiler::registerCommandLineOptions(const options::OptionsPtr &options) {
    options->setHelpTitle("Erbsland Core Resource Compiler"_el);
    options->setHelpDescription("Generates C++ translation units for one compiled resource."_el);
    options->setParserFlag(options::OptionParserFlag::DisableVersion);
    options->addOption({"--protocol"_el, "protocol"_el})
        .setType(options::OptionType::Integer)
        .setRequired()
        .setValueName("version"_el)
        .setHelpDescription("Generator protocol version."_el);
    options->addOption({"--input"_el, "input"_el})
        .setType(options::OptionType::Text)
        .setRequired()
        .setValueName("path"_el)
        .setHelpDescription("Input resource file."_el);
    options->addOption({"--data-output"_el, "data-output"_el})
        .setType(options::OptionType::Text)
        .setRequired()
        .setValueName("path"_el)
        .setHelpDescription("Generated byte-array source."_el);
    options->addOption({"--descriptor-output"_el, "descriptor-output"_el})
        .setType(options::OptionType::Text)
        .setRequired()
        .setValueName("path"_el)
        .setHelpDescription("Generated descriptor source."_el);
    options->addOption({"--identifier"_el, "identifier"_el})
        .setType(options::OptionType::Text)
        .setRequired()
        .setHelpDescription("Portable resource identifier."_el);
    options->addOption({"--resource-path"_el, "resource-path"_el})
        .setType(options::OptionType::Text)
        .setRequired()
        .setValueName("path"_el)
        .setHelpDescription("Normalized relative resource path."_el);
    options->addOption({"--symbol"_el, "symbol"_el})
        .setType(options::OptionType::Text)
        .setRequired()
        .setHelpDescription("Stable generated link-symbol suffix."_el);
    options->addOption({"--no-hash"_el, "no-hash"_el})
        .setType(options::OptionType::Flag)
        .setHelpDescription("Do not generate a SHA3-256 digest."_el);
    options->addOption({"--no-compression"_el, "no-compression"_el})
        .setType(options::OptionType::Flag)
        .setHelpDescription("Embed the original bytes without compression."_el);
}

auto ResourceCompiler::main() -> unit::ExitCode {
    readCommandLine();
    compileResource();
    return unit::ExitCode::success();
}

void ResourceCompiler::compileResource() {
    const auto input = readInput();
    auto stored = input;
    auto compressed = false;
    if (_compressionEnabled && !input.isEmpty()) {
        const auto candidate = mem::ByteCompressor{mem::ByteCompressionAlgorithm::Lz4Block}.compress(input);
        if (candidate.length().toSizeT() * 100U <= input.length().toSizeT() * 80U) {
            stored = candidate;
            compressed = true;
        }
    }
    auto hash = mem::ByteBlock{};
    if (_hashEnabled) {
        auto hasher = cryptology::Hasher{cryptology::HashAlgorithm::Sha3_256};
        hasher.update(input);
        hash = hasher.finalize();
    }
    writeIfChanged(_dataOutputPath, createDataSource(stored));
    const auto infoBlock = createInfoBlock(input.length(), stored.length(), compressed, hash);
    writeIfChanged(_descriptorOutputPath, createDescriptorSource(infoBlock));
}

auto ResourceCompiler::readInput() const -> mem::ByteBlock {
    auto readOptions = path::PathReadDataOptions{};
    readOptions.setMaximumByteLength(unit::ByteLength{1024U * 1024U});
    return _inputPath.content().readDataOrThrow(readOptions);
}

auto ResourceCompiler::createDataSource(const mem::ByteBlock &storedData) const -> text::String {
    auto output = text::AnyStringBuilder::u8();
    output.append("// Generated by erbsland-core-resource-compiler.\n"_el)
        .append("#include <cstdint>\n"_el)
        .append("#include <span>\n\n"_el)
        .append("auto erbsland_resource_data_"_el)
        .append(_symbol)
        .append("() noexcept -> std::span<const std::uint8_t> {\n"_el)
        .append("    static constexpr std::uint8_t data[] = {\n"_el);
    appendByteInitializers(output, storedData, true);
    output.append("    };\n"_el)
        .append("    return {data, "_el)
        .appendInteger(storedData.length().toRawValue())
        .append("U};\n"_el)
        .append("}\n"_el);
    return output.takeString();
}

auto ResourceCompiler::createDescriptorSource(const mem::ByteBlock &infoBlock) const -> text::String {
    auto output = text::AnyStringBuilder::u8();
    output.append("// Generated by erbsland-core-resource-compiler.\n"_el)
        .append("#include <erbsland/resource/ResourceStorageRegistration.hpp>\n\n"_el)
        .append("#include <cstdint>\n"_el)
        .append("#include <span>\n\n"_el)
        .append("auto erbsland_resource_data_"_el)
        .append(_symbol)
        .append("() noexcept -> std::span<const std::uint8_t>;\n\n"_el)
        .append("namespace erbsland_generated_resource_"_el)
        .append(_symbol)
        .append(" {\n\n"_el)
        .append("constexpr std::uint8_t cInfo[] = {\n"_el);
    appendByteInitializers(output, infoBlock, false);
    output.append("};\n\n"_el)
        .append("const auto cRegistration = erbsland::resource::impl::ResourceStorageRegistration{\n"_el)
        .append("    erbsland_resource_data_"_el)
        .append(_symbol)
        .append(", std::span<const std::uint8_t>{cInfo}};\n\n"_el)
        .append("}\n"_el);
    return output.takeString();
}

auto ResourceCompiler::createInfoBlock(
    const unit::ByteLength originalSize,
    const unit::ByteLength storedSize,
    const bool compressed,
    const mem::ByteBlock &hash) const -> mem::ByteBlock {
    const auto identifierBytes =
        text::StringEncoder{_identifier}.encode(text::StringEncoding::Utf8, text::StringBomMode::Reject);
    const auto pathBytes =
        text::StringEncoder{_resourcePath}.encode(text::StringEncoding::Utf8, text::StringBomMode::Reject);
    if (identifierBytes.length().toRawValue() > std::numeric_limits<std::uint32_t>::max() ||
        pathBytes.length().toRawValue() > std::numeric_limits<std::uint32_t>::max() ||
        hash.length().toRawValue() > std::numeric_limits<std::uint16_t>::max()) {
        throw core::ApplicationError{"Compiled resource metadata exceeds its storage format."_el};
    }
    auto writer = mem::ByteWriter{};
    writer.writeByte(mem::Byte::fromChar('E'))
        .writeByte(mem::Byte::fromChar('L'))
        .writeByte(mem::Byte::fromChar('R'))
        .writeByte(mem::Byte::fromChar('I'))
        .writeUInt8(1U)
        .writeUInt8(compressed ? std::uint8_t{1U} : std::uint8_t{0U})
        .writeUInt8(hash.isEmpty() ? 0U : 1U)
        .writeUInt8(0U)
        .writeUInt64(originalSize.toRawValue())
        .writeUInt64(storedSize.toRawValue())
        .writeUInt32(static_cast<std::uint32_t>(identifierBytes.length().toRawValue()))
        .writeUInt32(static_cast<std::uint32_t>(pathBytes.length().toRawValue()))
        .writeUInt16(static_cast<std::uint16_t>(hash.length().toRawValue()))
        .writeUInt16(0U)
        .writeBytes(identifierBytes)
        .writeBytes(pathBytes)
        .writeBytes(hash);
    return writer.toByteBlock();
}

void ResourceCompiler::appendByteInitializers(
    text::AnyStringBuilder &output, const mem::ByteBlock &bytes, const bool addSentinel) {
    auto values = mem::ByteBlockEditor{bytes};
    if (addSentinel) {
        values.append(mem::Byte{});
    }
    const auto format = text::ByteFormat{text::ByteFormatFlag::Separator | text::ByteFormatFlag::Lines}
                            .setBytesPerLine(unit::ByteLength{16U})
                            .setByteSeparator(", 0x"_el)
                            .setLinePrefix("    0x"_el)
                            .setLineSuffix(",\n"_el);
    output.appendByteBlock(values, format);
}

void ResourceCompiler::writeIfChanged(const path::Path &path, const text::String &content) {
    auto readOptions = path::PathReadTextOptions{};
    readOptions.setMaximumByteLength(unit::ByteLength::infinite());
    if (const auto existing = path.content().readText(readOptions); existing.has_value() && *existing == content) {
        return;
    }
    auto writeOptions = path::PathWriteTextOptions{text::StringEncoding::Utf8};
    writeOptions.setBomMode(text::StringBomMode::Reject).setCreationMode(path::PathCreateMode::CreateOrOverwrite);
    path.content().writeTextOrThrow(content, writeOptions);
}

void ResourceCompiler::readCommandLine() {
    const auto values = optionValues();
    if (values->getInteger("protocol"_el) != cProtocolVersion) {
        throw core::ApplicationError{"Unsupported resource compiler protocol version."_el};
    }
    _inputPath = path::Path{values->getText("input"_el)};
    _dataOutputPath = path::Path{values->getText("data-output"_el)};
    _descriptorOutputPath = path::Path{values->getText("descriptor-output"_el)};
    _identifier = values->getText("identifier"_el);
    _resourcePath = values->getText("resource-path"_el);
    _symbol = values->getText("symbol"_el);
    _hashEnabled = !values->getFlag("no-hash"_el);
    _compressionEnabled = !values->getFlag("no-compression"_el);
}

}
