// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "ResourceError.hpp"
#include "ResourceErrorCategory.hpp"
#include "ResourceInfo.hpp"
#include "ResourceManager.hpp"
#include "Resources.hpp"


