// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "Application.hpp"
#include "ApplicationError.hpp"
#include "ApplicationErrorContext.hpp"
#include "ApplicationInfo.hpp"
#include "ApplicationPart.hpp"
#include "ApplicationPartCallback.hpp"
#include "ApplicationPartCommandLine.hpp"
#include "ApplicationPartErrorAction.hpp"
#include "ApplicationPartIdentifier.hpp"
#include "ApplicationPartManager.hpp"
#include "ApplicationPartManagerAccess.hpp"
#include "ApplicationPartManagerState.hpp"
#include "ApplicationPartState.hpp"
#include "ApplicationPartTraits.hpp"
#include "ApplicationPartWithInterface.hpp"
#include "CommandLineArguments.hpp"
#include "Definitions.hpp"
#include "InitializeFn.hpp"
#include "LastErrorDumpMode.hpp"
#include "MainFn.hpp"
#include "MakeOneNamespace.hpp"
#include "Namespaces.hpp"


