# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from dev.update_includes import UpdateIncludesApp
from lib.error import UtilityError


class TestUpdateIncludesApp(UpdateIncludesApp):
    """Update-includes app bound to an isolated project directory."""

    def __init__(self, project_dir: Path) -> None:
        super().__init__()
        self._project_dir = project_dir

    @property
    def project_directory(self) -> Path:
        """Use the temporary test project as the project root."""
        return self._project_dir

    def config_file_path(self) -> Path:
        """Use the production update-includes configuration."""
        return Path(__file__).resolve().parents[1] / "conf" / "update_includes.elcl"


class UpdateIncludesTest(unittest.TestCase):
    """Tests for generated include and all-header updates."""

    def setUp(self) -> None:
        self.temp_dir = tempfile.TemporaryDirectory(dir="/private/tmp")
        self.project_dir = Path(self.temp_dir.name)
        (self.project_dir / "src" / "erbsland").mkdir(parents=True)
        (self.project_dir / "include" / "erbsland").mkdir(parents=True)

    def tearDown(self) -> None:
        self.temp_dir.cleanup()

    def write_header(self, relative_path: str, text: str) -> None:
        """Write a header below the temporary source root."""
        path = self.project_dir / "src" / "erbsland" / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")

    def run_update_includes(self) -> None:
        """Run the update-includes utility in the temporary project."""
        app = TestUpdateIncludesApp(self.project_dir)
        app.run([])

    def create_manual_app(self) -> TestUpdateIncludesApp:
        """Create an update-includes app with manually configured test settings."""
        app = TestUpdateIncludesApp(self.project_dir)
        app.project_dir = self.project_dir
        app.src_dir = self.project_dir / "src" / "erbsland"
        app.include_dir = self.project_dir / "include" / "erbsland"
        app.generated_header = "#pragma once\n// generated"
        app.generated_include_header = "#pragma once\n// generated"
        app.exclude_dirs = []
        app.exclude_headers = set()
        app.exclude_from_all_headers = set()
        app.exclude_from_parent_folding = set()
        app.create_all_base_dir = ""
        return app

    def test_legacy_fwd_entry_marker_is_ignored(self) -> None:
        self.write_header(
            "sample/Widget.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once

namespace erbsland::sample {

class Widget { // fwd-entry: class Widget
};

}
""",
        )

        self.run_update_includes()

        sample_all = self.project_dir / "src" / "erbsland" / "sample" / "all.hpp"
        self.assertTrue(sample_all.is_file())
        sample_all_text = sample_all.read_text(encoding="utf-8")
        self.assertIn('#include "Widget.hpp"', sample_all_text)
        self.assertNotIn("class Widget;", sample_all_text)
        self.assertFalse((self.project_dir / "src" / "erbsland" / "sample" / "fwd.hpp").exists())
        wrapper_path = self.project_dir / "include" / "erbsland" / "sample" / "Widget.hpp"
        self.assertTrue(wrapper_path.is_file())
        wrapper_text = wrapper_path.read_text(encoding="utf-8")
        self.assertEqual(
            "\n".join(
                [
                    "#pragma once",
                    "// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!",
                    '// This file was generated by the "update_includes.py" script.',
                    '#include "../../../src/erbsland/sample/Widget.hpp"',
                    "",
                ]
            ),
            wrapper_text,
        )
        self.assertTrue((self.project_dir / "include" / "erbsland" / "sample" / "all.hpp").is_file())
        self.assertTrue((self.project_dir / "include" / "erbsland" / "all_sample.hpp").is_file())

    def test_source_fwd_header_is_skipped(self) -> None:
        self.write_header(
            "sample/Widget.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once

namespace erbsland::sample {

class Widget {};

}
""",
        )
        original_fwd_text = """// Hand-written source forward declarations.
#pragma once
"""
        self.write_header("sample/fwd.hpp", original_fwd_text)
        stale_wrapper = self.project_dir / "include" / "erbsland" / "sample" / "fwd.hpp"
        stale_wrapper.parent.mkdir(parents=True, exist_ok=True)
        stale_wrapper.write_text("stale\n", encoding="utf-8")

        self.run_update_includes()

        sample_all_text = (self.project_dir / "src" / "erbsland" / "sample" / "all.hpp").read_text(encoding="utf-8")
        self.assertIn('#include "Widget.hpp"', sample_all_text)
        self.assertNotIn("fwd.hpp", sample_all_text)
        self.assertEqual(
            original_fwd_text,
            (self.project_dir / "src" / "erbsland" / "sample" / "fwd.hpp").read_text(encoding="utf-8"),
        )
        self.assertFalse(stale_wrapper.exists())

    def test_fwd_named_headers_are_not_published(self) -> None:
        self.write_header(
            "math/Widget.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once

namespace erbsland::math {

class Widget {};

}
""",
        )
        self.write_header(
            "math/Widget_fwd.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once

namespace erbsland::math {

class Widget;

}
""",
        )

        self.run_update_includes()

        math_all_text = (self.project_dir / "src" / "erbsland" / "math" / "all.hpp").read_text(encoding="utf-8")
        root_all_text = (self.project_dir / "src" / "erbsland" / "all.hpp").read_text(encoding="utf-8")
        self.assertIn('#include "Widget.hpp"', math_all_text)
        self.assertNotIn("Widget_fwd.hpp", math_all_text)
        self.assertIn('#include "math/Widget.hpp"', root_all_text)
        self.assertNotIn("Widget_fwd.hpp", root_all_text)
        self.assertTrue((self.project_dir / "include" / "erbsland" / "math" / "Widget.hpp").is_file())
        self.assertFalse((self.project_dir / "include" / "erbsland" / "math" / "Widget_fwd.hpp").exists())

    def test_underscored_part_headers_are_not_published(self) -> None:
        self.write_header(
            "math/Widget.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once

#include "Widget_part.hpp"

namespace erbsland::math {

class Widget {};

}
""",
        )
        self.write_header(
            "math/Widget_part.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once

namespace erbsland::math::detail {

class WidgetPart {};

}
""",
        )
        stale_wrapper = self.project_dir / "include" / "erbsland" / "math" / "Widget_part.hpp"
        stale_wrapper.parent.mkdir(parents=True, exist_ok=True)
        stale_wrapper.write_text("stale\n", encoding="utf-8")

        self.run_update_includes()

        math_all_text = (self.project_dir / "src" / "erbsland" / "math" / "all.hpp").read_text(encoding="utf-8")
        self.assertIn('#include "Widget.hpp"', math_all_text)
        self.assertNotIn("Widget_part.hpp", math_all_text)
        self.assertTrue((self.project_dir / "include" / "erbsland" / "math" / "Widget.hpp").is_file())
        self.assertFalse(stale_wrapper.exists())

    def test_configured_header_is_excluded_from_generated_outputs(self) -> None:
        self.write_header(
            "system/PlatformError.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once

namespace erbsland::system {

class PlatformError {};

}
""",
        )
        self.write_header(
            "system/WindowsErrorContext.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once

namespace erbsland::system {

class WindowsErrorContext {};

}
""",
        )

        self.run_update_includes()

        system_all_text = (self.project_dir / "src" / "erbsland" / "system" / "all.hpp").read_text(encoding="utf-8")
        self.assertIn('#include "PlatformError.hpp"', system_all_text)
        self.assertNotIn("WindowsErrorContext.hpp", system_all_text)
        self.assertTrue((self.project_dir / "include" / "erbsland" / "system" / "PlatformError.hpp").is_file())
        self.assertFalse((self.project_dir / "include" / "erbsland" / "system" / "WindowsErrorContext.hpp").exists())

    def test_header_can_be_published_but_excluded_from_all_headers(self) -> None:
        self.write_header(
            "text/String.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once
""",
        )
        self.write_header(
            "text/StdFormat.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once
""",
        )
        self.write_header(
            "time/StdFormat.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once
""",
        )
        app = self.create_manual_app()
        app.fold_into_parent = {"text", "time"}
        app.exclude_from_all_headers = {Path("text/StdFormat.hpp"), Path("time/StdFormat.hpp")}

        app.collect_header_files()
        app._create_effective_parent_include_map()
        app.generate_all_headers()
        app.generate_includes()

        text_all_text = (self.project_dir / "src" / "erbsland" / "text" / "all.hpp").read_text(encoding="utf-8")
        time_all_text = (self.project_dir / "src" / "erbsland" / "time" / "all.hpp").read_text(encoding="utf-8")
        root_all_text = (self.project_dir / "src" / "erbsland" / "all.hpp").read_text(encoding="utf-8")
        root_wrapper_text = (self.project_dir / "include" / "erbsland" / "StdFormat.hpp").read_text(encoding="utf-8")
        self.assertIn('#include "String.hpp"', text_all_text)
        self.assertNotIn("StdFormat.hpp", text_all_text)
        self.assertNotIn("StdFormat.hpp", time_all_text)
        self.assertIn('#include "text/String.hpp"', root_all_text)
        self.assertNotIn("StdFormat.hpp", root_all_text)
        self.assertIn("src/erbsland/text/StdFormat.hpp", root_wrapper_text)
        self.assertIn("src/erbsland/time/StdFormat.hpp", root_wrapper_text)
        self.assertTrue((self.project_dir / "include" / "erbsland" / "text" / "StdFormat.hpp").is_file())
        self.assertTrue((self.project_dir / "include" / "erbsland" / "time" / "StdFormat.hpp").is_file())

    def test_duplicate_folded_headers_are_merged_deterministically(self) -> None:
        self.write_header(
            "text/Literals.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once
""",
        )
        self.write_header(
            "time/Literals.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once
""",
        )
        stale_wrapper = self.project_dir / "include" / "erbsland" / "Obsolete.hpp"
        stale_wrapper.write_text("stale\n", encoding="utf-8")

        def run_generator() -> None:
            app = self.create_manual_app()
            app.fold_into_parent = {"text", "time"}
            app.collect_header_files()
            app._create_effective_parent_include_map()
            app.generate_all_headers()
            app.generate_includes()
            app.remove_obsolete_includes()

        run_generator()

        root_all_path = self.project_dir / "src" / "erbsland" / "all.hpp"
        root_wrapper_path = self.project_dir / "include" / "erbsland" / "Literals.hpp"
        root_all_text = root_all_path.read_text(encoding="utf-8")
        root_wrapper_text = root_wrapper_path.read_text(encoding="utf-8")
        self.assertLess(root_all_text.index("text/Literals.hpp"), root_all_text.index("time/Literals.hpp"))
        self.assertLess(
            root_wrapper_text.index("src/erbsland/text/Literals.hpp"),
            root_wrapper_text.index("src/erbsland/time/Literals.hpp"),
        )
        self.assertEqual(root_wrapper_text.count("src/erbsland/text/Literals.hpp"), 1)
        self.assertEqual(root_wrapper_text.count("src/erbsland/time/Literals.hpp"), 1)
        self.assertTrue((self.project_dir / "include" / "erbsland" / "text" / "Literals.hpp").is_file())
        self.assertTrue((self.project_dir / "include" / "erbsland" / "time" / "Literals.hpp").is_file())
        self.assertFalse(stale_wrapper.exists())

        first_root_all_text = root_all_text
        first_root_wrapper_text = root_wrapper_text
        run_generator()
        self.assertEqual(root_all_path.read_text(encoding="utf-8"), first_root_all_text)
        self.assertEqual(root_wrapper_path.read_text(encoding="utf-8"), first_root_wrapper_text)

    def test_header_can_be_excluded_from_parent_folding(self) -> None:
        self.write_header(
            "text/Literals.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once
""",
        )
        self.write_header(
            "time/Literals.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once
""",
        )
        app = self.create_manual_app()
        app.fold_into_parent = {"text", "time"}
        app.exclude_from_parent_folding = {Path("time/Literals.hpp")}

        app.collect_header_files()
        app._create_effective_parent_include_map()
        app.generate_all_headers()
        app.generate_includes()

        text_all_text = (self.project_dir / "src" / "erbsland" / "text" / "all.hpp").read_text(encoding="utf-8")
        time_all_text = (self.project_dir / "src" / "erbsland" / "time" / "all.hpp").read_text(encoding="utf-8")
        root_all_text = (self.project_dir / "src" / "erbsland" / "all.hpp").read_text(encoding="utf-8")
        root_wrapper_text = (self.project_dir / "include" / "erbsland" / "Literals.hpp").read_text(encoding="utf-8")
        self.assertIn('#include "Literals.hpp"', text_all_text)
        self.assertIn('#include "Literals.hpp"', time_all_text)
        self.assertIn('#include "text/Literals.hpp"', root_all_text)
        self.assertNotIn('#include "time/Literals.hpp"', root_all_text)
        self.assertIn("src/erbsland/text/Literals.hpp", root_wrapper_text)
        self.assertTrue((self.project_dir / "include" / "erbsland" / "text" / "Literals.hpp").is_file())
        self.assertTrue((self.project_dir / "include" / "erbsland" / "time" / "Literals.hpp").is_file())

    def test_tpp_headers_are_not_published(self) -> None:
        self.write_header(
            "text/CharSet.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once

#include "CharSet.tpp"

namespace erbsland::text {

class CharSet {};

}
""",
        )
        self.write_header(
            "text/CharSet.tpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once

namespace erbsland::text::detail {

inline constexpr auto charSetPart = 1;

}
""",
        )
        stale_wrapper = self.project_dir / "include" / "erbsland" / "text" / "CharSet.tpp"
        stale_wrapper.parent.mkdir(parents=True, exist_ok=True)
        stale_wrapper.write_text("stale\n", encoding="utf-8")

        self.run_update_includes()

        text_all_text = (self.project_dir / "src" / "erbsland" / "text" / "all.hpp").read_text(encoding="utf-8")
        self.assertIn('#include "CharSet.hpp"', text_all_text)
        self.assertNotIn("CharSet.tpp", text_all_text)
        self.assertTrue((self.project_dir / "include" / "erbsland" / "text" / "CharSet.hpp").is_file())
        self.assertFalse(stale_wrapper.exists())

    def test_equal_header_names_in_separate_directories_are_published(self) -> None:
        self.write_header(
            "alpha/Foo.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once
""",
        )
        self.write_header(
            "beta/Foo.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once
""",
        )

        self.run_update_includes()

        self.assertTrue((self.project_dir / "include" / "erbsland" / "alpha" / "Foo.hpp").is_file())
        self.assertTrue((self.project_dir / "include" / "erbsland" / "beta" / "Foo.hpp").is_file())
        self.assertFalse((self.project_dir / "include" / "erbsland" / "Foo.hpp").exists())

    def test_folded_parent_conflict_is_reported(self) -> None:
        self.write_header(
            "alpha/Foo.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once
""",
        )
        self.write_header(
            "alpha/core/Foo.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once
""",
        )

        with self.assertRaisesRegex(UtilityError, "Folded include path conflict"):
            self.run_update_includes()

    def test_global_include_conflict_is_reported_before_writing_wrappers(self) -> None:
        self.write_header(
            "alpha/Foo.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once
""",
        )
        self.write_header(
            "beta/Foo.hpp",
            """// Copyright (c) 2026 Tobias Erbsland
#pragma once
""",
        )
        app = self.create_manual_app()
        app.create_global_includes = True

        app.collect_header_files()
        app.generate_all_headers()
        with self.assertRaisesRegex(UtilityError, "Generated include path conflict"):
            app.generate_includes()

        self.assertFalse(any((self.project_dir / "include" / "erbsland").rglob("*.hpp")))


if __name__ == "__main__":
    unittest.main()
