# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from lib.copyright import HeaderConfig
from lib.error import UtilityError


class CopyrightTest(unittest.TestCase):
    """Tests for shared generated-file header rendering."""

    @staticmethod
    def config_file_path() -> Path:
        """Get a tool configuration that includes the shared header config."""
        return Path(__file__).resolve().parents[1] / "conf" / "update_includes.elcl"

    def test_hpp_header_places_warning_after_pragma_once(self) -> None:
        header = HeaderConfig.read(self.config_file_path()).source_header(
            "hpp",
            tool="sample.py",
            year=2034,
        )

        self.assertEqual(
            "\n".join(
                [
                    "// Copyright © 2034 Tobias Erbsland - https://erbsland.dev",
                    "// SPDX-License-Identifier: Apache-2.0",
                    "#pragma once",
                    "",
                    "// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!",
                    '// This file was generated by the "sample.py" script.',
                ]
            ),
            header,
        )

    def test_cpp_header_uses_aggressive_warning(self) -> None:
        header = HeaderConfig.read(self.config_file_path()).source_header("cpp", tool="sample.cpp.py", year=2034)

        self.assertEqual(
            "\n".join(
                [
                    "// Copyright © 2034 Tobias Erbsland - https://erbsland.dev",
                    "// SPDX-License-Identifier: Apache-2.0",
                    "",
                    "// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!",
                    '// This file was generated by the "sample.cpp.py" script.',
                ]
            ),
            header,
        )

    def test_py_header_uses_hash_comments(self) -> None:
        header = HeaderConfig.read(self.config_file_path()).source_header("py", tool="sample.py", year=2034)

        self.assertEqual(
            "\n".join(
                [
                    "# Copyright © 2034 Tobias Erbsland - https://erbsland.dev",
                    "# SPDX-License-Identifier: Apache-2.0",
                    "",
                    "# !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!",
                    '# This file was generated by the "sample.py" script.',
                ]
            ),
            header,
        )

    def test_include_header_is_compact(self) -> None:
        header = HeaderConfig.read(self.config_file_path()).source_header("include", tool="sample.py", year=2034)

        self.assertEqual(
            "\n".join(
                [
                    "#pragma once",
                    "// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!",
                    '// This file was generated by the "sample.py" script.',
                ]
            ),
            header,
        )

    def test_validate_requires_placeholders(self) -> None:
        with self.assertRaisesRegex(UtilityError, "hpp_copyright"):
            HeaderConfig(
                hpp_copyright="// Copyright",
                cpp_copyright="// Copyright {year}",
                py_copyright="# Copyright {year}",
                include_copyright="#pragma once",
                cpp_warning="// Generated by {tool}",
                py_warning="# Generated by {tool}",
            ).validate()


if __name__ == "__main__":
    unittest.main()
