# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(block)
add_subdirectory(compression)
add_subdirectory(conf)
add_subdirectory(core)
add_subdirectory(cryptology)
add_subdirectory(cterm)
add_subdirectory(debug)
add_subdirectory(err)
add_subdirectory(event)
add_subdirectory(geometry)
add_subdirectory(i18n)
add_subdirectory(log)
add_subdirectory(math)
add_subdirectory(mem)
add_subdirectory(network)
add_subdirectory(options)
add_subdirectory(path)
add_subdirectory(random)
add_subdirectory(re)
add_subdirectory(resource)
add_subdirectory(stream)
add_subdirectory(system)
add_subdirectory(text)
add_subdirectory(time)
add_subdirectory(unit)
add_subdirectory(util)
