# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(bgeo)
add_subdirectory(core)
add_subdirectory(cterm)
add_subdirectory(debug)
add_subdirectory(err)
add_subdirectory(math)
add_subdirectory(mem)
add_subdirectory(options)
add_subdirectory(random)
add_subdirectory(stream)
add_subdirectory(text)
add_subdirectory(time)
add_subdirectory(unit)
add_subdirectory(util)
