# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(AnyStringBuilder)
add_subdirectory(AnyStringEditor)
add_subdirectory(BaseN)
add_subdirectory(FuzzyMatching)
add_subdirectory(HtmlFragments)
add_subdirectory(JsonValues)
add_subdirectory(NamedKeyParsing)
add_subdirectory(Placeholders)
add_subdirectory(RenderLayouts)
add_subdirectory(ScalarConversion)
add_subdirectory(String)
add_subdirectory(StringBuilding)
add_subdirectory(StringCharReader)
add_subdirectory(StringConverter)
add_subdirectory(StringEditor)
add_subdirectory(StringEncoder)
add_subdirectory(StringFormat)
add_subdirectory(StringLiteral)
add_subdirectory(StringPattern)
add_subdirectory(TextDocument)
