# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(AnyString)
add_subdirectory(String)
add_subdirectory(StringBuilder)
add_subdirectory(StringCharReader)
add_subdirectory(StringCharView)
add_subdirectory(StringConverter)
add_subdirectory(StringEncoder)
add_subdirectory(StringFormat)
add_subdirectory(StringLiteral)
add_subdirectory(StringPattern)
add_subdirectory(StringView)
add_subdirectory(TextDocument)
