// Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0

#include "OperationDescriptor.hpp"

namespace app::charset {

using namespace el::text::literals;

auto operationDescriptors() -> const el::List<OperationDescriptor> & {
    static const auto descriptors = el::List<OperationDescriptor>{
        {Operation::ConstructDefault,
            "construct-default"_el,
            "Default construction and destruction."_el,
            el::StringList{"CharSet::CharSet()"_el, "CharSet::~CharSet()"_el},
            el::StringList{"default"_el}},
        {Operation::ConstructChar,
            "construct-char"_el,
            "Construction from one character."_el,
            el::StringList{"CharSet::CharSet(Char)"_el},
            el::StringList{"ascii"_el, "supplementary"_el, "invalid"_el}},
        {Operation::ConstructU8String,
            "construct-u8-string"_el,
            "Construction from decoded UTF-8 text."_el,
            el::StringList{"CharSet::CharSet(const U8String&)"_el},
            el::StringList{"single"_el, "adjacent"_el, "sparse-ascii"_el, "unicode"_el}},
        {Operation::ConstructSet,
            "construct-set"_el,
            "Construction from an ordered character set."_el,
            el::StringList{"CharSet::CharSet(const util::Set<Char>&)"_el},
            el::StringList{"single"_el, "adjacent"_el, "sparse-ascii"_el, "unicode"_el}},
        {Operation::ConstructList,
            "construct-list"_el,
            "Construction from a character list."_el,
            el::StringList{"CharSet::CharSet(const util::List<Char>&)"_el},
            el::StringList{"single"_el, "adjacent"_el, "sparse-ascii"_el, "unicode"_el}},
        {Operation::ConstructInitializerList,
            "construct-initializer-list"_el,
            "Construction from an initializer list."_el,
            el::StringList{"CharSet::CharSet(initializer_list<Char>)"_el},
            el::StringList{"single"_el, "adjacent"_el, "sparse-ascii"_el, "unicode"_el}},
        {Operation::CopyConstruct,
            "copy-construct"_el,
            "Copy construction with copy-on-write storage."_el,
            el::StringList{"CharSet::CharSet(const CharSet&)"_el},
            el::StringList{"empty"_el, "single"_el, "sparse-ascii"_el, "unicode-category"_el}},
        {Operation::MoveConstruct,
            "move-construct"_el,
            "Move construction while retaining a valid source."_el,
            el::StringList{"CharSet::CharSet(CharSet&&)"_el},
            el::StringList{"empty"_el, "single"_el, "sparse-ascii"_el, "unicode-category"_el}},
        {Operation::CopyAssign,
            "copy-assign"_el,
            "Copy assignment with copy-on-write storage."_el,
            el::StringList{"CharSet::operator=(const CharSet&)"_el},
            el::StringList{"empty"_el, "single"_el, "sparse-ascii"_el, "unicode-category"_el}},
        {Operation::MoveAssign,
            "move-assign"_el,
            "Move assignment while retaining a valid source."_el,
            el::StringList{"CharSet::operator=(CharSet&&)"_el},
            el::StringList{"empty"_el, "single"_el, "sparse-ascii"_el, "unicode-category"_el}},
        {Operation::Equal,
            "equal"_el,
            "Equality comparison."_el,
            el::StringList{"CharSet::operator=="_el},
            el::StringList{"equal-single"_el, "equal-sparse"_el, "different-early"_el, "different-late"_el}},
        {Operation::NotEqual,
            "not-equal"_el,
            "Inequality comparison."_el,
            el::StringList{"CharSet::operator!="_el},
            el::StringList{"equal-single"_el, "equal-sparse"_el, "different-early"_el, "different-late"_el}},
        {Operation::SubsetOperator,
            "subset-operator"_el,
            "Subset comparison operator."_el,
            el::StringList{"CharSet::operator<="_el},
            el::StringList{"subset"_el, "equal"_el, "overlap"_el, "disjoint"_el}},
        {Operation::SupersetOperator,
            "superset-operator"_el,
            "Superset comparison operator."_el,
            el::StringList{"CharSet::operator>="_el},
            el::StringList{"subset"_el, "equal"_el, "overlap"_el, "disjoint"_el}},
        {Operation::IsEmpty,
            "is-empty"_el,
            "Empty-set test."_el,
            el::StringList{"CharSet::isEmpty"_el},
            el::StringList{"empty"_el, "single"_el, "unicode-category"_el}},
        {Operation::Contains,
            "contains"_el,
            "Character membership test."_el,
            el::StringList{"CharSet::contains"_el},
            el::StringList{
                "single-hit"_el,
                "single-miss"_el,
                "range-hit"_el,
                "range-miss"_el,
                "sparse-first"_el,
                "sparse-last"_el,
                "sparse-miss"_el,
                "unicode-hit"_el,
                "unicode-miss"_el}},
        {Operation::IsSubset,
            "is-subset"_el,
            "Subset test."_el,
            el::StringList{"CharSet::isSubsetOf"_el},
            el::StringList{"subset"_el, "equal"_el, "overlap"_el, "disjoint"_el}},
        {Operation::IsSuperset,
            "is-superset"_el,
            "Superset test."_el,
            el::StringList{"CharSet::isSupersetOf"_el},
            el::StringList{"subset"_el, "equal"_el, "overlap"_el, "disjoint"_el}},
        {Operation::IsEqualCi,
            "is-equal-ci"_el,
            "Case-insensitive equality test."_el,
            el::StringList{"CharSet::isEqualToCI"_el},
            el::StringList{"ascii-equal"_el, "ascii-folded"_el, "unicode-folded"_el, "different"_el}},
        {Operation::IsSubsetCi,
            "is-subset-ci"_el,
            "Case-insensitive subset test."_el,
            el::StringList{"CharSet::isSubsetOfCI"_el},
            el::StringList{"ascii-subset"_el, "ascii-folded"_el, "unicode-folded"_el, "different"_el}},
        {Operation::ContainsCaseFoldable,
            "contains-case-foldable"_el,
            "Case-folding metadata test."_el,
            el::StringList{"CharSet::containsCaseFoldableCharacters"_el},
            el::StringList{"single-false"_el, "single-true"_el, "sparse-late"_el, "unicode-category"_el}},
        {Operation::ContainsLowercaseMappable,
            "contains-lowercase-mappable"_el,
            "Lowercase-mapping metadata test."_el,
            el::StringList{"CharSet::containsLowercaseMappableCharacters"_el},
            el::StringList{"single-false"_el, "single-true"_el, "sparse-late"_el, "unicode-category"_el}},
        {Operation::ContainsUppercaseMappable,
            "contains-uppercase-mappable"_el,
            "Uppercase-mapping metadata test."_el,
            el::StringList{"CharSet::containsUppercaseMappableCharacters"_el},
            el::StringList{"single-false"_el, "single-true"_el, "sparse-late"_el, "unicode-category"_el}},
        {Operation::UnitedWith,
            "united-with"_el,
            "Set union method."_el,
            el::StringList{"CharSet::unitedWith"_el},
            el::StringList{"merge"_el, "overlap"_el, "disjoint"_el, "unicode"_el}},
        {Operation::IntersectedWith,
            "intersected-with"_el,
            "Set intersection method."_el,
            el::StringList{"CharSet::intersectedWith"_el},
            el::StringList{"overlap"_el, "equal"_el, "disjoint"_el, "unicode"_el}},
        {Operation::SubtractedBy,
            "subtracted-by"_el,
            "Set subtraction method."_el,
            el::StringList{"CharSet::subtractedBy"_el},
            el::StringList{"split"_el, "overlap"_el, "disjoint"_el, "unicode"_el}},
        {Operation::SymmetricDifferenceWith,
            "symmetric-difference-with"_el,
            "Symmetric-difference method."_el,
            el::StringList{"CharSet::symmetricDifferenceWith"_el},
            el::StringList{"overlap"_el, "equal"_el, "disjoint"_el, "unicode"_el}},
        {Operation::UnionOperator,
            "union-operator"_el,
            "Set union operator."_el,
            el::StringList{"CharSet::operator|"_el},
            el::StringList{"merge"_el, "overlap"_el, "disjoint"_el}},
        {Operation::IntersectionOperator,
            "intersection-operator"_el,
            "Set intersection operator."_el,
            el::StringList{"CharSet::operator&"_el},
            el::StringList{"overlap"_el, "equal"_el, "disjoint"_el}},
        {Operation::SubtractionOperator,
            "subtraction-operator"_el,
            "Set subtraction operator."_el,
            el::StringList{"CharSet::operator-"_el},
            el::StringList{"split"_el, "overlap"_el, "disjoint"_el}},
        {Operation::SymmetricDifferenceOperator,
            "symmetric-difference-operator"_el,
            "Symmetric-difference operator."_el,
            el::StringList{"CharSet::operator^"_el},
            el::StringList{"overlap"_el, "equal"_el, "disjoint"_el}},
        {Operation::UnionAssign,
            "union-assign"_el,
            "Compound set union."_el,
            el::StringList{"CharSet::operator|="_el},
            el::StringList{"merge"_el, "overlap"_el, "disjoint"_el}},
        {Operation::IntersectionAssign,
            "intersection-assign"_el,
            "Compound set intersection."_el,
            el::StringList{"CharSet::operator&="_el},
            el::StringList{"overlap"_el, "equal"_el, "disjoint"_el}},
        {Operation::SubtractionAssign,
            "subtraction-assign"_el,
            "Compound set subtraction."_el,
            el::StringList{"CharSet::operator-="_el},
            el::StringList{"split"_el, "overlap"_el, "disjoint"_el}},
        {Operation::SymmetricDifferenceAssign,
            "symmetric-difference-assign"_el,
            "Compound symmetric difference."_el,
            el::StringList{"CharSet::operator^="_el},
            el::StringList{"overlap"_el, "equal"_el, "disjoint"_el}},
        {Operation::AddSet,
            "add-set"_el,
            "Add another set to a copied source."_el,
            el::StringList{"CharSet::add(const CharSet&)"_el},
            el::StringList{"merge"_el, "overlap"_el, "disjoint"_el, "empty"_el}},
        {Operation::AddRange,
            "add-range"_el,
            "Add one range to a copied source."_el,
            el::StringList{"CharSet::add(CharRange)"_el},
            el::StringList{"merge"_el, "overlap"_el, "disjoint"_el, "empty"_el}},
        {Operation::AddChar,
            "add-char"_el,
            "Add one character to a copied source."_el,
            el::StringList{"CharSet::add(Char)"_el},
            el::StringList{"merge"_el, "existing"_el, "disjoint"_el, "invalid"_el}},
        {Operation::RemoveSet,
            "remove-set"_el,
            "Remove another set from a copied source."_el,
            el::StringList{"CharSet::remove(const CharSet&)"_el},
            el::StringList{"split"_el, "overlap"_el, "disjoint"_el, "empty"_el}},
        {Operation::RemoveRange,
            "remove-range"_el,
            "Remove one range from a copied source."_el,
            el::StringList{"CharSet::remove(CharRange)"_el},
            el::StringList{"split"_el, "overlap"_el, "disjoint"_el, "empty"_el}},
        {Operation::RemoveChar,
            "remove-char"_el,
            "Remove one character from a copied source."_el,
            el::StringList{"CharSet::remove(Char)"_el},
            el::StringList{"split"_el, "edge"_el, "disjoint"_el, "invalid"_el}},
        {Operation::ForEachRange,
            "for-each-range"_el,
            "Iterate normalized ranges."_el,
            el::StringList{"CharSet::forEach(CharRange)"_el},
            el::StringList{"empty"_el, "single"_el, "sparse-ascii"_el, "unicode-category"_el}},
        {Operation::ForEachChar,
            "for-each-char"_el,
            "Iterate Unicode scalar values."_el,
            el::StringList{"CharSet::forEach(Char)"_el},
            el::StringList{"empty"_el, "single"_el, "range"_el, "sparse-ascii"_el, "unicode-small"_el}},
        {Operation::Transform,
            "transform"_el,
            "Transform and normalize every character."_el,
            el::StringList{"CharSet::transform"_el},
            el::StringList{"identity"_el, "ascii-fold"_el, "collapse"_el, "unicode"_el}},
        {Operation::CaseFolded,
            "case-folded"_el,
            "Create a simple case-folded set."_el,
            el::StringList{"CharSet::caseFolded"_el},
            el::StringList{"unchanged"_el, "ascii"_el, "unicode"_el}},
        {Operation::ToLowercase,
            "to-lowercase"_el,
            "Create a lowercase set."_el,
            el::StringList{"CharSet::toLowercase"_el},
            el::StringList{"unchanged"_el, "ascii"_el, "unicode"_el}},
        {Operation::ToUppercase,
            "to-uppercase"_el,
            "Create an uppercase set."_el,
            el::StringList{"CharSet::toUppercase"_el},
            el::StringList{"unchanged"_el, "ascii"_el, "unicode"_el}},
        {Operation::ToString,
            "to-string"_el,
            "Convert to the default string width."_el,
            el::StringList{"CharSet::toString"_el},
            el::StringList{"empty"_el, "single"_el, "range"_el, "sparse-ascii"_el, "unicode-small"_el}},
        {Operation::ToU8String,
            "to-u8-string"_el,
            "Convert to UTF-8 text."_el,
            el::StringList{"CharSet::toU8String"_el},
            el::StringList{"empty"_el, "single"_el, "range"_el, "sparse-ascii"_el, "unicode-small"_el}},
        {Operation::ToU16String,
            "to-u16-string"_el,
            "Convert to UTF-16 text."_el,
            el::StringList{"CharSet::toU16String"_el},
            el::StringList{"empty"_el, "single"_el, "range"_el, "sparse-ascii"_el, "unicode-small"_el}},
        {Operation::ToU32String,
            "to-u32-string"_el,
            "Convert to UTF-32 text."_el,
            el::StringList{"CharSet::toU32String"_el},
            el::StringList{"empty"_el, "single"_el, "range"_el, "sparse-ascii"_el, "unicode-small"_el}},
        {Operation::ToSet,
            "to-set"_el,
            "Convert to an ordered character set."_el,
            el::StringList{"CharSet::toSet"_el},
            el::StringList{"empty"_el, "single"_el, "range"_el, "sparse-ascii"_el, "unicode-small"_el}},
        {Operation::ToList,
            "to-list"_el,
            "Convert to a character list."_el,
            el::StringList{"CharSet::toList"_el},
            el::StringList{"empty"_el, "single"_el, "range"_el, "sparse-ascii"_el, "unicode-small"_el}},
        {Operation::FromRange,
            "from-range"_el,
            "Create an inclusive character range."_el,
            el::StringList{"CharSet::fromRange"_el},
            el::StringList{"single"_el, "ascii"_el, "reversed"_el, "supplementary"_el, "invalid"_el}},
        {Operation::FromAsciiCategory,
            "from-ascii-category"_el,
            "Create an ASCII category set."_el,
            el::StringList{"CharSet::from(AsciiCategory)"_el},
            el::StringList{"digit"_el, "whitespace"_el, "control"_el, "punctuation"_el, "alphanumeric"_el}},
        {Operation::FromUnicodeCategory,
            "from-unicode-category"_el,
            "Create a Unicode general-category set."_el,
            el::StringList{"CharSet::from(UnicodeCategory)"_el},
            el::StringList{
                "uppercase-letter"_el, "decimal-number"_el, "other-symbol"_el, "control"_el, "unassigned"_el}},
        {Operation::FromUnicodeGroup,
            "from-unicode-group"_el,
            "Create a Unicode category-group set."_el,
            el::StringList{"CharSet::from(UnicodeCategoryGroup)"_el},
            el::StringList{"letter"_el, "number"_el, "punctuation"_el, "symbol"_el, "other"_el}},
        {Operation::FromPatternU8,
            "from-pattern-u8"_el,
            "Parse a UTF-8 character-set pattern."_el,
            el::StringList{"CharSet::fromPattern(const U8String&)"_el},
            el::StringList{"single"_el, "literals"_el, "ranges"_el, "mixed"_el, "unicode"_el}},
        {Operation::FromPatternU16,
            "from-pattern-u16"_el,
            "Parse a UTF-16 character-set pattern."_el,
            el::StringList{"CharSet::fromPattern(const U16String&)"_el},
            el::StringList{"single"_el, "literals"_el, "ranges"_el, "mixed"_el, "unicode"_el}},
        {Operation::FromPatternU32,
            "from-pattern-u32"_el,
            "Parse a UTF-32 character-set pattern."_el,
            el::StringList{"CharSet::fromPattern(const U32String&)"_el},
            el::StringList{"single"_el, "literals"_el, "ranges"_el, "mixed"_el, "unicode"_el}},
    };
    return descriptors;
}

}
