# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(bitmap-showcase)
add_subdirectory(display-all-attributes)
add_subdirectory(display-all-colors)
add_subdirectory(frame-color-animations)
add_subdirectory(frame-weaver)
add_subdirectory(grid-layout)
add_subdirectory(html-viewer)
add_subdirectory(key-input-demo)
add_subdirectory(log-viewer)
add_subdirectory(retro-plasma)
add_subdirectory(terminal-chronicle)
add_subdirectory(text-gallery)
