# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(ReadLine)
add_subdirectory(BitmapShowcase)
add_subdirectory(DisplayAllAttributes)
add_subdirectory(DisplayAllColors)
add_subdirectory(FrameColorAnimations)
add_subdirectory(FrameWeaver)
add_subdirectory(GridLayout)
add_subdirectory(HtmlViewer)
add_subdirectory(KeyInputDemo)
add_subdirectory(LogViewer)
add_subdirectory(RetroPlasma)
add_subdirectory(TerminalChronicle)
add_subdirectory(TextGallery)
