[package]
name = "erbsland-core-compression-interop-counterpart"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bzip2 = { version = "=0.6.1", default-features = false, features = ["bzip2-sys", "static"] }
flate2 = { version = "=1.1.10", default-features = false, features = ["miniz_oxide"] }
lz4 = "=1.28.1"
lzma-rs = "=0.3.0"
miniz_oxide = "=0.9.1"
xz2 = { version = "=0.1.7", features = ["static"] }
zstd = "=0.13.3"
