// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "ByteInputStream.hpp"
#include "ByteOutputStream.hpp"
#include "InputStream.hpp"
#include "InputStreamSettings.hpp"
#include "OutputStream.hpp"
#include "OutputStreamSettings.hpp"
#include "StandardStreamRedirect.hpp"
#include "StandardStreams.hpp"
#include "StreamCloseStatus.hpp"
#include "StreamError.hpp"
#include "StreamErrorContext.hpp"
#include "StreamErrorSource.hpp"
#include "StreamPositionOrigin.hpp"
#include "StreamPositionStatus.hpp"
#include "StreamPositioning.hpp"
#include "StreamReadResult.hpp"
#include "StreamReadStatus.hpp"
#include "StreamState.hpp"
#include "StreamWaitStatus.hpp"
#include "StreamWriteStatus.hpp"
#include "StringBuilderStream.hpp"
#include "TempByteOutputStream.hpp"
#include "TempTextOutputStream.hpp"
#include "TextInputStream.hpp"
#include "TextOutputStream.hpp"
#include "TextPrintContext.hpp"


