// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "Alignment.hpp"
#include "AlignmentFlags.hpp"
#include "BlockAlignedSource.hpp"
#include "BlockAnchor.hpp"
#include "BlockAxisMapper.hpp"
#include "BlockCoordinate.hpp"
#include "BlockDirection.hpp"
#include "BlockMargins.hpp"
#include "BlockPosition.hpp"
#include "BlockPositionList.hpp"
#include "BlockRectangle.hpp"
#include "BlockRectangleList.hpp"
#include "BlockSize.hpp"
#include "Orientation.hpp"
#include "StdFormatForBlock.hpp"
#include "Symmetry.hpp"


