// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "U8Format.hpp"
#include "U8String.hpp"
#include "U8StringCIHashMap.hpp"
#include "U8StringCIHashSet.hpp"
#include "U8StringCIMap.hpp"
#include "U8StringCISet.hpp"
#include "U8StringCharView.hpp"
#include "U8StringConstIterator.hpp"
#include "U8StringHashMap.hpp"
#include "U8StringHashSet.hpp"
#include "U8StringList.hpp"
#include "U8StringLiteral.hpp"
#include "U8StringMap.hpp"
#include "U8StringSet.hpp"
#include "U8StringView.hpp"
#include "U8StringViewList.hpp"


