# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)

add_subdirectory(_common)
add_subdirectory(cterm)
add_subdirectory(cryptology)
add_subdirectory(err)
add_subdirectory(event)
add_subdirectory(math)
add_subdirectory(option)
add_subdirectory(path)
add_subdirectory(random)
add_subdirectory(stream)
add_subdirectory(text)
