# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)
include_guard(GLOBAL)

function(_erbsland_core_setup_target target visibility configured_property)
    get_target_property(is_configured "${target}" "${configured_property}")
    if(is_configured)
        return()
    endif()

    if(TARGET erbsland::core)
        set(core_target erbsland::core)
    elseif(TARGET ErbslandDEV::erbsland-core)
        set(core_target ErbslandDEV::erbsland-core)
    else()
        message(FATAL_ERROR "The Erbsland Core target is unavailable.")
    endif()
    target_link_libraries("${target}" "${visibility}" "${core_target}")
    target_compile_features("${target}" "${visibility}" cxx_std_20)
    set_target_properties("${target}" PROPERTIES
            CXX_SCAN_FOR_MODULES OFF
            "${configured_property}" TRUE
    )
    if(MSVC)
        target_compile_options("${target}" "${visibility}" /utf-8)
    endif()
endfunction()

function(erbsland_core_setup_application)
    set(options "")
    set(one_value_args TARGET)
    set(multi_value_args "")
    cmake_parse_arguments(ARGS "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

    if(ARGS_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Unexpected arguments for erbsland_core_setup_application: ${ARGS_UNPARSED_ARGUMENTS}")
    endif()
    if(NOT ARGS_TARGET)
        message(FATAL_ERROR "erbsland_core_setup_application requires TARGET.")
    endif()
    if(NOT TARGET "${ARGS_TARGET}")
        message(FATAL_ERROR "erbsland_core_setup_application target does not exist: ${ARGS_TARGET}")
    endif()
    get_target_property(target_type "${ARGS_TARGET}" TYPE)
    if(NOT target_type STREQUAL "EXECUTABLE")
        message(FATAL_ERROR "erbsland_core_setup_application supports executable targets only: ${ARGS_TARGET}")
    endif()
    _erbsland_core_setup_target("${ARGS_TARGET}" PRIVATE ERBSLAND_CORE_APPLICATION_CONFIGURED)
endfunction()

function(erbsland_core_setup_static_library)
    set(options "")
    set(one_value_args TARGET)
    set(multi_value_args "")
    cmake_parse_arguments(ARGS "${options}" "${one_value_args}" "${multi_value_args}" ${ARGN})

    if(ARGS_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Unexpected arguments for erbsland_core_setup_static_library: ${ARGS_UNPARSED_ARGUMENTS}")
    endif()
    if(NOT ARGS_TARGET)
        message(FATAL_ERROR "erbsland_core_setup_static_library requires TARGET.")
    endif()
    if(NOT TARGET "${ARGS_TARGET}")
        message(FATAL_ERROR "erbsland_core_setup_static_library target does not exist: ${ARGS_TARGET}")
    endif()
    get_target_property(target_type "${ARGS_TARGET}" TYPE)
    if(NOT target_type STREQUAL "STATIC_LIBRARY")
        message(FATAL_ERROR "erbsland_core_setup_static_library supports static library targets only: ${ARGS_TARGET}")
    endif()
    _erbsland_core_setup_target("${ARGS_TARGET}" PUBLIC ERBSLAND_CORE_STATIC_LIBRARY_CONFIGURED)
endfunction()
