# Copyright (c) 2026 Tobias Erbsland - https://erbsland.dev
# SPDX-License-Identifier: Apache-2.0

cmake_minimum_required(VERSION 3.28)
include_guard(GLOBAL)

function(_erbsland_core_package_tool)
    if(TARGET erbsland-core-package-tool)
        return()
    endif()
    if(EXISTS "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/tools/package/CMakeLists.txt")
        set(tool_source "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/tools/package")
    else()
        set(tool_source "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/package-tool")
    endif()
    if(NOT EXISTS "${tool_source}/CMakeLists.txt")
        message(FATAL_ERROR "Erbsland Core package tool sources are unavailable: ${tool_source}")
    endif()
    add_subdirectory("${tool_source}" "${CMAKE_BINARY_DIR}/erbsland-core-package-tool-build" EXCLUDE_FROM_ALL)
endfunction()

# Register one ZIP package as an install rule. Build the named executables before installing.
# Usage: erbsland_core_package(TARGET <executable> | TARGETS <executables...>
#                            [NAME <name>] [CONFIG <elcl-file>] [OUTPUT_DIRECTORY <directory>])
function(erbsland_core_package)
    if(NOT WIN32 AND NOT APPLE)
        message(FATAL_ERROR "erbsland_core_package supports Windows and macOS only.")
    endif()
    cmake_parse_arguments(ARGS "" "TARGET;NAME;CONFIG;OUTPUT_DIRECTORY" "TARGETS" ${ARGN})
    if(ARGS_UNPARSED_ARGUMENTS OR ARGS_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "Invalid erbsland_core_package arguments: ${ARGS_UNPARSED_ARGUMENTS}")
    endif()
    if((ARGS_TARGET AND ARGS_TARGETS) OR (NOT ARGS_TARGET AND NOT ARGS_TARGETS))
        message(FATAL_ERROR "erbsland_core_package requires exactly one of TARGET or TARGETS.")
    endif()
    if(ARGS_TARGET)
        set(package_targets "${ARGS_TARGET}")
    else()
        set(package_targets ${ARGS_TARGETS})
    endif()
    if(NOT ARGS_NAME)
        set(ARGS_NAME "${CMAKE_PROJECT_NAME}")
    endif()
    if(NOT ARGS_NAME MATCHES "^[A-Za-z0-9][A-Za-z0-9._-]*$")
        message(FATAL_ERROR "Package NAME must be a portable filename component: ${ARGS_NAME}")
    endif()
    get_property(registered GLOBAL PROPERTY ERBSLAND_CORE_PACKAGE_NAMES)
    if(ARGS_NAME IN_LIST registered)
        message(FATAL_ERROR "Package NAME is already registered: ${ARGS_NAME}")
    endif()
    set_property(GLOBAL APPEND PROPERTY ERBSLAND_CORE_PACKAGE_NAMES "${ARGS_NAME}")
    foreach(package_target IN LISTS package_targets)
        if(NOT TARGET "${package_target}")
            message(FATAL_ERROR "Package target does not exist: ${package_target}")
        endif()
        get_target_property(target_type "${package_target}" TYPE)
        if(NOT target_type STREQUAL "EXECUTABLE")
            message(FATAL_ERROR "Package target must be an executable: ${package_target}")
        endif()
    endforeach()
    if(ARGS_CONFIG)
        get_filename_component(config_path "${ARGS_CONFIG}" ABSOLUTE BASE_DIR "${CMAKE_SOURCE_DIR}")
        if(NOT EXISTS "${config_path}")
            message(FATAL_ERROR "Package CONFIG does not exist: ${config_path}")
        endif()
    else()
        set(config_path "${CMAKE_SOURCE_DIR}/package.elcl")
    endif()
    if(ARGS_OUTPUT_DIRECTORY)
        get_filename_component(output_directory "${ARGS_OUTPUT_DIRECTORY}" ABSOLUTE BASE_DIR "${CMAKE_SOURCE_DIR}")
    else()
        set(output_directory "${CMAKE_SOURCE_DIR}/packages")
    endif()
    _erbsland_core_package_tool()
    if(CMAKE_CXX_COMPILER_ARCHITECTURE_ID)
        set(package_architecture "${CMAKE_CXX_COMPILER_ARCHITECTURE_ID}")
    elseif(CMAKE_VS_PLATFORM_NAME)
        set(package_architecture "${CMAKE_VS_PLATFORM_NAME}")
    else()
        set(package_architecture "${CMAKE_SYSTEM_PROCESSOR}")
    endif()
    set(package_arguments
            --project-root "${CMAKE_SOURCE_DIR}"
            --project-name "${CMAKE_PROJECT_NAME}"
            --project-version "${CMAKE_PROJECT_VERSION}"
            --package-name "${ARGS_NAME}"
            --config "${config_path}"
            --output-directory "${output_directory}"
            --architecture "${package_architecture}"
            --cmake "${CMAKE_COMMAND}")
    find_package(Git QUIET)
    if(GIT_FOUND)
        list(APPEND package_arguments --git "${GIT_EXECUTABLE}")
    endif()
    foreach(package_target IN LISTS package_targets)
        list(APPEND package_arguments --target-name "${package_target}"
                --target-path "$<TARGET_FILE:${package_target}>")
        get_target_property(is_bundle "${package_target}" MACOSX_BUNDLE)
        if(is_bundle)
            list(APPEND package_arguments --bundle-target "${package_target}")
        endif()
    endforeach()
    set(package_command "")
    foreach(package_argument IN LISTS package_arguments)
        string(APPEND package_command " [==[${package_argument}]==]")
    endforeach()
    # Generator expressions are expanded in install(CODE), making each configuration use its own binaries.
    set(install_code "
if(NOT CMAKE_INSTALL_CONFIG_NAME MATCHES \"^(Release|RelWithDebInfo)$\")
    message(WARNING \"Package ${ARGS_NAME}: no ZIP is created for configuration '\${CMAKE_INSTALL_CONFIG_NAME}'.\")
else()
    execute_process(COMMAND \"${CMAKE_COMMAND}\" --build \"${CMAKE_BINARY_DIR}\"
            --target erbsland-core-package-tool --config \"\${CMAKE_INSTALL_CONFIG_NAME}\"
            COMMAND_ERROR_IS_FATAL ANY)
    execute_process(COMMAND \"$<TARGET_FILE:erbsland-core-package-tool>\"${package_command}
            COMMAND_ERROR_IS_FATAL ANY)
endif()")
    install(CODE "${install_code}" COMPONENT "Package-${ARGS_NAME}")
endfunction()
