// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "Diagnostic.hpp"
#include "DiagnosticHelper.hpp"
#include "ErrorDocumentBuilder.hpp"
#include "Exception.hpp"
#include "LogicError.hpp"
#include "OutOfRangeError.hpp"
#include "OverflowError.hpp"
#include "ParameterError.hpp"
#include "ParseError.hpp"
#include "RuntimeError.hpp"


