// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "ApplicationError.hpp"
#include "EncodingError.hpp"
#include "Exception.hpp"
#include "FormatError.hpp"
#include "LogicError.hpp"
#include "OptionError.hpp"
#include "OutOfRangeError.hpp"
#include "OverflowError.hpp"
#include "ParameterError.hpp"
#include "ParseError.hpp"
#include "ParseNumberError.hpp"
#include "RandomError.hpp"
#include "RuntimeError.hpp"
#include "StreamError.hpp"
#include "ThrowHelper.hpp"
#include "U16EncodingError.hpp"
#include "U32EncodingError.hpp"
#include "U8EncodingError.hpp"


