// Copyright © 2026 Tobias Erbsland - https://erbsland.dev
// SPDX-License-Identifier: Apache-2.0
#pragma once

// !!! THIS IS A GENERATED FILE - DO NOT EDIT MANUALLY !!!
// This file was generated by the "update_includes.py" script.

#include "TlsAlertDescription.hpp"
#include "TlsClientConnectOptions.hpp"
#include "TlsClientConnection.hpp"
#include "TlsClientConnectionEventEditor.hpp"
#include "TlsServerAcceptOptions.hpp"
#include "TlsServerConnection.hpp"
#include "TlsServerConnectionEventEditor.hpp"
#include "TlsServerIdentityMapping.hpp"


