name: Docs

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # actions/checkout@v7.0.1
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      # actions/setup-python@v7.0.0
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: '3.13'

      - name: Install Python dependencies from requirements.txt
        run: pip install -r doc/requirements-doc.txt

      - name: Install Doxygen
        run: sudo apt-get install doxygen -y
        shell: bash

      - name: Prepare Doxygen input
        run: python3 doc/_tools/preprocess_sources.py

      - name: Build documentation
        run: sphinx-build doc _build

      - name: Upload Pages artifact
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        # actions/upload-pages-artifact@v5.0.0
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: _build

  deploy:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # actions/deploy-pages@v5.0.1
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346
